// Code generated by vk-gen. DO NOT EDIT.

// Package arm_format_pack provides bindings for the VK_ARM_format_pack extension.
// Author: ARM
// Contact: Jan-Harald Fredriksen @janharaldfredriksen-arm
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2025-03-24
//
// Interactions and External Dependencies:
//
// Contributors:
//   - Jan-Harald Fredriksen, Arm
//   - Lisa Wu, Arm
//   - Oivind Boge, Arm
//
// Description:
//
// This extension adds support for additional 1-, 2- and 4-component formats
// with 10, 12, or 14 bits of components in 16-bit containers.
//
// Issues:
//
// What do we call this extension?:
//
// # RESOLVED
//
// Many existing extension have the format in the name, but in this case we
// want to expose multiple formats.
//
// We will describe this set of formats as a "pack".
//
// Compatibility classes:
//
// RESOLVED:
//
// Should these additional formats be in the same compatibility class as any
// other formats? For single-plane formats, we put formats with the same number
// of bits (but different types) in the same class.
// Each multi-plane or subsampled format gets its own compatibility class.
// This is consistent with how existing formats are handled.
//
// Format feature requirements:
//
// RESOLVED:
//
// The format feature queries could be used to determine what is supported on
// any given implementation, but it may be useful to establish a baseline
// requirement in the specification.
// For that purpose, we require a set of format features - sufficient to enable
// texture operations - to be supported for the added unsigned integer
// single-plane formats.
// Other formats and format features are optional.
//
// Version History:
//
//   - Revision 1, 2025-03-24
//   - Initial revision
package arm_format_pack
