// Code generated by vk-gen. DO NOT EDIT.

// Package amd_shader_image_load_store_lod provides bindings for the VK_AMD_shader_image_load_store_lod extension.
// Author: AMD
// Contact: Dominik Witczak @dominikwitczakamd
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2017-08-21
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLregistry}/AMD/AMDshaderimageloadstorelod.txt[GLAMDshaderimageloadstore_lod]
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Dominik Witczak, AMD
//   - Qun Lin, AMD
//   - Rex Xu, AMD
//
// Description:
//
// This extension adds support for the following SPIR-V extension in Vulkan:
//
//   - {spirv}/AMD/SPVAMDshaderimageloadstorelod.html[SPVAMDshaderimageloadstorelod]
//
// Version History:
//
//   - Revision 1, 2017-08-21 (Dominik Witczak)
//   - Initial draft
package amd_shader_image_load_store_lod
