// Code generated by vk-gen. DO NOT EDIT.

package ext_depth_clamp_control

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdSetDepthClampRangeEXT uintptr
)

// Init resolves and initializes all VK_EXT_depth_clamp_control extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdSetDepthClampRangeEXT = vulkan.GetDeviceProcAddr(device, "vkCmdSetDepthClampRangeEXT")
}

// CmdSetDepthClampRangeEXT - Set the viewport depth clamp range dynamically for a command buffer (vkCmdSetDepthClampRangeEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - depthClampMode: determines how the clamp range is determined for each viewport.
//   - depthClampRange: sets the depth clamp range for all viewports if depthClampMode is VK_DEPTH_CLAMP_MODE_USER_DEFINED_RANGE_EXT.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetDepthClampRangeEXT.html
func CmdSetDepthClampRangeEXT(commandBuffer vulkan.CommandBuffer, depthClampMode vulkan.DepthClampModeEXT, depthClampRange *vulkan.DepthClampRangeEXT) {
	c_depthClampRange := depthClampRange.Raw()
	vulkan.CallSyscall(pfnCmdSetDepthClampRangeEXT, uintptr(commandBuffer), uintptr(depthClampMode), uintptr(unsafe.Pointer(c_depthClampRange)))
}
