// Code generated by vk-gen. DO NOT EDIT.

package khr_push_descriptor

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdPushDescriptorSetKHR             uintptr
	pfnCmdPushDescriptorSetWithTemplateKHR uintptr
)

// Init resolves and initializes all VK_KHR_push_descriptor extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdPushDescriptorSetKHR = vulkan.GetInstanceProcAddr(instance, "vkCmdPushDescriptorSetKHR")
	pfnCmdPushDescriptorSetWithTemplateKHR = vulkan.GetInstanceProcAddr(instance, "vkCmdPushDescriptorSetWithTemplateKHR")
}

// CmdPushDescriptorSetKHR executes vkCmdPushDescriptorSetKHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPushDescriptorSetKHR.html
func CmdPushDescriptorSetKHR() {
	vulkan.CallSyscall(pfnCmdPushDescriptorSetKHR)
}

// CmdPushDescriptorSetWithTemplateKHR executes vkCmdPushDescriptorSetWithTemplateKHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdPushDescriptorSetWithTemplateKHR.html
func CmdPushDescriptorSetWithTemplateKHR() {
	vulkan.CallSyscall(pfnCmdPushDescriptorSetWithTemplateKHR)
}
