// Code generated by vk-gen. DO NOT EDIT.

// Package ext_filter_cubic provides bindings for the VK_EXT_filter_cubic extension.
// Author: QCOM
// Contact: Matthew Netsch @mnetsch
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2019-12-13
//
// Contributors:
//   - Bill Licea-Kane, Qualcomm Technologies, Inc.
//   - Andrew Garrard, Samsung
//   - Daniel Koch, NVIDIA
//   - Donald Scorgie, Imagination Technologies
//   - Graeme Leese, Broadcom
//   - Jan-Harald Fredriksen, ARM
//   - Jeff Leger, Qualcomm Technologies, Inc.
//   - Tobias Hector, AMD
//   - Tom Olson, ARM
//   - Stuart Smith, Imagination Technologies
//
// Description:
//
// VKEXTfiltercubic extends VKIMGfiltercubic.
//
// It documents cubic filtering of other image view types.
// It adds new structures that can: be added to the pNext chain of
// VkPhysicalDeviceImageFormatInfo2 and VkImageFormatProperties2
// that can: be used to determine which image types and which image view types
// support cubic filtering.
//
// Version History:
//
//   - Revision 3, 2019-12-13 (wwlk)
//   - Delete requirement to cubic filter the formats USCALED_PACKED32,
//     SSCALEDPACKED32, UINTPACK32, and SINT_PACK32 (cut/paste error)
//   - Revision 2, 2019-06-05 (wwlk)
//   - Clarify 1D optional
//   - Revision 1, 2019-01-24 (wwlk)
//   - Initial version
package ext_filter_cubic
