// Code generated by vk-gen. DO NOT EDIT.

package android_external_memory_android_hardware_buffer

const (
	ExtensionName   = "VK_ANDROID_external_memory_android_hardware_buffer"
	ExtensionNumber = 130
)
