// Code generated by vk-gen. DO NOT EDIT.

// Package amd_draw_indirect_count provides bindings for the VK_AMD_draw_indirect_count extension.
// Author: AMD
// Contact: Daniel Rakos @drakos-amd
// Promoted to: VK_KHR_draw_indirect_count
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2016-08-23
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Matthaeus G. Chajdas, AMD
//   - Derrick Owens, AMD
//   - Graham Sellers, AMD
//   - Daniel Rakos, AMD
//   - Dominik Witczak, AMD
//
// Description:
//
// This extension allows an application to source the number of draws for
// indirect drawing commands from a buffer.
// This enables applications to generate an arbitrary number of drawing
// commands and execute them without host intervention.
//
// Promotion to `VK_KHR_draw_indirect_count`:
//
// All functionality in this extension is included in
// VKKHRdrawindirectcount, with the suffix changed to KHR.
// The original type, enum, and command names are still available as aliases of
// the core functionality.
//
// Version History:
//
//   - Revision 2, 2016-08-23 (Dominik Witczak)
//   - Minor fixes
//   - Revision 1, 2016-07-21 (Matthaeus Chajdas)
//   - Initial draft
package amd_draw_indirect_count
