// Code generated by vk-gen. DO NOT EDIT.

// Package nv_shader_sm_builtins provides bindings for the VK_NV_shader_sm_builtins extension.
// Author: NV
// Contact: Daniel Koch @dgkoch
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2019-05-28
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLSLregistry}/nv/GLSLNVshadersmbuiltins.txt[GLNVshadersmbuiltins]
//
// Contributors:
//   - Jeff Bolz, NVIDIA
//   - Eric Werness, NVIDIA
//
// Description:
//
// This extension provides the ability to determine device-specific properties
// on NVIDIA GPUs.
// It provides the number of streaming multiprocessors (SMs), the maximum
// number of warps (subgroups) that can run on an SM, and shader builtins to
// enable invocations to identify which SM and warp a shader invocation is
// executing on.
//
// This extension enables support for the SPIR-V ShaderSMBuiltinsNV
// capability.
//
// These properties and built-ins should: typically only be used for debugging
// purposes.
//
// New or Modified Built-In Variables:
//
//   - WarpsPerSMNV
//   - SMCountNV
//   - WarpIDNV
//   - SMIDNV
//
// New SPIR-V Capabilities:
//
//   - <<spirvenv-capabilities-table-ShaderSMBuiltinsNV,
//     ShaderSMBuiltinsNV>>
//
// Issues:
// . What should we call this extension?
// +
// RESOLVED:
// Other options considered included:
//
//   - NVshadersmid - but SMID is really easy to typo/confuse as SIMD.
//     NVshadersm_info - but Info* is typically reserved for input
//     structures
//
// Version History:
//
//   - Revision 1, 2019-05-28 (Daniel Koch)
//   - Internal revisions
package nv_shader_sm_builtins
