// Code generated by vk-gen. DO NOT EDIT.

package nv_mesh_shader

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdDrawMeshTasksIndirectCountNV uintptr
	pfnCmdDrawMeshTasksIndirectNV      uintptr
	pfnCmdDrawMeshTasksNV              uintptr
)

// Init resolves and initializes all VK_NV_mesh_shader extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdDrawMeshTasksIndirectCountNV = vulkan.GetDeviceProcAddr(device, "vkCmdDrawMeshTasksIndirectCountNV")
	pfnCmdDrawMeshTasksIndirectNV = vulkan.GetDeviceProcAddr(device, "vkCmdDrawMeshTasksIndirectNV")
	pfnCmdDrawMeshTasksNV = vulkan.GetDeviceProcAddr(device, "vkCmdDrawMeshTasksNV")
}

// CmdDrawMeshTasksIndirectCountNV - Perform an indirect mesh tasks draw with the draw count sourced from a buffer (vkCmdDrawMeshTasksIndirectCountNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - buffer: is the buffer containing draw parameters.
//   - offset: is the byte offset into buffer where parameters begin.
//   - countBuffer: is the buffer containing the draw count.
//   - countBufferOffset: is the byte offset into countBuffer where the draw count begins.
//   - maxDrawCount: specifies the maximum number of draws that will be executed. The actual number of executed draw calls is the minimum of the count specified in countBuffer and maxDrawCount.
//   - stride: is the byte stride between successive sets of draw parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawMeshTasksIndirectCountNV.html
func CmdDrawMeshTasksIndirectCountNV(commandBuffer vulkan.CommandBuffer, buffer vulkan.Buffer, offset vulkan.DeviceSize, countBuffer vulkan.Buffer, countBufferOffset vulkan.DeviceSize, maxDrawCount uint32, stride uint32) {
	vulkan.CallSyscall(pfnCmdDrawMeshTasksIndirectCountNV, uintptr(commandBuffer), uintptr(buffer), uintptr(offset), uintptr(countBuffer), uintptr(countBufferOffset), uintptr(maxDrawCount), uintptr(stride))
}

// CmdDrawMeshTasksIndirectNV - Issue an indirect mesh tasks draw into a command buffer (vkCmdDrawMeshTasksIndirectNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - buffer: is the buffer containing draw parameters.
//   - offset: is the byte offset into buffer where parameters begin.
//   - drawCount: is the number of draws to execute, and can be zero.
//   - stride: is the byte stride between successive sets of draw parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawMeshTasksIndirectNV.html
func CmdDrawMeshTasksIndirectNV(commandBuffer vulkan.CommandBuffer, buffer vulkan.Buffer, offset vulkan.DeviceSize, drawCount uint32, stride uint32) {
	vulkan.CallSyscall(pfnCmdDrawMeshTasksIndirectNV, uintptr(commandBuffer), uintptr(buffer), uintptr(offset), uintptr(drawCount), uintptr(stride))
}

// CmdDrawMeshTasksNV - Draw mesh task work items (vkCmdDrawMeshTasksNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - taskCount: is the number of local workgroups to dispatch in the X dimension. Y and Z dimension are implicitly set to one.
//   - firstTask: is the X component of the first workgroup ID.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawMeshTasksNV.html
func CmdDrawMeshTasksNV(commandBuffer vulkan.CommandBuffer, taskCount uint32, firstTask uint32) {
	vulkan.CallSyscall(pfnCmdDrawMeshTasksNV, uintptr(commandBuffer), uintptr(taskCount), uintptr(firstTask))
}
