// Code generated by vk-gen. DO NOT EDIT.

package khr_maintenance10

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdEndRendering2KHR uintptr
)

// Init resolves and initializes all VK_KHR_maintenance10 extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdEndRendering2KHR = vulkan.GetDeviceProcAddr(device, "vkCmdEndRendering2KHR")
}

// CmdEndRendering2KHR - End a dynamic render pass instance (vkCmdEndRendering2KHR).
// Parameters:
//   - commandBuffer: is the command buffer in which to record the command.
//   - renderingEndInfo: is NULL or a pointer to a VkRenderingEndInfoKHR structure containing information about how the render pass will be ended.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdEndRendering2KHR.html
func CmdEndRendering2KHR(commandBuffer vulkan.CommandBuffer, renderingEndInfo *vulkan.RenderingEndInfoKHR) {
	c_renderingEndInfo := renderingEndInfo.Raw()
	vulkan.CallSyscall(pfnCmdEndRendering2KHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_renderingEndInfo)))
}
