package emitter

import (
	"fmt"
	"sort"
	"strings"

	"github.com/KCoen/vk/generator/indexer"
)

// EmitBranchBitmasks generates bitmasks_gen.go for an API branch package (vulkan, vulkanbase, vulkansc).
func EmitBranchBitmasks(branch *indexer.ApiBranchInfo, idx *indexer.Index) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by vk-gen. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", branch.PkgName))
	sb.WriteString("import \"fmt\"\n\n")

	handledEnumGroups := make(map[string]bool)
	globalSeenConstants := make(map[string]bool)

	var maskNames []string
	for name := range branch.Bitmasks {
		maskNames = append(maskNames, name)
	}
	sort.Strings(maskNames)

	for _, name := range maskNames {
		bm := branch.Bitmasks[name]
		underlying := "Flags"
		if bm.Bitwidth == 64 {
			underlying = "Flags64"
		}

		lead := fmt.Sprintf("%s is a bitmask of %s.", bm.GoName, bm.Name)
		if bm.ShortDesc != "" {
			lead = fmt.Sprintf("%s - %s (%s).", bm.GoName, bm.ShortDesc, bm.Name)
		} else if bm.Comment != "" {
			lead = fmt.Sprintf("%s - %s (%s).", bm.GoName, bm.Comment, bm.Name)
		}

		doc := FormatDocComment(lead, "Documented at: "+FormatVulkanDocLink(name))
		sb.WriteString(doc)
		sb.WriteString(fmt.Sprintf("type %s %s\n\n", bm.GoName, underlying))

		// If there is an associated BitsType, declare it as a type alias
		flagBitsName := ""
		if bm.BitsType != "" {
			flagBitsName = indexer.CleanTypeName(bm.BitsType)
		} else if strings.HasSuffix(bm.GoName, "Flags") {
			flagBitsName = strings.TrimSuffix(bm.GoName, "Flags") + "FlagBits"
		} else if strings.HasSuffix(bm.GoName, "FlagsKHR") {
			flagBitsName = strings.TrimSuffix(bm.GoName, "FlagsKHR") + "FlagBitsKHR"
		} else if strings.HasSuffix(bm.GoName, "FlagsEXT") {
			flagBitsName = strings.TrimSuffix(bm.GoName, "FlagsEXT") + "FlagBitsEXT"
		} else if strings.HasSuffix(bm.GoName, "FlagsNV") {
			flagBitsName = strings.TrimSuffix(bm.GoName, "FlagsNV") + "FlagBitsNV"
		}

		if flagBitsName != "" && flagBitsName != bm.GoName {
			sb.WriteString(fmt.Sprintf("// %s is an alias of %s.\n", flagBitsName, bm.GoName))
			sb.WriteString(fmt.Sprintf("type %s = %s\n\n", flagBitsName, bm.GoName))
		}

		// Methods
		sb.WriteString(fmt.Sprintf("// Has returns true if all bits of flag are set in %s.\n", bm.GoName))
		sb.WriteString(fmt.Sprintf("func (f %s) Has(flag %s) bool {\n\treturn (f & flag) == flag\n}\n\n", bm.GoName, bm.GoName))

		sb.WriteString(fmt.Sprintf("// With returns a new %s with the given flag bits added.\n", bm.GoName))
		sb.WriteString(fmt.Sprintf("func (f %s) With(flag %s) %s {\n\treturn f | flag\n}\n\n", bm.GoName, bm.GoName, bm.GoName))

		sb.WriteString(fmt.Sprintf("// Without returns a new %s with the given flag bits removed.\n", bm.GoName))
		sb.WriteString(fmt.Sprintf("func (f %s) Without(flag %s) %s {\n\treturn f &^ flag\n}\n\n", bm.GoName, bm.GoName, bm.GoName))

		sb.WriteString(fmt.Sprintf("// String returns the string representation of %s.\n", bm.GoName))
		sb.WriteString(fmt.Sprintf("func (f %s) String() string {\n\treturn fmt.Sprintf(\"%s(0x%%X)\", %s(f))\n}\n\n", bm.GoName, bm.GoName, underlying))

		// Check if there is an associated FlagBits enum group
		if bm.BitsType != "" {
			handledEnumGroups[bm.BitsType] = true
			if eg, ok := branch.EnumGroups[bm.BitsType]; ok && len(eg.Values) > 0 {
				handledEnumGroups[eg.Name] = true

				var validValues []indexer.EnumValue
				for _, v := range eg.Values {
					if globalSeenConstants[v.GoName] {
						continue
					}
					validValues = append(validValues, v)
				}

				if len(validValues) > 0 {
					sb.WriteString("const (\n")

					for _, v := range validValues {
						if globalSeenConstants[v.GoName] {
							continue
						}
						globalSeenConstants[v.GoName] = true

						comment := v.Comment
						if comment != "" {
							comment = " // " + strings.TrimSpace(comment)
						}

						if v.IsAlias && v.AliasOf != "" {
							sb.WriteString(fmt.Sprintf("\t%s %s = %s%s\n", v.GoName, bm.GoName, v.AliasOf, comment))
						} else if v.ValueStr != "" {
							sb.WriteString(fmt.Sprintf("\t%s %s = %s%s\n", v.GoName, bm.GoName, v.ValueStr, comment))
						}
					}
					sb.WriteString(")\n\n")
				}
			}
		}
	}

	// Also emit FlagBits enums that might not be in branch.Bitmasks
	var egNames []string
	for name := range branch.EnumGroups {
		egNames = append(egNames, name)
	}
	sort.Strings(egNames)

	for _, name := range egNames {
		eg := branch.EnumGroups[name]
		if eg.Type != "bitmask" {
			continue
		}
		if handledEnumGroups[name] {
			continue
		}

		flagsName := strings.TrimSuffix(name, "Bits")
		if strings.HasSuffix(name, "FlagBits") {
			flagsName = strings.TrimSuffix(name, "FlagBits") + "Flags"
		} else if strings.HasSuffix(name, "FlagBitsKHR") {
			flagsName = strings.TrimSuffix(name, "FlagBitsKHR") + "FlagsKHR"
		} else if strings.HasSuffix(name, "FlagBitsEXT") {
			flagsName = strings.TrimSuffix(name, "FlagBitsEXT") + "FlagsEXT"
		}
		if _, exists := branch.Bitmasks[flagsName]; exists {
			continue
		}

		typeKind := "Flags"
		if eg.Bitwidth == 64 {
			typeKind = "Flags64"
		}

		lead := fmt.Sprintf("%s is a bitmask of %s.", eg.GoName, eg.Name)
		if eg.ShortDesc != "" {
			lead = fmt.Sprintf("%s - %s (%s).", eg.GoName, eg.ShortDesc, eg.Name)
		} else if eg.Comment != "" {
			lead = fmt.Sprintf("%s - %s (%s).", eg.GoName, eg.Comment, eg.Name)
		}

		doc := FormatDocComment(lead, "Documented at: "+FormatVulkanDocLink(name))
		sb.WriteString(doc)
		sb.WriteString(fmt.Sprintf("type %s %s\n\n", eg.GoName, typeKind))

		if flagsName != eg.GoName {
			sb.WriteString(fmt.Sprintf("// %s is an alias of %s.\n", flagsName, eg.GoName))
			sb.WriteString(fmt.Sprintf("type %s = %s\n\n", flagsName, eg.GoName))
		}

		var validValues []indexer.EnumValue
		for _, v := range eg.Values {
			if globalSeenConstants[v.GoName] {
				continue
			}
			validValues = append(validValues, v)
		}

		if len(validValues) > 0 {
			sb.WriteString("const (\n")
			for _, v := range validValues {
				if globalSeenConstants[v.GoName] {
					continue
				}
				globalSeenConstants[v.GoName] = true

				comment := v.Comment
				if comment != "" {
					comment = " // " + strings.TrimSpace(comment)
				}

				if v.IsAlias && v.AliasOf != "" {
					sb.WriteString(fmt.Sprintf("\t%s %s = %s%s\n", v.GoName, eg.GoName, v.AliasOf, comment))
				} else if v.ValueStr != "" {
					sb.WriteString(fmt.Sprintf("\t%s %s = %s%s\n", v.GoName, eg.GoName, v.ValueStr, comment))
				}
			}
			sb.WriteString(")\n\n")
		}
	}

	// Bitmask Aliases
	var aliasNames []string
	for name, a := range branch.TypeAliases {
		if a.Category == "bitmask" {
			aliasNames = append(aliasNames, name)
		}
	}
	sort.Strings(aliasNames)

	if len(aliasNames) > 0 {
		sb.WriteString("// --- Bitmask Type Aliases ---\n\n")
		for _, name := range aliasNames {
			a := idx.TypeAliases[name]
			doc := FormatDocComment(fmt.Sprintf("%s is an alias of %s.", a.GoName, a.GoAlias),
				a.Comment,
				"Documented at: "+FormatVulkanDocLink(name),
			)
			sb.WriteString(doc)
			sb.WriteString(fmt.Sprintf("type %s = %s\n\n", a.GoName, a.GoAlias))
		}
	}

	return sb.String(), nil
}
