// Code generated by vk-gen. DO NOT EDIT.

// Package ext_shader_long_vector provides bindings for the VK_EXT_shader_long_vector extension.
// Author: EXT
// Contact: Jeff Bolz @jeffbolznv
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2025-06-24
//
// Interactions and External Dependencies:
//   - This extension requires
//     {spirv}/EXT/SPVEXTlongvector.html[SPVEXTlongvector]
//   - This extension provides API support for
//     {GLSLregistry}/ext/GLSLEXTlongvector.txt[GLEXTlongvector]
//
// Contributors:
//   - Jeff Bolz, NVIDIA
//   - Spencer Fricke, LunarG
//
// Description:
//
// This extension adds support for using vector types with more than four
// components in SPIR-V.
//
// Long vector types are defined by the
// {spirv}/EXT/SPVEXTlongvector.html[SPVEXTlongvector] SPIR-V extension
// and can be used with the
// {GLSLregistry}/ext/GLSLEXTlongvector.txt[GLEXTlongvector] GLSL
// extension.
//
// New SPIR-V Capabilities:
//
//   - LongVectorEXT
//
// Issues:
//
// Version History:
//
//   - Revision 1, 2025-06-24 (Jeff Bolz)
//   - Initial revisions
package ext_shader_long_vector
