// Code generated by vk-gen. DO NOT EDIT.

// Package ext_metal_objects provides bindings for the VK_EXT_metal_objects extension.
// Author: EXT
// Contact: Bill Hollings @billhollings
// Platform: metal
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2024-04-04
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Bill Hollings, The Brenwill Workshop Ltd.
//   - Dzmitry Malyshau, Mozilla Corp.
//
// Description:
//
// In a Vulkan implementation that is layered on top of Metal on Apple device
// platforms, this extension provides the ability to import and export the
// underlying Metal objects associated with specific Vulkan objects.
//
// As detailed in the
// https://github.com/KhronosGroup/Vulkan-Docs/tree/main/proposals/VKEXTmetal_objects.adoc[extension
// proposal document], this extension adds one new Vulkan command,
// vkExportMetalObjectsEXT, to export underlying Metal objects from
// Vulkan objects, and supports importing the appropriate existing Metal
// objects when creating Vulkan objects of types VkDeviceMemory,
// VkImage, VkSemaphore, and VkEvent,
//
// The intent is that this extension will be advertised and supported only on
// implementations that are layered on top of Metal on Apple device platforms.
//
// Issues:
//
// None.
//
// Version History:
//
//   - Revision 1, 2022-05-28 (Bill Hollings)
//   - Initial draft.
//   - Incorporated feedback from review by the Vulkan Working Group.
//     Renamed many structures, moved import/export of MTLBuffer to
//     VkDeviceMemory, added export of MTLSharedEvent, added import of
//     MTLSharedEvent for VkSemaphore and VkEvent, and changed used bit mask
//     fields to individual bit fields to simplify Valid Usage rules.
//   - Revision 2, 2024-04-04 (Bill Hollings)
//   - Add an _unsafeunretained ownership qualifier to all Metal object
//     declarations, to support Automatic Reference Counting (ARC) on Apple
//     devices.
package ext_metal_objects
