// Code generated by vk-gen. DO NOT EDIT.

package nv_device_generated_commands_compute

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdUpdatePipelineIndirectBufferNV       uintptr
	pfnGetPipelineIndirectDeviceAddressNV      uintptr
	pfnGetPipelineIndirectMemoryRequirementsNV uintptr
)

// Init resolves and initializes all VK_NV_device_generated_commands_compute extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdUpdatePipelineIndirectBufferNV = vulkan.GetDeviceProcAddr(device, "vkCmdUpdatePipelineIndirectBufferNV")
	pfnGetPipelineIndirectDeviceAddressNV = vulkan.GetDeviceProcAddr(device, "vkGetPipelineIndirectDeviceAddressNV")
	pfnGetPipelineIndirectMemoryRequirementsNV = vulkan.GetDeviceProcAddr(device, "vkGetPipelineIndirectMemoryRequirementsNV")
}

// CmdUpdatePipelineIndirectBufferNV - Update the indirect compute pipeline\ (vkCmdUpdatePipelineIndirectBufferNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - pipelineBindPoint: is a VkPipelineBindPoint value specifying the type of pipeline whose metadata will be saved.
//   - pipeline: is the pipeline whose metadata will be saved.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdUpdatePipelineIndirectBufferNV.html
func CmdUpdatePipelineIndirectBufferNV(commandBuffer vulkan.CommandBuffer, pipelineBindPoint vulkan.PipelineBindPoint, pipeline vulkan.Pipeline) {
	vulkan.CallSyscall(pfnCmdUpdatePipelineIndirectBufferNV, uintptr(commandBuffer), uintptr(pipelineBindPoint), uintptr(pipeline))
}

// GetPipelineIndirectDeviceAddressNV - Get pipeline\ (vkGetPipelineIndirectDeviceAddressNV).
// Parameters:
//   - device: is the logical device on which the pipeline was created.
//   - info: is a pointer to a VkPipelineIndirectDeviceAddressInfoNV structure specifying the pipeline to retrieve the address for.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPipelineIndirectDeviceAddressNV.html
func GetPipelineIndirectDeviceAddressNV(device vulkan.Device, info *vulkan.PipelineIndirectDeviceAddressInfoNV) (result vulkan.DeviceAddress) {
	c_info := info.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetPipelineIndirectDeviceAddressNV, uintptr(device), uintptr(unsafe.Pointer(c_info)))
	return vulkan.DeviceAddress(r1)
}

// GetPipelineIndirectMemoryRequirementsNV - Get the memory requirements for the compute indirect pipeline (vkGetPipelineIndirectMemoryRequirementsNV).
// Parameters:
//   - device: is the logical device that owns the buffer.
//   - createInfo: is a VkComputePipelineCreateInfo structure specifying the creation parameters of the compute pipeline whose memory requirements are being queried.
//   - memoryRequirements: is a pointer to a VkMemoryRequirements2 structure in which the requested pipeline's memory requirements are returned.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPipelineIndirectMemoryRequirementsNV.html
func GetPipelineIndirectMemoryRequirementsNV(device vulkan.Device, createInfo *vulkan.ComputePipelineCreateInfo) (memoryRequirements vulkan.MemoryRequirements2) {
	c_createInfo := createInfo.Raw()
	vulkan.CallSyscall(pfnGetPipelineIndirectMemoryRequirementsNV, uintptr(device), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(&memoryRequirements)))
	return memoryRequirements
}
