// Code generated by vk-gen. DO NOT EDIT.

package khr_device_address_commands

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdBeginConditionalRendering2EXT    uintptr
	pfnCmdBeginTransformFeedback2EXT       uintptr
	pfnCmdBindIndexBuffer3KHR              uintptr
	pfnCmdBindTransformFeedbackBuffers2EXT uintptr
	pfnCmdBindVertexBuffers3KHR            uintptr
	pfnCmdCopyImageToMemoryKHR             uintptr
	pfnCmdCopyMemoryKHR                    uintptr
	pfnCmdCopyMemoryToImageKHR             uintptr
	pfnCmdCopyQueryPoolResultsToMemoryKHR  uintptr
	pfnCmdDispatchIndirect2KHR             uintptr
	pfnCmdDrawIndexedIndirect2KHR          uintptr
	pfnCmdDrawIndexedIndirectCount2KHR     uintptr
	pfnCmdDrawIndirect2KHR                 uintptr
	pfnCmdDrawIndirectByteCount2EXT        uintptr
	pfnCmdDrawIndirectCount2KHR            uintptr
	pfnCmdDrawMeshTasksIndirect2EXT        uintptr
	pfnCmdDrawMeshTasksIndirectCount2EXT   uintptr
	pfnCmdEndTransformFeedback2EXT         uintptr
	pfnCmdFillMemoryKHR                    uintptr
	pfnCmdUpdateMemoryKHR                  uintptr
	pfnCmdWriteMarkerToMemoryAMD           uintptr
	pfnCreateAccelerationStructure2KHR     uintptr
)

// Init resolves and initializes all VK_KHR_device_address_commands extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdBeginConditionalRendering2EXT = vulkan.GetDeviceProcAddr(device, "vkCmdBeginConditionalRendering2EXT")
	pfnCmdBeginTransformFeedback2EXT = vulkan.GetDeviceProcAddr(device, "vkCmdBeginTransformFeedback2EXT")
	pfnCmdBindIndexBuffer3KHR = vulkan.GetDeviceProcAddr(device, "vkCmdBindIndexBuffer3KHR")
	pfnCmdBindTransformFeedbackBuffers2EXT = vulkan.GetDeviceProcAddr(device, "vkCmdBindTransformFeedbackBuffers2EXT")
	pfnCmdBindVertexBuffers3KHR = vulkan.GetDeviceProcAddr(device, "vkCmdBindVertexBuffers3KHR")
	pfnCmdCopyImageToMemoryKHR = vulkan.GetDeviceProcAddr(device, "vkCmdCopyImageToMemoryKHR")
	pfnCmdCopyMemoryKHR = vulkan.GetDeviceProcAddr(device, "vkCmdCopyMemoryKHR")
	pfnCmdCopyMemoryToImageKHR = vulkan.GetDeviceProcAddr(device, "vkCmdCopyMemoryToImageKHR")
	pfnCmdCopyQueryPoolResultsToMemoryKHR = vulkan.GetDeviceProcAddr(device, "vkCmdCopyQueryPoolResultsToMemoryKHR")
	pfnCmdDispatchIndirect2KHR = vulkan.GetDeviceProcAddr(device, "vkCmdDispatchIndirect2KHR")
	pfnCmdDrawIndexedIndirect2KHR = vulkan.GetDeviceProcAddr(device, "vkCmdDrawIndexedIndirect2KHR")
	pfnCmdDrawIndexedIndirectCount2KHR = vulkan.GetDeviceProcAddr(device, "vkCmdDrawIndexedIndirectCount2KHR")
	pfnCmdDrawIndirect2KHR = vulkan.GetDeviceProcAddr(device, "vkCmdDrawIndirect2KHR")
	pfnCmdDrawIndirectByteCount2EXT = vulkan.GetDeviceProcAddr(device, "vkCmdDrawIndirectByteCount2EXT")
	pfnCmdDrawIndirectCount2KHR = vulkan.GetDeviceProcAddr(device, "vkCmdDrawIndirectCount2KHR")
	pfnCmdDrawMeshTasksIndirect2EXT = vulkan.GetDeviceProcAddr(device, "vkCmdDrawMeshTasksIndirect2EXT")
	pfnCmdDrawMeshTasksIndirectCount2EXT = vulkan.GetDeviceProcAddr(device, "vkCmdDrawMeshTasksIndirectCount2EXT")
	pfnCmdEndTransformFeedback2EXT = vulkan.GetDeviceProcAddr(device, "vkCmdEndTransformFeedback2EXT")
	pfnCmdFillMemoryKHR = vulkan.GetDeviceProcAddr(device, "vkCmdFillMemoryKHR")
	pfnCmdUpdateMemoryKHR = vulkan.GetDeviceProcAddr(device, "vkCmdUpdateMemoryKHR")
	pfnCmdWriteMarkerToMemoryAMD = vulkan.GetDeviceProcAddr(device, "vkCmdWriteMarkerToMemoryAMD")
	pfnCreateAccelerationStructure2KHR = vulkan.GetDeviceProcAddr(device, "vkCreateAccelerationStructure2KHR")
}

// CmdBeginConditionalRendering2EXT - Define the beginning of a conditional rendering block (vkCmdBeginConditionalRendering2EXT).
// Parameters:
//   - commandBuffer: is the command buffer into which this command will be recorded.
//   - conditionalRenderingBegin: is a pointer to a VkConditionalRenderingBeginInfo2EXT structure specifying parameters of conditional rendering.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginConditionalRendering2EXT.html
func CmdBeginConditionalRendering2EXT(commandBuffer vulkan.CommandBuffer, conditionalRenderingBegin *vulkan.ConditionalRenderingBeginInfo2EXT) {
	c_conditionalRenderingBegin := conditionalRenderingBegin.Raw()
	vulkan.CallSyscall(pfnCmdBeginConditionalRendering2EXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_conditionalRenderingBegin)))
}

// CmdBeginTransformFeedback2EXT - Make transform feedback active in the command buffer (vkCmdBeginTransformFeedback2EXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - firstCounterRange: is the index of the first transform feedback buffer corresponding to pCounterInfos[0].
//   - counterRangeCount: is the size of the pCounterRanges array.
//   - counterInfos: is NULL or a pointer to an array of VkBindTransformFeedbackBuffer2InfoEXT structures defining memory ranges containing counters used to resume transform feedback from a previous location.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginTransformFeedback2EXT.html
func CmdBeginTransformFeedback2EXT(commandBuffer vulkan.CommandBuffer, firstCounterRange uint32, counterInfos []vulkan.BindTransformFeedbackBuffer2InfoEXT) {
	c_counterInfos := make([]vulkan.RawBindTransformFeedbackBuffer2InfoEXT, len(counterInfos))
	for i := range counterInfos {
		if raw := counterInfos[i].Raw(); raw != nil {
			c_counterInfos[i] = *raw
		}
	}
	vulkan.CallSyscall(pfnCmdBeginTransformFeedback2EXT, uintptr(commandBuffer), uintptr(firstCounterRange), uintptr(len(counterInfos)), uintptr(unsafe.Pointer(vulkan.SliceData(c_counterInfos))))
}

// CmdBindIndexBuffer3KHR - Bind an address range as an index buffer to a command buffer (vkCmdBindIndexBuffer3KHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkBindIndexBuffer3InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBindIndexBuffer3KHR.html
func CmdBindIndexBuffer3KHR(commandBuffer vulkan.CommandBuffer, info *vulkan.BindIndexBuffer3InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdBindIndexBuffer3KHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdBindTransformFeedbackBuffers2EXT - Bind transform feedback memory ranges to a command buffer (vkCmdBindTransformFeedbackBuffers2EXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - firstBinding: is the index of the first transform feedback binding whose state is updated by the command.
//   - bindingCount: is the number of transform feedback bindings whose state is updated by the command.
//   - bindingInfos: is a pointer to an array of VkBindTransformFeedbackBuffer2InfoEXT structures specifying the ranges of memory to be used to capture transform feedback data.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBindTransformFeedbackBuffers2EXT.html
func CmdBindTransformFeedbackBuffers2EXT(commandBuffer vulkan.CommandBuffer, firstBinding uint32, bindingInfos []vulkan.BindTransformFeedbackBuffer2InfoEXT) {
	c_bindingInfos := make([]vulkan.RawBindTransformFeedbackBuffer2InfoEXT, len(bindingInfos))
	for i := range bindingInfos {
		if raw := bindingInfos[i].Raw(); raw != nil {
			c_bindingInfos[i] = *raw
		}
	}
	vulkan.CallSyscall(pfnCmdBindTransformFeedbackBuffers2EXT, uintptr(commandBuffer), uintptr(firstBinding), uintptr(len(bindingInfos)), uintptr(unsafe.Pointer(vulkan.SliceData(c_bindingInfos))))
}

// CmdBindVertexBuffers3KHR - Bind strided address ranges as vertex buffers to a command buffer and dynamically set strides (vkCmdBindVertexBuffers3KHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - firstBinding: is the index of the first vertex input binding whose state is updated by the command.
//   - bindingCount: is the number of vertex input bindings whose state is updated by the command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBindVertexBuffers3KHR.html
func CmdBindVertexBuffers3KHR(commandBuffer vulkan.CommandBuffer, firstBinding uint32, bindingInfos []vulkan.BindVertexBuffer3InfoKHR) {
	c_bindingInfos := make([]vulkan.RawBindVertexBuffer3InfoKHR, len(bindingInfos))
	for i := range bindingInfos {
		if raw := bindingInfos[i].Raw(); raw != nil {
			c_bindingInfos[i] = *raw
		}
	}
	vulkan.CallSyscall(pfnCmdBindVertexBuffers3KHR, uintptr(commandBuffer), uintptr(firstBinding), uintptr(len(bindingInfos)), uintptr(unsafe.Pointer(vulkan.SliceData(c_bindingInfos))))
}

// CmdCopyImageToMemoryKHR - Copy data from an image to memory ranges (vkCmdCopyImageToMemoryKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - copyMemoryInfo: a pointer to a VkCopyDeviceMemoryImageInfoKHR structure describing the copies to perform.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyImageToMemoryKHR.html
func CmdCopyImageToMemoryKHR(commandBuffer vulkan.CommandBuffer, copyMemoryInfo *vulkan.CopyDeviceMemoryImageInfoKHR) {
	c_copyMemoryInfo := copyMemoryInfo.Raw()
	vulkan.CallSyscall(pfnCmdCopyImageToMemoryKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_copyMemoryInfo)))
}

// CmdCopyMemoryKHR - Copy data between memory ranges (vkCmdCopyMemoryKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - copyMemoryInfo: a pointer to a VkCopyDeviceMemoryInfoKHR structure describing the copies to perform.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyMemoryKHR.html
func CmdCopyMemoryKHR(commandBuffer vulkan.CommandBuffer, copyMemoryInfo *vulkan.CopyDeviceMemoryInfoKHR) {
	c_copyMemoryInfo := copyMemoryInfo.Raw()
	vulkan.CallSyscall(pfnCmdCopyMemoryKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_copyMemoryInfo)))
}

// CmdCopyMemoryToImageKHR - Copy data from memory ranges to an image (vkCmdCopyMemoryToImageKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - copyMemoryInfo: a pointer to a VkCopyDeviceMemoryImageInfoKHR structure describing the copies to perform.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyMemoryToImageKHR.html
func CmdCopyMemoryToImageKHR(commandBuffer vulkan.CommandBuffer, copyMemoryInfo *vulkan.CopyDeviceMemoryImageInfoKHR) {
	c_copyMemoryInfo := copyMemoryInfo.Raw()
	vulkan.CallSyscall(pfnCmdCopyMemoryToImageKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_copyMemoryInfo)))
}

// CmdCopyQueryPoolResultsToMemoryKHR - Copy the results of queries in a query pool to a memory range (vkCmdCopyQueryPoolResultsToMemoryKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which this command will be recorded.
//   - queryPool: is the query pool managing the queries containing the desired results.
//   - firstQuery: is the initial query index.
//   - queryCount: is the number of queries. firstQuery and queryCount together define a range of queries.
//   - dstRange: is a pointer to a VkStridedDeviceAddressRangeKHR describing a range of memory addressed with a stride that will receive the results of the copy command.
//   - dstFlags: is a VkAddressCommandFlagsKHR value defining the flags for the destination address range.
//   - queryResultFlags: is a bitmask of VkQueryResultFlagBits specifying how and when results are returned.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyQueryPoolResultsToMemoryKHR.html
func CmdCopyQueryPoolResultsToMemoryKHR(commandBuffer vulkan.CommandBuffer, queryPool vulkan.QueryPool, firstQuery uint32, queryCount uint32, dstRange *vulkan.StridedDeviceAddressRangeKHR, dstFlags vulkan.AddressCommandFlagsKHR, queryResultFlags vulkan.QueryResultFlags) {
	c_dstRange := dstRange.Raw()
	vulkan.CallSyscall(pfnCmdCopyQueryPoolResultsToMemoryKHR, uintptr(commandBuffer), uintptr(queryPool), uintptr(firstQuery), uintptr(queryCount), uintptr(unsafe.Pointer(c_dstRange)), uintptr(dstFlags), uintptr(queryResultFlags))
}

// CmdDispatchIndirect2KHR - Dispatch compute work items with indirect parameters through an address range (vkCmdDispatchIndirect2KHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkDispatchIndirect2InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDispatchIndirect2KHR.html
func CmdDispatchIndirect2KHR(commandBuffer vulkan.CommandBuffer, info *vulkan.DispatchIndirect2InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdDispatchIndirect2KHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdDrawIndexedIndirect2KHR - Draw primitives with indirect parameters through an address range and with indexed vertices (vkCmdDrawIndexedIndirect2KHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkDrawIndirect2InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndexedIndirect2KHR.html
func CmdDrawIndexedIndirect2KHR(commandBuffer vulkan.CommandBuffer, info *vulkan.DrawIndirect2InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdDrawIndexedIndirect2KHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdDrawIndexedIndirectCount2KHR - Draw primitives with indirect parameters and draw count through address ranges and with indexed vertices (vkCmdDrawIndexedIndirectCount2KHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkDrawIndirectCount2InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndexedIndirectCount2KHR.html
func CmdDrawIndexedIndirectCount2KHR(commandBuffer vulkan.CommandBuffer, info *vulkan.DrawIndirectCount2InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdDrawIndexedIndirectCount2KHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdDrawIndirect2KHR - Draw primitives with indirect parameters through an address range (vkCmdDrawIndirect2KHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkDrawIndirect2InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndirect2KHR.html
func CmdDrawIndirect2KHR(commandBuffer vulkan.CommandBuffer, info *vulkan.DrawIndirect2InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdDrawIndirect2KHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdDrawIndirectByteCount2EXT - Draw primitives with indirect parameters where the vertex count is derived from the counter byte value in the counter memory range (vkCmdDrawIndirectByteCount2EXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - instanceCount: is the number of instances to draw.
//   - firstInstance: is the instance ID of the first instance to draw.
//   - counterInfo: is a pointer to a VkBindTransformFeedbackBuffer2InfoEXT defining the range of memory that the byte count is read from.
//   - counterOffset: is subtracted from the byte count.
//   - vertexStride: is the stride in bytes between each element of the vertex data that is used to calculate the vertex count from the counter value. This value is typically the same value that was used in the graphics pipeline state when the transform feedback was captured as the XfbStride.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndirectByteCount2EXT.html
func CmdDrawIndirectByteCount2EXT(commandBuffer vulkan.CommandBuffer, instanceCount uint32, firstInstance uint32, counterInfo *vulkan.BindTransformFeedbackBuffer2InfoEXT, counterOffset uint32, vertexStride uint32) {
	c_counterInfo := counterInfo.Raw()
	vulkan.CallSyscall(pfnCmdDrawIndirectByteCount2EXT, uintptr(commandBuffer), uintptr(instanceCount), uintptr(firstInstance), uintptr(unsafe.Pointer(c_counterInfo)), uintptr(counterOffset), uintptr(vertexStride))
}

// CmdDrawIndirectCount2KHR - Draw primitives with indirect parameters and draw count through address ranges (vkCmdDrawIndirectCount2KHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkDrawIndirectCount2InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndirectCount2KHR.html
func CmdDrawIndirectCount2KHR(commandBuffer vulkan.CommandBuffer, info *vulkan.DrawIndirectCount2InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdDrawIndirectCount2KHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdDrawMeshTasksIndirect2EXT - Issue a mesh tasks draw with indirect parameters through an address range (vkCmdDrawMeshTasksIndirect2EXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkDrawIndirect2InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawMeshTasksIndirect2EXT.html
func CmdDrawMeshTasksIndirect2EXT(commandBuffer vulkan.CommandBuffer, info *vulkan.DrawIndirect2InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdDrawMeshTasksIndirect2EXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdDrawMeshTasksIndirectCount2EXT - Perform an indirect mesh tasks draw with the draw count sourced from an address range (vkCmdDrawMeshTasksIndirectCount2EXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - info: is a pointer to a VkDrawIndirectCount2InfoKHR structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawMeshTasksIndirectCount2EXT.html
func CmdDrawMeshTasksIndirectCount2EXT(commandBuffer vulkan.CommandBuffer, info *vulkan.DrawIndirectCount2InfoKHR) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdDrawMeshTasksIndirectCount2EXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CmdEndTransformFeedback2EXT - Make transform feedback inactive in the command buffer (vkCmdEndTransformFeedback2EXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - counterRangeCount: is the size of the pCounterInfos array.
//   - counterInfos: is NULL or a pointer to an array of VkBindTransformFeedbackBuffer2InfoEXT structures defining memory ranges used to write counters used to later resume transform feedback.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdEndTransformFeedback2EXT.html
func CmdEndTransformFeedback2EXT(commandBuffer vulkan.CommandBuffer, firstCounterRange uint32, counterInfos []vulkan.BindTransformFeedbackBuffer2InfoEXT) {
	c_counterInfos := make([]vulkan.RawBindTransformFeedbackBuffer2InfoEXT, len(counterInfos))
	for i := range counterInfos {
		if raw := counterInfos[i].Raw(); raw != nil {
			c_counterInfos[i] = *raw
		}
	}
	vulkan.CallSyscall(pfnCmdEndTransformFeedback2EXT, uintptr(commandBuffer), uintptr(firstCounterRange), uintptr(len(counterInfos)), uintptr(unsafe.Pointer(vulkan.SliceData(c_counterInfos))))
}

// CmdFillMemoryKHR - Fill a memory range with a fixed 4-byte bit pattern (vkCmdFillMemoryKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - dstRange: is a pointer to the VkDeviceAddressRangeKHR selecting the memory range to be filled.
//   - dstFlags: is a VkAddressCommandFlagsKHR value defining the copy flags for the destination address range.
//   - data: is the 4-byte word written repeatedly to the destination range to fill size bytes of data.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdFillMemoryKHR.html
func CmdFillMemoryKHR(commandBuffer vulkan.CommandBuffer, dstRange *vulkan.DeviceAddressRangeKHR, dstFlags vulkan.AddressCommandFlagsKHR, data uint32) {
	c_dstRange := dstRange.Raw()
	vulkan.CallSyscall(pfnCmdFillMemoryKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_dstRange)), uintptr(dstFlags), uintptr(data))
}

// CmdUpdateMemoryKHR - Update the content of device memory from host memory (vkCmdUpdateMemoryKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - dstRange: is a pointer to the VkDeviceAddressRangeKHR selecting the memory range to be updated.
//   - dstFlags: is a VkAddressCommandFlagsKHR value defining the copy flags for the destination address range.
//   - dataSize: is the number of bytes to update, and must be a multiple of 4.
//   - data: is a pointer to the source data for the buffer update, and must be at least dataSize bytes in size.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdUpdateMemoryKHR.html
func CmdUpdateMemoryKHR(commandBuffer vulkan.CommandBuffer, dstRange *vulkan.DeviceAddressRangeKHR, dstFlags vulkan.AddressCommandFlagsKHR, data []unsafe.Pointer) {
	c_dstRange := dstRange.Raw()
	c_data := vulkan.SliceData(data)
	vulkan.CallSyscall(pfnCmdUpdateMemoryKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_dstRange)), uintptr(dstFlags), uintptr(len(data)), uintptr(unsafe.Pointer(c_data)))
}

// CmdWriteMarkerToMemoryAMD - Execute a pipelined write of a marker value into a memory range (vkCmdWriteMarkerToMemoryAMD).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - info: specifies a pointer to an VkMemoryMarkerInfoAMD structure defining parameters of this command.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdWriteMarkerToMemoryAMD.html
func CmdWriteMarkerToMemoryAMD(commandBuffer vulkan.CommandBuffer, info *vulkan.MemoryMarkerInfoAMD) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnCmdWriteMarkerToMemoryAMD, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_info)))
}

// CreateAccelerationStructure2KHR - Create a new acceleration structure object using a device address (vkCreateAccelerationStructure2KHR).
// Parameters:
//   - device: is the logical device that creates the acceleration structure object.
//   - createInfo: is a pointer to a VkAccelerationStructureCreateInfo2KHR structure containing parameters affecting creation of the acceleration structure.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//   - accelerationStructure: is a pointer to a VkAccelerationStructureKHR handle in which the resulting acceleration structure object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR, VK_ERROR_VALIDATION_FAILED, VK_ERROR_UNKNOWN
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateAccelerationStructure2KHR.html
func CreateAccelerationStructure2KHR(device vulkan.Device, createInfo *vulkan.AccelerationStructureCreateInfo2KHR, allocator *vulkan.AllocationCallbacks) (accelerationStructure vulkan.AccelerationStructureKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateAccelerationStructure2KHR, uintptr(device), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&accelerationStructure)))
	return accelerationStructure, vulkan.Result(r1)
}
