// Code generated by vk-gen. DO NOT EDIT.

// Package khr_device_address_commands provides bindings for the VK_KHR_device_address_commands extension.
// Author: KHR
// Contact: Tobias Hector @tobski
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2026-03-10
//
// Contributors:
//   - Tobias Hector, AMD
//   - Matthew Netsch, Qualcomm Technologies, Inc
//   - Jan-Harald Fredriksen, Arm
//   - Mike Blumenkrantz, Valve
//   - Allan MacKinnon, Google
//   - Daniel Koch, NVIDIA
//   - Autumn Ashton, Valve
//   - Piers Daniell, NVIDIA
//   - Stuart Smith, AMD
//   - Caterina Shablia, Collabora
//   - Piotr Byszewski, Cognizant
//   - James Fitzpatrick, Imagination
//   - Daniel Story, Nintendo
//   - Baldur Karlsson, Valve
//   - Jon Leech, Khronos
//   - Samuel Pitoiset, Valve
//   - Lionel Landwerlin, Intel
//   - Hans-Kristian Arntzen, Valve
//   - Žiga Markuš, LunarG
//   - Spencer Fricke, Lunarg
//   - Per Inge Mathisen, Arm
//   - Vikram Kushwaha, NVIDIA
//   - Ralph Potter, Samsung
//   - Marijn Suijten, Traverse Research
//   - Ricard Garcia, Igalia
//   - Mengyang Liu, AMD
//   - Artem Kharytoniuk, LunarG
//   - Marty Johnson, Khronos
//   - Alyssa Rosenzweig, Valve
//
// Description:
//
// This extension enables applications to use device addresses in place of
// buffer objects for most functionality.
//
// Version History:
//
//   - Revision 1, 2026-03-10 (Tobias Hector)
//   - Initial revision
package khr_device_address_commands
