// Code generated by vk-gen. DO NOT EDIT.

// Package nv_partitioned_acceleration_structure provides bindings for the VK_NV_partitioned_acceleration_structure extension.
// Author: NV
// Contact: Vikram Kushwaha @vkushwaha
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2025-01-09
//
// Contributors:
//   - Vikram Kushwaha, NVIDIA
//   - Eric Werness, NVIDIA
//   - Christoph Kubisch, NVIDIA
//   - Jan Schmid, NVIDIA
//   - Pyarelal Knowles, NVIDIA
//
// Description:
//
// With an increase in scene complexity and expansive game worlds, the number
// of instances has surged in ray tracing over the last few years.
// The current Top Level Acceleration Structure (TLAS) API necessitates a full
// rebuild of the entire data structure even when only a few instances are
// modified.
//
// This extension introduces Partitioned Top Level Acceleration Structures
// (PTLAS) as an alternative to the existing TLAS.
// PTLAS enables the efficient reuse of previously constructed parts of the
// acceleration structure, resulting in much faster build times and supporting
// a higher number of instances.
//
// Version History:
//
//   - Revision 1, 2025-01-09 (Vikram Kushwaha)
//   - Initial draft
package nv_partitioned_acceleration_structure
