// Code generated by vk-gen. DO NOT EDIT.

package ext_acquire_xlib_display

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnAcquireXlibDisplayEXT    uintptr
	pfnGetRandROutputDisplayEXT uintptr
)

// Init resolves and initializes all VK_EXT_acquire_xlib_display extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnAcquireXlibDisplayEXT = vulkan.GetInstanceProcAddr(instance, "vkAcquireXlibDisplayEXT")
	pfnGetRandROutputDisplayEXT = vulkan.GetInstanceProcAddr(instance, "vkGetRandROutputDisplayEXT")
}

// AcquireXlibDisplayEXT - Acquire access to a VkDisplayKHR using Xlib (vkAcquireXlibDisplayEXT).
// Parameters:
//   - physicalDevice: is the physical device the display is on.
//   - dpy: is a connection to the X11 server that currently owns display.
//   - display: is the display the caller wishes to control in Vulkan.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_INITIALIZATION_FAILED, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkAcquireXlibDisplayEXT.html
func AcquireXlibDisplayEXT(physicalDevice vulkan.PhysicalDevice, display vulkan.DisplayKHR) (dpy uintptr, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnAcquireXlibDisplayEXT, uintptr(physicalDevice), uintptr(unsafe.Pointer(&dpy)), uintptr(display))
	return dpy, vulkan.Result(r1)
}

// GetRandROutputDisplayEXT - Query the VkDisplayKHR corresponding to an X11 RandR Output (vkGetRandROutputDisplayEXT).
// Parameters:
//   - physicalDevice: is the physical device to query the display handle on.
//   - dpy: is a connection to the X11 server from which rrOutput was queried.
//   - rrOutput: is an X11 RandR output ID.
//   - display: is a pointer to a VkDisplayKHR handle where the display is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetRandROutputDisplayEXT.html
func GetRandROutputDisplayEXT(physicalDevice vulkan.PhysicalDevice, dpy uintptr, rrOutput uintptr) (display vulkan.DisplayKHR, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnGetRandROutputDisplayEXT, uintptr(physicalDevice), uintptr(unsafe.Pointer(dpy)), uintptr(rrOutput), uintptr(unsafe.Pointer(&display)))
	return display, vulkan.Result(r1)
}
