// Code generated by vk-gen. DO NOT EDIT.

// Package qcom_rotated_copy_commands provides bindings for the VK_QCOM_rotated_copy_commands extension.
// Author: QCOM
// Contact: Matthew Netsch @mnetsch
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2023-12-13
//
// Interactions and External Dependencies:
//   - This extension interacts with VKKHRswapchain
//   - This extension interacts with VKKHRsurface
//
// Contributors:
//   - Jeff Leger, Qualcomm Technologies, Inc.
//   - Matthew Netsch, Qualcomm Technologies, Inc.
//
// Description:
//
// This extension extends adds an optional rotation transform to copy commands
// vkCmdBlitImage2KHR, vkCmdCopyImageToBuffer2KHR and
// vkCmdCopyBufferToImage2KHR.
// When copying between two resources, where one resource contains rotated
// content and the other does not, a rotated copy may be desired.
// This extension may be used in combination with VKQCOMrenderpasstransform
// which adds rotated render passes.
//
// This extension adds an extension structure to the commands
// vkCmdBlitImage2KHR, vkCmdCopyImageToBuffer2KHR, and
// vkCmdCopyBufferToImage2KHR
//
// Issues:
//
// 1) What is an appropriate name for the added extension structure? The style
// guide says "`Structures which extend other structures through the
// pNext chain should reflect the name of the base structure they
// extend.`", but in this case a single extension structure is used to extend
// three base structures (vkCmdBlitImage2KHR, vkCmdCopyImageToBuffer2KHR, and
// vkCmdCopyBufferToImage2KHR).
// Creating three identical structures with unique names seemed undesirable.
//
// RESOLVED:
//
// 2) Should this extension add a rotation capability to vkCmdCopyImage2KHR?
//
// RESOLVED:
// Use of rotated vkCmdBlitImage2KHR can fully address this use case.
//
// 3) Should this extension add a rotation capability to vkCmdResolveImage2KHR?
//
// RESOLVED No.
// Use of vkCmdResolveImage2KHR is very slow and extremely bandwidth intensive
// on Qualcomm's GPU architecture and use of pResolveAttachments in
// vkRenderPass is the strongly preferred approach.
// Therefore, we choose not to introduce a rotation capability to
// vkCmdResolveImage2KHR.
//
// Version History:
//
//   - Revision 1, 2020-09-19 (Jeff Leger)
//   - Revision 2, 2023-12-13 (Matthew Netsch)
//   - Relax dependency on VKKHRswapchain
package qcom_rotated_copy_commands
