// Code generated by vk-gen. DO NOT EDIT.

// Package ext_legacy_dithering provides bindings for the VK_EXT_legacy_dithering extension.
// Author: EXT
// Contact: Shahbaz Youssefi @syoussefi
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2024-02-22
//
// Contributors:
//   - Shahbaz Youssefi, Google
//   - Graeme Leese, Broadcom
//   - Jan-Harald Fredriksen, Arm
//
// Description:
//
// This extension exposes a hardware feature used by some vendors to implement
// OpenGL's dithering.
// The purpose of this extension is to support layering OpenGL over Vulkan, by
// allowing the layer to take advantage of the same hardware feature and
// provide equivalent dithering to OpenGL applications.
//
// Version History:
//
//   - Revision 1, 2022-03-31 (Shahbaz Youssefi)
//   - Internal revisions
//   - Revision 2, 2024-02-22 (Shahbaz Youssefi)
//   - Added pipeline create flag to support dynamic rendering
//
// Issues:
//
// 1) In OpenGL, the dither state can change dynamically.
// Should this extension add a pipeline state for dither?
//
// RESOLVED:
// Changing dither state is rarely, if ever, done during rendering.
// Every surveyed Android application either entirely disables dither,
// explicitly enables it, or uses the default state (which is enabled).
// Additionally, on some hardware dither can only be specified in a render pass
// granularity, so a change in dither state would necessarily need to cause a
// render pass break.
// This extension considers dynamic changes in OpenGL dither state a
// theoretical situation, and expects the layer to break the render pass in
// such a situation without any practical downsides.
package ext_legacy_dithering
