// Code generated by vk-gen. DO NOT EDIT.

package ext_shader_module_identifier

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetShaderModuleCreateInfoIdentifierEXT uintptr
	pfnGetShaderModuleIdentifierEXT           uintptr
)

// Init resolves and initializes all VK_EXT_shader_module_identifier extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetShaderModuleCreateInfoIdentifierEXT = vulkan.GetDeviceProcAddr(device, "vkGetShaderModuleCreateInfoIdentifierEXT")
	pfnGetShaderModuleIdentifierEXT = vulkan.GetDeviceProcAddr(device, "vkGetShaderModuleIdentifierEXT")
}

// GetShaderModuleCreateInfoIdentifierEXT - Query a unique identifier for a shader module create info (vkGetShaderModuleCreateInfoIdentifierEXT).
// Parameters:
//   - device: is the logical device that can create a VkShaderModule from pCreateInfo.
//   - createInfo: is a pointer to a VkShaderModuleCreateInfo structure.
//   - identifier: is a pointer to the returned VkShaderModuleIdentifierEXT.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetShaderModuleCreateInfoIdentifierEXT.html
func GetShaderModuleCreateInfoIdentifierEXT(device vulkan.Device, createInfo *vulkan.ShaderModuleCreateInfo) (identifier vulkan.ShaderModuleIdentifierEXT) {
	c_createInfo := createInfo.Raw()
	vulkan.CallSyscall(pfnGetShaderModuleCreateInfoIdentifierEXT, uintptr(device), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(&identifier)))
	return identifier
}

// GetShaderModuleIdentifierEXT - Query a unique identifier for a shader module (vkGetShaderModuleIdentifierEXT).
// Parameters:
//   - device: is the logical device that created the shader module.
//   - shaderModule: is the handle of the shader module.
//   - identifier: is a pointer to the returned VkShaderModuleIdentifierEXT.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetShaderModuleIdentifierEXT.html
func GetShaderModuleIdentifierEXT(device vulkan.Device, shaderModule vulkan.ShaderModule) (identifier vulkan.ShaderModuleIdentifierEXT) {
	vulkan.CallSyscall(pfnGetShaderModuleIdentifierEXT, uintptr(device), uintptr(shaderModule), uintptr(unsafe.Pointer(&identifier)))
	return identifier
}
