// Code generated by vk-gen. DO NOT EDIT.

package ext_custom_resolve

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Commands holds resolved procedure addresses for an instance and/or device.
type Commands struct {
	pfnCmdBeginCustomResolveEXT uintptr
}

// Default procedure addresses resolved by Init
var (
	pfnCmdBeginCustomResolveEXT uintptr
)

// Init resolves and initializes all VK_EXT_custom_resolve extension procedure addresses, setting default globals and returning a Commands instance for multi-device support.
func Init(instance vulkan.Instance, device vulkan.Device) *Commands {
	cmds := &Commands{
		pfnCmdBeginCustomResolveEXT: vulkan.GetDeviceProcAddr(device, "vkCmdBeginCustomResolveEXT"),
	}
	pfnCmdBeginCustomResolveEXT = cmds.pfnCmdBeginCustomResolveEXT
	return cmds
}

// CmdBeginCustomResolveEXT - Begins a shader resolve operation (vkCmdBeginCustomResolveEXT).
// Parameters:
//   - commandBuffer: is the command buffer in which to record the command.
//   - beginCustomResolveInfo: is an optional struct with which to extend functionality.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginCustomResolveEXT.html
func (c *Commands) CmdBeginCustomResolveEXT(commandBuffer vulkan.CommandBuffer, beginCustomResolveInfo *vulkan.BeginCustomResolveInfoEXT) {
	c_beginCustomResolveInfo := beginCustomResolveInfo.Raw()
	vulkan.CallSyscall(c.pfnCmdBeginCustomResolveEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_beginCustomResolveInfo)))
}

func CmdBeginCustomResolveEXT(commandBuffer vulkan.CommandBuffer, beginCustomResolveInfo *vulkan.BeginCustomResolveInfoEXT) {
	c_beginCustomResolveInfo := beginCustomResolveInfo.Raw()
	vulkan.CallSyscall(pfnCmdBeginCustomResolveEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_beginCustomResolveInfo)))
}
