// Code generated by vk-gen. DO NOT EDIT.

package ext_custom_resolve

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdBeginCustomResolveEXT uintptr
)

// Init resolves and initializes all VK_EXT_custom_resolve extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdBeginCustomResolveEXT = vulkan.GetDeviceProcAddr(device, "vkCmdBeginCustomResolveEXT")
}

// CmdBeginCustomResolveEXT - Begins a shader resolve operation (vkCmdBeginCustomResolveEXT).
// Parameters:
//   - commandBuffer: is the command buffer in which to record the command.
//   - beginCustomResolveInfo: is an optional struct with which to extend functionality.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginCustomResolveEXT.html
func CmdBeginCustomResolveEXT(commandBuffer vulkan.CommandBuffer, beginCustomResolveInfo *vulkan.BeginCustomResolveInfoEXT) {
	c_beginCustomResolveInfo := beginCustomResolveInfo.Raw()
	vulkan.CallSyscall(pfnCmdBeginCustomResolveEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_beginCustomResolveInfo)))
}
