// Code generated by vk-gen. DO NOT EDIT.

// Package amd_shader_ballot provides bindings for the VK_AMD_shader_ballot extension.
// Author: AMD
// Contact: Dominik Witczak @dominikwitczakamd
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2016-09-19
//
// IP Status:
//
//	No known IP claims.
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLregistry}/AMD/AMDshaderballot.txt[GLAMDshader_ballot]
//
// Contributors:
//   - Qun Lin, AMD
//   - Graham Sellers, AMD
//   - Daniel Rakos, AMD
//   - Rex Xu, AMD
//   - Dominik Witczak, AMD
//   - Matthäus G. Chajdas, AMD
//
// Description:
//
// This extension adds support for the following SPIR-V extension in Vulkan:
//
//   - {spirv}/AMD/SPVAMDshaderballot.html[SPVAMDshaderballot]
//
// Version History:
//
//   - Revision 1, 2016-09-19 (Dominik Witczak)
//   - Initial draft
package amd_shader_ballot
