// Code generated by vk-gen. DO NOT EDIT.

package ext_external_memory_host

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetMemoryHostPointerPropertiesEXT uintptr
)

// Init resolves and initializes all VK_EXT_external_memory_host extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetMemoryHostPointerPropertiesEXT = vulkan.GetDeviceProcAddr(device, "vkGetMemoryHostPointerPropertiesEXT")
}

// GetMemoryHostPointerPropertiesEXT - Get properties of external memory host pointer (vkGetMemoryHostPointerPropertiesEXT).
// Parameters:
//   - device: is the logical device that will be importing pHostPointer.
//   - handleType: is a VkExternalMemoryHandleTypeFlagBits value specifying the type of the handle pHostPointer.
//   - hostPointer: is the host pointer to import from.
//   - memoryHostPointerProperties: is a pointer to a VkMemoryHostPointerPropertiesEXT structure in which the host pointer properties are returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_INVALID_EXTERNAL_HANDLE, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetMemoryHostPointerPropertiesEXT.html
func GetMemoryHostPointerPropertiesEXT(device vulkan.Device, handleType vulkan.ExternalMemoryHandleTypeFlagBits, hostPointer unsafe.Pointer) (memoryHostPointerProperties vulkan.MemoryHostPointerPropertiesEXT, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnGetMemoryHostPointerPropertiesEXT, uintptr(device), uintptr(handleType), uintptr(unsafe.Pointer(hostPointer)), uintptr(unsafe.Pointer(&memoryHostPointerProperties)))
	return memoryHostPointerProperties, vulkan.Result(r1)
}
