// Code generated by vk-gen. DO NOT EDIT.

// Package amd_shader_info provides bindings for the VK_AMD_shader_info extension.
// Author: AMD
// Contact: Jaakko Konttinen @jaakkoamd
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2017-10-09
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Jaakko Konttinen, AMD
//
// Description:
//
// This extension adds a way to query certain information about a compiled
// shader which is part of a pipeline.
// This information may include shader disassembly, shader binary and various
// statistics about a shader's resource usage.
//
// While this extension provides a mechanism for extracting this information,
// the details regarding the contents or format of this information are not
// specified by this extension and may be provided by the vendor externally.
//
// Furthermore, all information types are optionally supported, and users
// should not assume every implementation supports querying every type of
// information.
//
// Examples:
//
// This example extracts the register usage of a fragment shader within a
// particular graphics pipeline:
//
// extern VkDevice device;
// extern VkPipeline gfxPipeline;
//
// PFNvkGetShaderInfoAMD pfnGetShaderInfoAMD = (PFNvkGetShaderInfoAMD)vkGetDeviceProcAddr(
//
//	device, "vkGetShaderInfoAMD");
//
// VkShaderStatisticsInfoAMD statistics = {};
//
// size_t dataSize = sizeof(statistics);
//
// if (pfnGetShaderInfoAMD(device,
//
//	gfxPipeline,
//	VKSHADERSTAGEFRAGMENTBIT,
//	VKSHADERINFOTYPESTATISTICS_AMD,
//	&dataSize,
//	&statistics) == VK_SUCCESS)
//
//	{
//	    printf("VGPR usage: %d\n", statistics.resourceUsage.numUsedVgprs);
//	    printf("SGPR usage: %d\n", statistics.resourceUsage.numUsedSgprs);
//	}
//
// The following example continues the previous example by subsequently
// attempting to query and print shader disassembly about the fragment shader:
//
// if (pfnGetShaderInfoAMD(device,
//
//	gfxPipeline,
//	VKSHADERSTAGEFRAGMENTBIT,
//	VKSHADERINFOTYPEDISASSEMBLY_AMD,
//	&dataSize,
//	nullptr) == VK_SUCCESS)
//
//	{
//	    printf("Fragment shader disassembly:\n");
//
//	    void* disassembly = malloc(dataSize);
//
//	    if (pfnGetShaderInfoAMD(device,
//	        gfxPipeline,
//	        VKSHADERSTAGEFRAGMENTBIT,
//	        VKSHADERINFOTYPEDISASSEMBLY_AMD,
//	        &dataSize,
//	        disassembly) == VK_SUCCESS)
//	    {
//	        printf((char*)disassembly);
//	    }
//
//	    free(disassembly);
//	}
//
// Version History:
//
//   - Revision 1, 2017-10-09 (Jaakko Konttinen)
//   - Initial revision
package amd_shader_info
