// Code generated by vk-gen. DO NOT EDIT.

package ohos_surface

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Commands holds resolved procedure addresses for an instance and/or device.
type Commands struct {
	pfnCreateSurfaceOHOS uintptr
}

// Default procedure addresses resolved by Init
var (
	pfnCreateSurfaceOHOS uintptr
)

// Init resolves and initializes all VK_OHOS_surface extension procedure addresses, setting default globals and returning a Commands instance for multi-device support.
func Init(instance vulkan.Instance, device vulkan.Device) *Commands {
	cmds := &Commands{
		pfnCreateSurfaceOHOS: vulkan.GetInstanceProcAddr(instance, "vkCreateSurfaceOHOS"),
	}
	pfnCreateSurfaceOHOS = cmds.pfnCreateSurfaceOHOS
	return cmds
}

// CreateSurfaceOHOS - Create a VkSurfaceKHR object for an Open Harmony OS native window (vkCreateSurfaceOHOS).
// Parameters:
//   - instance: is the instance to associate the surface with.
//   - createInfo: is a pointer to a VkSurfaceCreateInfoOHOS structure containing parameters affecting the creation of the surface object.
//   - allocator: is the allocator used for host memory allocated for the surface object when there is no more specific allocator available (see Memory Allocation).
//   - surface: is a pointer to a VkSurfaceKHR handle in which the created surface object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_SURFACE_LOST_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateSurfaceOHOS.html
func (c *Commands) CreateSurfaceOHOS(instance vulkan.Instance, createInfo *vulkan.SurfaceCreateInfoOHOS, allocator *vulkan.AllocationCallbacks) (surface vulkan.SurfaceKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnCreateSurfaceOHOS, uintptr(instance), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&surface)))
	return surface, vulkan.Result(r1)
}

func CreateSurfaceOHOS(instance vulkan.Instance, createInfo *vulkan.SurfaceCreateInfoOHOS, allocator *vulkan.AllocationCallbacks) (surface vulkan.SurfaceKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateSurfaceOHOS, uintptr(instance), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&surface)))
	return surface, vulkan.Result(r1)
}
