// Code generated by vk-gen. DO NOT EDIT.

package khr_swapchain_maintenance1

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnReleaseSwapchainImagesKHR uintptr
)

// Init resolves and initializes all VK_KHR_swapchain_maintenance1 extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnReleaseSwapchainImagesKHR = vulkan.GetDeviceProcAddr(device, "vkReleaseSwapchainImagesKHR")
}

// ReleaseSwapchainImagesKHR - Release previously acquired but unused images (vkReleaseSwapchainImagesKHR).
// Parameters:
//   - device: is the device associated with VkReleaseSwapchainImagesInfoKHR::pname:swapchain.
//   - releaseInfo: is a pointer to a VkReleaseSwapchainImagesInfoKHR structure containing parameters of the release.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_SURFACE_LOST_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkReleaseSwapchainImagesKHR.html
func ReleaseSwapchainImagesKHR(device vulkan.Device, releaseInfo *vulkan.ReleaseSwapchainImagesInfoKHR) (result vulkan.Result) {
	c_releaseInfo := releaseInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnReleaseSwapchainImagesKHR, uintptr(device), uintptr(unsafe.Pointer(c_releaseInfo)))
	return vulkan.Result(r1)
}
