// Code generated by vk-gen. DO NOT EDIT.

package nv_coverage_reduction_mode

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Commands holds resolved procedure addresses for an instance and/or device.
type Commands struct {
	pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV uintptr
}

// Default procedure addresses resolved by Init
var (
	pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV uintptr
)

// Init resolves and initializes all VK_NV_coverage_reduction_mode extension procedure addresses, setting default globals and returning a Commands instance for multi-device support.
func Init(instance vulkan.Instance, device vulkan.Device) *Commands {
	cmds := &Commands{
		pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV: vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV"),
	}
	pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV = cmds.pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV
	return cmds
}

// GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV - Query supported sample count combinations (vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV).
// Parameters:
//   - physicalDevice: is the physical device from which to query the set of combinations.
//   - combinationCount: is a pointer to an integer related to the number of combinations available or queried, as described below.
//   - combinations: is either NULL or a pointer to an array of VkFramebufferMixedSamplesCombinationNV values, indicating the supported combinations of coverage reduction mode, rasterization samples, and color, depth, stencil attachment sample counts.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV.html
func (c *Commands) GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV(physicalDevice vulkan.PhysicalDevice) (combinations []vulkan.FramebufferMixedSamplesCombinationNV, result vulkan.Result) {
	var count uint32
	r1, _, _ := vulkan.CallSyscall(c.pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV, uintptr(physicalDevice), uintptr(unsafe.Pointer(&count)), 0)
	if vulkan.Result(r1) != vulkan.SUCCESS || count == 0 {
		return nil, vulkan.Result(r1)
	}

	combinations = make([]vulkan.FramebufferMixedSamplesCombinationNV, count)
	call2ArgsPtr := uintptr(unsafe.Pointer(&combinations[0]))
	r1, _, _ = vulkan.CallSyscall(c.pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV, uintptr(physicalDevice), uintptr(unsafe.Pointer(&count)), call2ArgsPtr)
	return combinations, vulkan.Result(r1)
}

func GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV(physicalDevice vulkan.PhysicalDevice) (combinations []vulkan.FramebufferMixedSamplesCombinationNV, result vulkan.Result) {
	var count uint32
	r1, _, _ := vulkan.CallSyscall(pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV, uintptr(physicalDevice), uintptr(unsafe.Pointer(&count)), 0)
	if vulkan.Result(r1) != vulkan.SUCCESS || count == 0 {
		return nil, vulkan.Result(r1)
	}

	combinations = make([]vulkan.FramebufferMixedSamplesCombinationNV, count)
	call2ArgsPtr := uintptr(unsafe.Pointer(&combinations[0]))
	r1, _, _ = vulkan.CallSyscall(pfnGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV, uintptr(physicalDevice), uintptr(unsafe.Pointer(&count)), call2ArgsPtr)
	return combinations, vulkan.Result(r1)
}
