// Code generated by vk-gen. DO NOT EDIT.

// Package khr_shader_subgroup_uniform_control_flow provides bindings for the VK_KHR_shader_subgroup_uniform_control_flow extension.
// Author: KHR
// Contact: Alan Baker @alan-baker
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2020-08-27
//
// IP Status:
//
//	No known IP claims.
//
// Interactions and External Dependencies:
//   - Requires SPIR-V 1.3.
//   - This extension provides API support for
//     {GLSLregistry}/ext/GLEXTsubgroupuniformqualifier.txt[GLEXTsubgroupuniformqualifier]
//
// Contributors:
//   - Alan Baker, Google
//   - Jeff Bolz, NVIDIA
//
// Description:
//
// This extension allows the use of the SPVKHRsubgroupuniformcontrol_flow
// SPIR-V extension in shader modules.
// SPVKHRsubgroupuniformcontrol_flow provides stronger guarantees that
// diverged subgroups will reconverge.
//
// Developers should utilize this extension if they use subgroup operations to
// reduce the work performed by a uniform subgroup.
// This extension will guarantee that uniform subgroup will reconverge in the
// same manner as invocation groups (see "Uniform Control Flow" in the
// Khronos SPIR-V Specification).
//
// Version History:
//
//   - Revision 1, 2020-08-27 (Alan Baker)
//   - Internal draft version
package khr_shader_subgroup_uniform_control_flow
