// Code generated by vk-gen. DO NOT EDIT.

// Package ext_shader_float8 provides bindings for the VK_EXT_shader_float8 extension.
// Author: EXT
// Contact: Kevin Petit @kpet
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2025-04-16
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Kévin Petit, Arm Ltd.
//   - Stu Smith, AMD
//   - Jeff Bolz, NVIDIA
//   - Craig Graham, Samsung
//
// Description:
//
// This extension enables support for 8-bit floating-point data types as
// defined in SPVEXTfloat8.
//
// New SPIR-V Capabilities:
//
//   - Float8EXT
//   - Float8CooperativeMatrixEXT
//
// Issues:
//
// 1) Resolve interactions with the changes VKKHRshader_float16 makes to
// rules for denorm flushing (always allowed by default for all FP formats).
// How to describe the requirement to preserve subnormals?
// +
// RESOLVED:
// IEEE 754 binary 16.
// In all other cases, subnormals may be flushed to zero.
// +
//
// Version History:
//
//   - Revision 1, 2025-04-16 (Kévin Petit)
//   - Initial draft
package ext_shader_float8
