// Code generated by vk-gen. DO NOT EDIT.

package mvk_macos_surface

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCreateMacOSSurfaceMVK uintptr
)

// Init resolves and initializes all VK_MVK_macos_surface extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCreateMacOSSurfaceMVK = vulkan.GetInstanceProcAddr(instance, "vkCreateMacOSSurfaceMVK")
}

// CreateMacOSSurfaceMVK - Create a VkSurfaceKHR object for a macOS NSView (vkCreateMacOSSurfaceMVK).
// Parameters:
//   - instance: is the instance with which to associate the surface.
//   - createInfo: is a pointer to a VkMacOSSurfaceCreateInfoMVK structure containing parameters affecting the creation of the surface object.
//   - allocator: is the allocator used for host memory allocated for the surface object when there is no more specific allocator available (see Memory Allocation).
//   - surface: is a pointer to a VkSurfaceKHR handle in which the created surface object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_NATIVE_WINDOW_IN_USE_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateMacOSSurfaceMVK.html
func CreateMacOSSurfaceMVK(instance vulkan.Instance, createInfo *vulkan.MacOSSurfaceCreateInfoMVK, allocator *vulkan.AllocationCallbacks) (surface vulkan.SurfaceKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateMacOSSurfaceMVK, uintptr(instance), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&surface)))
	return surface, vulkan.Result(r1)
}
