// Code generated by vk-gen. DO NOT EDIT.

package ext_headless_surface

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCreateHeadlessSurfaceEXT uintptr
)

// Init resolves and initializes all VK_EXT_headless_surface extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCreateHeadlessSurfaceEXT = vulkan.GetInstanceProcAddr(instance, "vkCreateHeadlessSurfaceEXT")
}

// CreateHeadlessSurfaceEXT - Create a headless VkSurfaceKHR object (vkCreateHeadlessSurfaceEXT).
// Parameters:
//   - instance: is the instance to associate the surface with.
//   - createInfo: is a pointer to a VkHeadlessSurfaceCreateInfoEXT structure containing parameters affecting the creation of the surface object.
//   - allocator: is the allocator used for host memory allocated for the surface object when there is no more specific allocator available (see Memory Allocation).
//   - surface: is a pointer to a VkSurfaceKHR handle in which the created surface object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateHeadlessSurfaceEXT.html
func CreateHeadlessSurfaceEXT(instance vulkan.Instance, createInfo *vulkan.HeadlessSurfaceCreateInfoEXT, allocator *vulkan.AllocationCallbacks) (surface vulkan.SurfaceKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateHeadlessSurfaceEXT, uintptr(instance), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&surface)))
	return surface, vulkan.Result(r1)
}
