// Code generated by vk-gen. DO NOT EDIT.

package nv_memory_decompression

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdDecompressMemoryIndirectCountNV uintptr
	pfnCmdDecompressMemoryNV              uintptr
)

// Init resolves and initializes all VK_NV_memory_decompression extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdDecompressMemoryIndirectCountNV = vulkan.GetDeviceProcAddr(device, "vkCmdDecompressMemoryIndirectCountNV")
	pfnCmdDecompressMemoryNV = vulkan.GetDeviceProcAddr(device, "vkCmdDecompressMemoryNV")
}

// CmdDecompressMemoryIndirectCountNV - Indirect decompress data between memory regions (vkCmdDecompressMemoryIndirectCountNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - indirectCommandsAddress: is the device address containing decompression parameters laid out as an array of VkDecompressMemoryRegionNV structures.
//   - indirectCommandsCountAddress: is the device address containing a 32-bit integer value specifying the decompression count.
//   - stride: is the byte stride between successive sets of decompression parameters located starting from indirectCommandsAddress.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDecompressMemoryIndirectCountNV.html
func CmdDecompressMemoryIndirectCountNV(commandBuffer vulkan.CommandBuffer, indirectCommandsAddress vulkan.DeviceAddress, indirectCommandsCountAddress vulkan.DeviceAddress, stride uint32) {
	vulkan.CallSyscall(pfnCmdDecompressMemoryIndirectCountNV, uintptr(commandBuffer), uintptr(indirectCommandsAddress), uintptr(indirectCommandsCountAddress), uintptr(stride))
}

// CmdDecompressMemoryNV - Decompress memory containing compressed data (vkCmdDecompressMemoryNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - decompressRegionCount: is the number of memory regions to decompress.
//   - decompressMemoryRegions: is a pointer to an array of decompressRegionCount VkDecompressMemoryRegionNV structures specifying decompression parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDecompressMemoryNV.html
func CmdDecompressMemoryNV(commandBuffer vulkan.CommandBuffer, decompressMemoryRegions []vulkan.DecompressMemoryRegionNV) {
	c_decompressMemoryRegions := make([]vulkan.RawDecompressMemoryRegionNV, len(decompressMemoryRegions))
	for i := range decompressMemoryRegions {
		if raw := decompressMemoryRegions[i].Raw(); raw != nil {
			c_decompressMemoryRegions[i] = *raw
		}
	}
	vulkan.CallSyscall(pfnCmdDecompressMemoryNV, uintptr(commandBuffer), uintptr(len(decompressMemoryRegions)), uintptr(unsafe.Pointer(vulkan.SliceData(c_decompressMemoryRegions))))
}
