// Code generated by vk-gen. DO NOT EDIT.

package khr_copy_memory_indirect

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdCopyMemoryIndirectKHR        uintptr
	pfnCmdCopyMemoryToImageIndirectKHR uintptr
)

// Init resolves and initializes all VK_KHR_copy_memory_indirect extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdCopyMemoryIndirectKHR = vulkan.GetDeviceProcAddr(device, "vkCmdCopyMemoryIndirectKHR")
	pfnCmdCopyMemoryToImageIndirectKHR = vulkan.GetDeviceProcAddr(device, "vkCmdCopyMemoryToImageIndirectKHR")
}

// CmdCopyMemoryIndirectKHR - Copy data between memory regions (vkCmdCopyMemoryIndirectKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - copyMemoryIndirectInfo: is a pointer to a VkCopyMemoryIndirectInfoKHR structure containing the copy parameters, including the number of copies to execute and a strided array of VkCopyMemoryIndirectCommandKHR structures.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyMemoryIndirectKHR.html
func CmdCopyMemoryIndirectKHR(commandBuffer vulkan.CommandBuffer, copyMemoryIndirectInfo *vulkan.CopyMemoryIndirectInfoKHR) {
	c_copyMemoryIndirectInfo := copyMemoryIndirectInfo.Raw()
	vulkan.CallSyscall(pfnCmdCopyMemoryIndirectKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_copyMemoryIndirectInfo)))
}

// CmdCopyMemoryToImageIndirectKHR - Copy data from a memory region to an image object (vkCmdCopyMemoryToImageIndirectKHR).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - copyMemoryToImageIndirectInfo: is a pointer to a VkCopyMemoryToImageIndirectInfoKHR structure which contains the copy parameters, including the number of copies to execute and a strided array of VkCopyMemoryToImageIndirectCommandKHR structures.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyMemoryToImageIndirectKHR.html
func CmdCopyMemoryToImageIndirectKHR(commandBuffer vulkan.CommandBuffer, copyMemoryToImageIndirectInfo *vulkan.CopyMemoryToImageIndirectInfoKHR) {
	c_copyMemoryToImageIndirectInfo := copyMemoryToImageIndirectInfo.Raw()
	vulkan.CallSyscall(pfnCmdCopyMemoryToImageIndirectKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_copyMemoryToImageIndirectInfo)))
}
