// Code generated by vk-gen. DO NOT EDIT.

// Package nv_linear_color_attachment provides bindings for the VK_NV_linear_color_attachment extension.
// Author: NVIDIA
// Contact: sourav parmar @souravpNV
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2021-12-02
//
// Interactions and External Dependencies:
//   - This extension requires VKKHRformatfeatureflags2
//
// Contributors:
//   - Pat Brown, NVIDIA
//   - Piers Daniell, NVIDIA
//   - Sourav Parmar, NVIDIA
//
// Description:
//
// This extension expands support for using VKIMAGETILING_LINEAR images
// as color attachments when all the color attachments in the render pass
// instance have VKIMAGETILING_LINEAR tiling.
// This extension adds a new flag bit
// VKFORMATFEATURE2LINEARCOLORATTACHMENTBITNV that extends the
// existing VkFormatFeatureFlagBits2KHR bits.
// This flag can: be set for renderable color formats in the
// VkFormatProperties3KHR::pname:linearTilingFeatures format properties
// structure member.
// Formats with the VKFORMATFEATURE2LINEARCOLORATTACHMENTBITNV
// flag may: be used as color attachments as long as all the color attachments
// in the render pass instance have VKIMAGETILING_LINEAR tiling, and
// the formats their images views are created with have
// VkFormatProperties3KHR::pname:linearTilingFeatures which include
// VKFORMATFEATURE2LINEARCOLORATTACHMENTBITNV.
// This extension supports both dynamic rendering and traditional render
// passes.
//
// Version History:
//
//   - Revision 1, 2021-11-29 (sourav parmar)
//   - Initial draft
package nv_linear_color_attachment
