// Code generated by vk-gen. DO NOT EDIT.

package ext_present_timing

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetPastPresentationTimingEXT          uintptr
	pfnGetSwapchainTimeDomainPropertiesEXT   uintptr
	pfnGetSwapchainTimingPropertiesEXT       uintptr
	pfnSetSwapchainPresentTimingQueueSizeEXT uintptr
)

// Init resolves and initializes all VK_EXT_present_timing extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetPastPresentationTimingEXT = vulkan.GetDeviceProcAddr(device, "vkGetPastPresentationTimingEXT")
	pfnGetSwapchainTimeDomainPropertiesEXT = vulkan.GetDeviceProcAddr(device, "vkGetSwapchainTimeDomainPropertiesEXT")
	pfnGetSwapchainTimingPropertiesEXT = vulkan.GetDeviceProcAddr(device, "vkGetSwapchainTimingPropertiesEXT")
	pfnSetSwapchainPresentTimingQueueSizeEXT = vulkan.GetDeviceProcAddr(device, "vkSetSwapchainPresentTimingQueueSizeEXT")
}

// GetPastPresentationTimingEXT - Obtain timing of previously-presented images (vkGetPastPresentationTimingEXT).
// Parameters:
//   - device: is the device associated with swapchain.
//   - pastPresentationTimingInfo: is a pointer to an instance of the VkPastPresentationTimingInfoEXT structure.
//   - pastPresentationTimingProperties: is a pointer to an instance of the VkPastPresentationTimingPropertiesEXT structure.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_DEVICE_LOST, VK_ERROR_OUT_OF_DATE_KHR, VK_ERROR_SURFACE_LOST_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPastPresentationTimingEXT.html
func GetPastPresentationTimingEXT(device vulkan.Device, pastPresentationTimingInfo *vulkan.PastPresentationTimingInfoEXT) (pastPresentationTimingProperties vulkan.PastPresentationTimingPropertiesEXT, result vulkan.Result) {
	c_pastPresentationTimingInfo := pastPresentationTimingInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetPastPresentationTimingEXT, uintptr(device), uintptr(unsafe.Pointer(c_pastPresentationTimingInfo)), uintptr(unsafe.Pointer(&pastPresentationTimingProperties)))
	return pastPresentationTimingProperties, vulkan.Result(r1)
}

// GetSwapchainTimeDomainPropertiesEXT - Obtain the time domains supported by the PE for the swapchain (vkGetSwapchainTimeDomainPropertiesEXT).
// Parameters:
//   - device: is the device associated with swapchain.
//   - swapchain: is the swapchain to obtain time domain properties for.
//   - swapchainTimeDomainProperties: is a pointer to an instance of the VkSwapchainTimeDomainPropertiesEXT structure.
//   - timeDomainsCounter: is NULL or a pointer to a 64-bit unsigned integer set by the implementation to the current value of the swapchain's internal time domain properties counter.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_SURFACE_LOST_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetSwapchainTimeDomainPropertiesEXT.html
func GetSwapchainTimeDomainPropertiesEXT(device vulkan.Device, swapchain vulkan.SwapchainKHR, swapchainTimeDomainProperties *vulkan.SwapchainTimeDomainPropertiesEXT) (timeDomainsCounter uint64, result vulkan.Result) {
	c_swapchainTimeDomainProperties := swapchainTimeDomainProperties.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetSwapchainTimeDomainPropertiesEXT, uintptr(device), uintptr(swapchain), uintptr(unsafe.Pointer(c_swapchainTimeDomainProperties)), uintptr(unsafe.Pointer(&timeDomainsCounter)))
	return timeDomainsCounter, vulkan.Result(r1)
}

// GetSwapchainTimingPropertiesEXT - Obtain the display timing properties of the PE\ (vkGetSwapchainTimingPropertiesEXT).
// Parameters:
//   - device: is the device associated with swapchain.
//   - swapchain: is the swapchain to obtain timing properties for.
//   - swapchainTimingProperties: is a pointer to an instance of the VkSwapchainTimingPropertiesEXT structure.
//   - swapchainTimingPropertiesCounter: is NULL or a pointer to a 64-bit unsigned integer set by the implementation to the current value of the swapchain's internal timing properties counter.
//
// Success codes: VK_SUCCESS, VK_NOT_READY
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_SURFACE_LOST_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetSwapchainTimingPropertiesEXT.html
func GetSwapchainTimingPropertiesEXT(device vulkan.Device, swapchain vulkan.SwapchainKHR, swapchainTimingProperties *vulkan.SwapchainTimingPropertiesEXT) (swapchainTimingPropertiesCounter uint64, result vulkan.Result) {
	c_swapchainTimingProperties := swapchainTimingProperties.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetSwapchainTimingPropertiesEXT, uintptr(device), uintptr(swapchain), uintptr(unsafe.Pointer(c_swapchainTimingProperties)), uintptr(unsafe.Pointer(&swapchainTimingPropertiesCounter)))
	return swapchainTimingPropertiesCounter, vulkan.Result(r1)
}

// SetSwapchainPresentTimingQueueSizeEXT - Allocate memory for the swapchain-internal timing results queue (vkSetSwapchainPresentTimingQueueSizeEXT).
// Parameters:
//   - device: is the device associated with swapchain.
//   - swapchain: is the swapchain to allocate a results queue for.
//   - size: is the requested number of slots in the internal results queue.
//
// Success codes: VK_SUCCESS, VK_NOT_READY
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkSetSwapchainPresentTimingQueueSizeEXT.html
func SetSwapchainPresentTimingQueueSizeEXT(device vulkan.Device, swapchain vulkan.SwapchainKHR, size uint32) (result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnSetSwapchainPresentTimingQueueSizeEXT, uintptr(device), uintptr(swapchain), uintptr(size))
	return vulkan.Result(r1)
}
