// Code generated by vk-gen. DO NOT EDIT.

// Package amdx_shader_enqueue provides bindings for the VK_AMDX_shader_enqueue extension.
// Author: AMD
// Contact: Tobias Hector @tobski
// Platform: provisional
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2024-07-17
//
// Provisional:
//
// *This extension is provisional and should: not be used in production
// applications.
// The functionality may: change in ways that break backwards compatibility
// between revisions, and before final release.*
//
// Contributors:
//   - Tobias Hector, AMD
//   - Matthaeus Chajdas, AMD
//   - Maciej Jesionowski, AMD
//   - Robert Martin, AMD
//   - Qun Lin, AMD
//   - Rex Xu, AMD
//   - Dominik Witczak, AMD
//   - Karthik Srinivasan, AMD
//   - Nicolai Haehnle, AMD
//   - Stuart Smith, AMD
//
// Description:
//
// This extension adds the ability for developers to enqueue mesh and compute
// shader workgroups from other compute shaders.
//
// Version History:
//
//   - Revision 2, 2024-07-17 (Tobias Hector)
//   - Add mesh nodes
//   - Revision 1, 2021-07-22 (Tobias Hector)
//   - Initial revision
package amdx_shader_enqueue
