// Code generated by vk-gen. DO NOT EDIT.

package ext_device_fault

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Commands holds resolved procedure addresses for an instance and/or device.
type Commands struct {
	pfnGetDeviceFaultInfoEXT uintptr
}

// Default procedure addresses resolved by Init
var (
	pfnGetDeviceFaultInfoEXT uintptr
)

// Init resolves and initializes all VK_EXT_device_fault extension procedure addresses, setting default globals and returning a Commands instance for multi-device support.
func Init(instance vulkan.Instance, device vulkan.Device) *Commands {
	cmds := &Commands{
		pfnGetDeviceFaultInfoEXT: vulkan.GetDeviceProcAddr(device, "vkGetDeviceFaultInfoEXT"),
	}
	pfnGetDeviceFaultInfoEXT = cmds.pfnGetDeviceFaultInfoEXT
	return cmds
}

// GetDeviceFaultInfoEXT - Reports fault information for the specified device (vkGetDeviceFaultInfoEXT).
// Parameters:
//   - device: is the logical device from which to query the diagnostic fault information.
//   - faultCounts: is a pointer to a VkDeviceFaultCountsEXT structure in which counts for structures describing additional fault information are returned.
//   - faultInfo: is NULL or a pointer to a VkDeviceFaultInfoEXT structure in which fault information is returned.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetDeviceFaultInfoEXT.html
func (c *Commands) GetDeviceFaultInfoEXT(device vulkan.Device, faultCounts *vulkan.DeviceFaultCountsEXT) (faultInfo vulkan.DeviceFaultInfoEXT, result vulkan.Result) {
	c_faultCounts := faultCounts.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnGetDeviceFaultInfoEXT, uintptr(device), uintptr(unsafe.Pointer(c_faultCounts)), uintptr(unsafe.Pointer(&faultInfo)))
	return faultInfo, vulkan.Result(r1)
}

func GetDeviceFaultInfoEXT(device vulkan.Device, faultCounts *vulkan.DeviceFaultCountsEXT) (faultInfo vulkan.DeviceFaultInfoEXT, result vulkan.Result) {
	c_faultCounts := faultCounts.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetDeviceFaultInfoEXT, uintptr(device), uintptr(unsafe.Pointer(c_faultCounts)), uintptr(unsafe.Pointer(&faultInfo)))
	return faultInfo, vulkan.Result(r1)
}
