// Code generated by vk-gen. DO NOT EDIT.

// Package ext_graphics_pipeline_library provides bindings for the VK_EXT_graphics_pipeline_library extension.
// Author: AMD
// Contact: Tobias Hector @tobski
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2021-08-17
//
// Contributors:
//   - Tobias Hector, AMD
//   - Chris Glover, Google
//   - Jeff Leger, Qualcomm
//   - Jan-Harald Fredriksen, Arm
//   - Piers Daniell, NVidia
//   - Boris Zanin, Mobica
//   - Krzysztof Niski, NVidia
//   - Dan Ginsburg, Valve
//   - Sebastian Aaltonen, Unity
//   - Arseny Kapoulkine, Roblox
//   - Calle Lejdfors, Ubisoft
//   - Tiago Rodrigues, Ubisoft
//   - Francois Duranleau, Gameloft
//
// Description:
//
// This extension allows the separate compilation of four distinct parts of
// graphics pipelines, with the intent of allowing faster pipeline loading for
// applications reusing the same shaders or state in multiple pipelines.
// Each part can be independently compiled into a graphics pipeline library,
// with a final link step required to create an executable pipeline that can be
// bound to a command buffer.
//
// Version History:
//
//   - Revision 1, 2021-08-17 (Tobias Hector)
//   - Initial draft.
package ext_graphics_pipeline_library
