// Code generated by vk-gen. DO NOT EDIT.

// Package google_hlsl_functionality1 provides bindings for the VK_GOOGLE_hlsl_functionality1 extension.
// Author: GOOGLE
// Contact: Hai Nguyen @chaoticbob
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2018-07-09
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Hai Nguyen, Google
//   - Neil Henning, AMD
//
// Description:
//
// The VKGOOGLEhlsl_functionality1 extension allows use of the
// SPVGOOGLEhlsl_functionality1 extension in SPIR-V shader modules.
//
// Version History:
//
//   - Revision 1, 2018-07-09 (Neil Henning)
//   - Initial draft
package google_hlsl_functionality1
