#version 460

/* Copyright (c) 2021-2026 Holochip Corporation
 * SPDX-License-Identifier: Apache-2.0
 */

layout(local_size_x = 64) in;

struct ModelInformation
{
	float x;
	float y;
	float z;
	float r;
	uint  texture_index;
	uint  firstIndex;
	uint  indexCount;
	uint  _pad;
};

struct VkDrawIndexedIndirectCommand
{
	uint indexCount;
	uint instanceCount;
	uint firstIndex;
	int  vertexOffset;
	uint firstInstance;
};

layout(std430, set = 0, binding = 0) buffer readonly ModelInformationBuffer
{
	ModelInformation arr[];
}
model_buffer;

layout(set = 0, binding = 2) uniform GlobalUniform
{
	mat4 view;
	mat4 proj;
	mat4 proj_view;
	uint model_count;
}
global_uniform;

layout(std430, set = 0, binding = 3) buffer writeonly CommandBuffer
{
	VkDrawIndexedIndirectCommand commands[];
}
command_buffer;

// Visibility test using bounding sphere against frustum planes
bool check_is_visible(mat4 mat, vec3 origin, float radius)
{
	uint plane_index = 0;
	for (uint i = 0; i < 3; ++i)
	{
		for (uint j = 0; j < 2; ++j, ++plane_index)
		{
			if (plane_index == 2 || plane_index == 3)
			{
				continue;
			}
			const float sign  = (j > 0) ? 1.f : -1.f;
			vec4        plane = vec4(0, 0, 0, 0);
			for (uint k = 0; k < 4; ++k)
			{
				plane[k] = mat[k][3] + sign * mat[k][i];
			}
			plane.xyzw /= sqrt(dot(plane.xyz, plane.xyz));
			if (dot(origin, plane.xyz) + plane.w + radius < 0)
			{
				return false;
			}
		}
	}
	return true;
}

void main()
{
	uint id = gl_GlobalInvocationID.x;
	if (id >= global_uniform.model_count)
	{
		return;
	}
	ModelInformation model                    = model_buffer.arr[id];
	bool             is_visible               = check_is_visible(global_uniform.proj_view, vec3(model.x, model.y, model.z), model.r);
	command_buffer.commands[id].instanceCount = is_visible ? 1 : 0;
}
