// Code generated by vk-gen. DO NOT EDIT.

// Package amd_gpa_interface provides bindings for the VK_AMD_gpa_interface extension.
// Author: AMD
// Contact: Stu Smith @stu-s
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2026-05-01
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Stu Smith, AMD
//   - Tobias Hector, AMD
//   - Noah Fredriks, AMD
//   - Peter Lohrmann, AMD
//   - Maciej Dziuban, AMD
//
// Description:
//
// This extension adds GPU Performance API (GPA) interface support for
// accessing GPU global performance counters, streaming performance monitors
// (SPM), and thread traces (SQTT), on AMD Radeon™ GPUs.
//
// Version History:
//
//   - Revision 1, 2026-05-01 (Stu Smith)
//   - Initial revision
package amd_gpa_interface
