// Code generated by vk-gen. DO NOT EDIT.

// Package ext_extended_dynamic_state provides bindings for the VK_EXT_extended_dynamic_state extension.
// Author: EXT
// Contact: Piers Daniell @pdaniell-nv
// Promoted to: VK_VERSION_1_3
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2019-12-09
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Dan Ginsburg, Valve Corporation
//   - Graeme Leese, Broadcom
//   - Hans-Kristian Arntzen, Valve Corporation
//   - Jan-Harald Fredriksen, Arm Limited
//   - Faith Ekstrand, Intel
//   - Jeff Bolz, NVIDIA
//   - Jesse Hall, Google
//   - Philip Rebohle, Valve Corporation
//   - Stuart Smith, Imagination Technologies
//   - Tobias Hector, AMD
//
// Description:
//
// This extension adds some more dynamic state to support applications that
// need to reduce the number of pipeline state objects they compile and bind.
//
// Promotion to Vulkan 1.3:
//
// All dynamic state enumerants and commands in this extension are included in
// core Vulkan 1.3, with the EXT suffix omitted.
// The feature structure is not promoted.
// Extension interfaces that were promoted remain available as aliases of the
// core functionality.
//
// Issues:
//
// 1) Why are the values of pStrides in vkCmdBindVertexBuffers2
// limited to be between 0 and the maximum extent of the binding, when this
// restriction is not present for the same static state?
//
// Implementing these edge cases adds overhead to some implementations that
// would require significant cost when calling this function, and the intention
// is that this state should be more or less free to change.
//
// VKEXTvertexinputdynamic_state allows the stride to be changed
// freely when supported via vkCmdSetVertexInputEXT.
//
// Version History:
//
//   - Revision 1, 2019-12-09 (Piers Daniell)
//   - Internal revisions
package ext_extended_dynamic_state
