// Code generated by vk-gen. DO NOT EDIT.

// Package nv_cooperative_vector provides bindings for the VK_NV_cooperative_vector extension.
// Author: NV
// Contact: Jeff Bolz @jeffbolznv
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2024-05-23
//
// Interactions and External Dependencies:
//   - This extension requires
//     {spirv}/NV/SPVNVcooperativevector.html[SPVNVcooperativevector]
//   - This extension provides API support for
//     {GLSLregistry}/nv/GLSLNVcooperativevector.txt[GLNVcooperativevector]
//
// Contributors:
//   - Jeff Bolz, NVIDIA
//
// Description:
//
// This extension adds support for using cooperative vector types in SPIR-V.
// Unlike cooperative matrix types, a variable with a cooperative vector type
// is logically stored in the invocation it belongs to, but they can cooperate
// behind the scenes when performing matrix-vector multiplies.
// Cooperative vectors do not require a fully occupied subgroup or uniform
// control flow like cooperative matrices, although these do increase the
// likelihood of being on the fast path.
// And unlike normal vector types, they have arbitrary length and support a
// relatively limited set of operations.
// These types are intended to help accelerate the evaluation of small neural
// networks, where each invocation is performing its own independent evaluation
// of the network.
//
// Cooperative vector types are defined by the
// {spirv}/NV/SPVNVcooperativevector.html[SPVNVcooperativevector]
// SPIR-V extension and can be used with the
// {GLSLregistry}/nv/GLSLNVcooperativevector.txt[GLNVcooperativevector]
// GLSL extension.
//
// This extension includes support for enumerating the combinations of types
// that are supported by the implementation, and for converting matrix data to
// and from an optimized opaque layout.
//
// New SPIR-V Capabilities:
//
//   - CooperativeVectorNV
//
// Issues:
//
// Version History:
//
//   - Revision 4, 2024-05-23 (Jeff Bolz)
//   - Add maxCooperativeVectorComponents
//   - Revision 3, 2024-05-23 (Jeff Bolz)
//   - Add training functions
//   - Revision 2, 2024-02-10 (Jeff Bolz)
//   - Add device-side matrix conversion
//   - Revision 1, 2023-12-13 (Jeff Bolz)
//   - Initial revisions
package nv_cooperative_vector
