// Code generated by vk-gen. DO NOT EDIT.

package khr_video_queue

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnBindVideoSessionMemoryKHR                 uintptr
	pfnCmdBeginVideoCodingKHR                    uintptr
	pfnCmdControlVideoCodingKHR                  uintptr
	pfnCmdEndVideoCodingKHR                      uintptr
	pfnCreateVideoSessionKHR                     uintptr
	pfnCreateVideoSessionParametersKHR           uintptr
	pfnDestroyVideoSessionKHR                    uintptr
	pfnDestroyVideoSessionParametersKHR          uintptr
	pfnGetPhysicalDeviceVideoCapabilitiesKHR     uintptr
	pfnGetPhysicalDeviceVideoFormatPropertiesKHR uintptr
	pfnGetVideoSessionMemoryRequirementsKHR      uintptr
	pfnUpdateVideoSessionParametersKHR           uintptr
)

// Init resolves and initializes all VK_KHR_video_queue extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnBindVideoSessionMemoryKHR = vulkan.GetDeviceProcAddr(device, "vkBindVideoSessionMemoryKHR")
	pfnCmdBeginVideoCodingKHR = vulkan.GetDeviceProcAddr(device, "vkCmdBeginVideoCodingKHR")
	pfnCmdControlVideoCodingKHR = vulkan.GetDeviceProcAddr(device, "vkCmdControlVideoCodingKHR")
	pfnCmdEndVideoCodingKHR = vulkan.GetDeviceProcAddr(device, "vkCmdEndVideoCodingKHR")
	pfnCreateVideoSessionKHR = vulkan.GetDeviceProcAddr(device, "vkCreateVideoSessionKHR")
	pfnCreateVideoSessionParametersKHR = vulkan.GetDeviceProcAddr(device, "vkCreateVideoSessionParametersKHR")
	pfnDestroyVideoSessionKHR = vulkan.GetDeviceProcAddr(device, "vkDestroyVideoSessionKHR")
	pfnDestroyVideoSessionParametersKHR = vulkan.GetDeviceProcAddr(device, "vkDestroyVideoSessionParametersKHR")
	pfnGetPhysicalDeviceVideoCapabilitiesKHR = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceVideoCapabilitiesKHR")
	pfnGetPhysicalDeviceVideoFormatPropertiesKHR = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceVideoFormatPropertiesKHR")
	pfnGetVideoSessionMemoryRequirementsKHR = vulkan.GetDeviceProcAddr(device, "vkGetVideoSessionMemoryRequirementsKHR")
	pfnUpdateVideoSessionParametersKHR = vulkan.GetDeviceProcAddr(device, "vkUpdateVideoSessionParametersKHR")
}

// BindVideoSessionMemoryKHR - Bind Video Memory (vkBindVideoSessionMemoryKHR).
// Parameters:
//   - device: is the logical device that owns the video session.
//   - videoSession: is the video session to be bound with device memory.
//   - bindSessionMemoryInfoCount: is the number of elements in pBindSessionMemoryInfos.
//   - bindSessionMemoryInfos: is a pointer to an array of bindSessionMemoryInfoCount VkBindVideoSessionMemoryInfoKHR structures specifying memory regions to be bound to specific memory bindings of the video session.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkBindVideoSessionMemoryKHR.html
func BindVideoSessionMemoryKHR(device vulkan.Device, videoSession vulkan.VideoSessionKHR, bindSessionMemoryInfos []vulkan.BindVideoSessionMemoryInfoKHR) (result vulkan.Result) {
	c_bindSessionMemoryInfos := make([]vulkan.RawBindVideoSessionMemoryInfoKHR, len(bindSessionMemoryInfos))
	for i := range bindSessionMemoryInfos {
		if raw := bindSessionMemoryInfos[i].Raw(); raw != nil {
			c_bindSessionMemoryInfos[i] = *raw
		}
	}
	r1, _, _ := vulkan.CallSyscall(pfnBindVideoSessionMemoryKHR, uintptr(device), uintptr(videoSession), uintptr(len(bindSessionMemoryInfos)), uintptr(unsafe.Pointer(vulkan.SliceData(c_bindSessionMemoryInfos))))
	return vulkan.Result(r1)
}

// CmdBeginVideoCodingKHR - Begin video coding scope (vkCmdBeginVideoCodingKHR).
// Parameters:
//   - commandBuffer: is the command buffer in which to record the command.
//   - beginInfo: is a pointer to a VkVideoBeginCodingInfoKHR structure specifying the parameters of the video coding scope, including the video session and video session parameters object to use.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginVideoCodingKHR.html
func CmdBeginVideoCodingKHR(commandBuffer vulkan.CommandBuffer, beginInfo *vulkan.VideoBeginCodingInfoKHR) {
	c_beginInfo := beginInfo.Raw()
	vulkan.CallSyscall(pfnCmdBeginVideoCodingKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_beginInfo)))
}

// CmdControlVideoCodingKHR - Control video coding parameters (vkCmdControlVideoCodingKHR).
// Parameters:
//   - commandBuffer: is the command buffer in which to record the command.
//   - codingControlInfo: is a pointer to a VkVideoCodingControlInfoKHR structure specifying the control parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdControlVideoCodingKHR.html
func CmdControlVideoCodingKHR(commandBuffer vulkan.CommandBuffer, codingControlInfo *vulkan.VideoCodingControlInfoKHR) {
	c_codingControlInfo := codingControlInfo.Raw()
	vulkan.CallSyscall(pfnCmdControlVideoCodingKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_codingControlInfo)))
}

// CmdEndVideoCodingKHR - End video coding scope (vkCmdEndVideoCodingKHR).
// Parameters:
//   - commandBuffer: is the command buffer in which to record the command.
//   - endCodingInfo: is a pointer to a VkVideoEndCodingInfoKHR structure specifying the parameters for ending the video coding scope.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdEndVideoCodingKHR.html
func CmdEndVideoCodingKHR(commandBuffer vulkan.CommandBuffer, endCodingInfo *vulkan.VideoEndCodingInfoKHR) {
	c_endCodingInfo := endCodingInfo.Raw()
	vulkan.CallSyscall(pfnCmdEndVideoCodingKHR, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_endCodingInfo)))
}

// CreateVideoSessionKHR - Creates a video session object (vkCreateVideoSessionKHR).
// Parameters:
//   - device: is the logical device that creates the video session.
//   - createInfo: is a pointer to a VkVideoSessionCreateInfoKHR structure containing parameters to be used to create the video session.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//   - videoSession: is a pointer to a VkVideoSessionKHR handle in which the resulting video session object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_INITIALIZATION_FAILED, VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR, VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateVideoSessionKHR.html
func CreateVideoSessionKHR(device vulkan.Device, createInfo *vulkan.VideoSessionCreateInfoKHR, allocator *vulkan.AllocationCallbacks) (videoSession vulkan.VideoSessionKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateVideoSessionKHR, uintptr(device), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&videoSession)))
	return videoSession, vulkan.Result(r1)
}

// CreateVideoSessionParametersKHR - Creates video session parameters object (vkCreateVideoSessionParametersKHR).
// Parameters:
//   - device: is the logical device that creates the video session parameters object.
//   - createInfo: is a pointer to VkVideoSessionParametersCreateInfoKHR structure containing parameters to be used to create the video session parameters object.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//   - videoSessionParameters: is a pointer to a VkVideoSessionParametersKHR handle in which the resulting video session parameters object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_INITIALIZATION_FAILED, VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateVideoSessionParametersKHR.html
func CreateVideoSessionParametersKHR(device vulkan.Device, createInfo *vulkan.VideoSessionParametersCreateInfoKHR, allocator *vulkan.AllocationCallbacks) (videoSessionParameters vulkan.VideoSessionParametersKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateVideoSessionParametersKHR, uintptr(device), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&videoSessionParameters)))
	return videoSessionParameters, vulkan.Result(r1)
}

// DestroyVideoSessionKHR - Destroy video session object (vkDestroyVideoSessionKHR).
// Parameters:
//   - device: is the logical device that destroys the video session.
//   - videoSession: is the video session to destroy.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkDestroyVideoSessionKHR.html
func DestroyVideoSessionKHR(device vulkan.Device, videoSession vulkan.VideoSessionKHR, allocator *vulkan.AllocationCallbacks) {
	c_allocator := allocator.Raw()
	vulkan.CallSyscall(pfnDestroyVideoSessionKHR, uintptr(device), uintptr(videoSession), uintptr(unsafe.Pointer(c_allocator)))
}

// DestroyVideoSessionParametersKHR - Destroy video session parameters object (vkDestroyVideoSessionParametersKHR).
// Parameters:
//   - device: is the logical device that destroys the video session parameters object.
//   - videoSessionParameters: is the video session parameters object to destroy.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkDestroyVideoSessionParametersKHR.html
func DestroyVideoSessionParametersKHR(device vulkan.Device, videoSessionParameters vulkan.VideoSessionParametersKHR, allocator *vulkan.AllocationCallbacks) {
	c_allocator := allocator.Raw()
	vulkan.CallSyscall(pfnDestroyVideoSessionParametersKHR, uintptr(device), uintptr(videoSessionParameters), uintptr(unsafe.Pointer(c_allocator)))
}

// GetPhysicalDeviceVideoCapabilitiesKHR - Query video coding capabilities (vkGetPhysicalDeviceVideoCapabilitiesKHR).
// Parameters:
//   - physicalDevice: is the physical device from which to query the video decode or encode capabilities.
//   - videoProfile: is a pointer to a VkVideoProfileInfoKHR structure.
//   - capabilities: is a pointer to a VkVideoCapabilitiesKHR structure in which the capabilities are returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR, VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR, VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR, VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceVideoCapabilitiesKHR.html
func GetPhysicalDeviceVideoCapabilitiesKHR(physicalDevice vulkan.PhysicalDevice, videoProfile *vulkan.VideoProfileInfoKHR) (capabilities vulkan.VideoCapabilitiesKHR, result vulkan.Result) {
	c_videoProfile := videoProfile.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetPhysicalDeviceVideoCapabilitiesKHR, uintptr(physicalDevice), uintptr(unsafe.Pointer(c_videoProfile)), uintptr(unsafe.Pointer(&capabilities)))
	return capabilities, vulkan.Result(r1)
}

// GetPhysicalDeviceVideoFormatPropertiesKHR - Query supported video decode and encode image formats and capabilities (vkGetPhysicalDeviceVideoFormatPropertiesKHR).
// Parameters:
//   - physicalDevice: is the physical device from which to query the video format properties.
//   - videoFormatInfo: is a pointer to a VkPhysicalDeviceVideoFormatInfoKHR structure specifying the usage and video profiles for which supported image formats and capabilities are returned.
//   - videoFormatPropertyCount: is a pointer to an integer related to the number of video format properties available or queried, as described below.
//   - videoFormatProperties: is a pointer to an array of VkVideoFormatPropertiesKHR structures in which supported image formats and capabilities are returned.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR, VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR, VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR, VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR, VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceVideoFormatPropertiesKHR.html
func GetPhysicalDeviceVideoFormatPropertiesKHR(physicalDevice vulkan.PhysicalDevice, videoFormatInfo *vulkan.PhysicalDeviceVideoFormatInfoKHR) (videoFormatProperties []vulkan.VideoFormatPropertiesKHR, result vulkan.Result) {
	c_videoFormatInfo := videoFormatInfo.Raw()
	var count uint32
	r1, _, _ := vulkan.CallSyscall(pfnGetPhysicalDeviceVideoFormatPropertiesKHR, uintptr(physicalDevice), uintptr(unsafe.Pointer(c_videoFormatInfo)), uintptr(unsafe.Pointer(&count)), 0)
	if vulkan.Result(r1) != vulkan.SUCCESS || count == 0 {
		return nil, vulkan.Result(r1)
	}

	videoFormatProperties = make([]vulkan.VideoFormatPropertiesKHR, count)
	call2ArgsPtr := uintptr(unsafe.Pointer(&videoFormatProperties[0]))
	r1, _, _ = vulkan.CallSyscall(pfnGetPhysicalDeviceVideoFormatPropertiesKHR, uintptr(physicalDevice), uintptr(unsafe.Pointer(c_videoFormatInfo)), uintptr(unsafe.Pointer(&count)), call2ArgsPtr)
	return videoFormatProperties, vulkan.Result(r1)
}

// GetVideoSessionMemoryRequirementsKHR - Get the memory requirements for a video session (vkGetVideoSessionMemoryRequirementsKHR).
// Parameters:
//   - device: is the logical device that owns the video session.
//   - videoSession: is the video session to query.
//   - memoryRequirementsCount: is a pointer to an integer related to the number of memory binding requirements available or queried, as described below.
//   - memoryRequirements: is NULL or a pointer to an array of VkVideoSessionMemoryRequirementsKHR structures in which the memory binding requirements of the video session are returned.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetVideoSessionMemoryRequirementsKHR.html
func GetVideoSessionMemoryRequirementsKHR(device vulkan.Device, videoSession vulkan.VideoSessionKHR) (memoryRequirements []vulkan.VideoSessionMemoryRequirementsKHR, result vulkan.Result) {
	var count uint32
	r1, _, _ := vulkan.CallSyscall(pfnGetVideoSessionMemoryRequirementsKHR, uintptr(device), uintptr(videoSession), uintptr(unsafe.Pointer(&count)), 0)
	if vulkan.Result(r1) != vulkan.SUCCESS || count == 0 {
		return nil, vulkan.Result(r1)
	}

	memoryRequirements = make([]vulkan.VideoSessionMemoryRequirementsKHR, count)
	call2ArgsPtr := uintptr(unsafe.Pointer(&memoryRequirements[0]))
	r1, _, _ = vulkan.CallSyscall(pfnGetVideoSessionMemoryRequirementsKHR, uintptr(device), uintptr(videoSession), uintptr(unsafe.Pointer(&count)), call2ArgsPtr)
	return memoryRequirements, vulkan.Result(r1)
}

// UpdateVideoSessionParametersKHR - Update video session parameters object (vkUpdateVideoSessionParametersKHR).
// Parameters:
//   - device: is the logical device that updates the video session parameters.
//   - videoSessionParameters: is the video session parameters object to update.
//   - updateInfo: is a pointer to a VkVideoSessionParametersUpdateInfoKHR structure specifying the parameter update information.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkUpdateVideoSessionParametersKHR.html
func UpdateVideoSessionParametersKHR(device vulkan.Device, videoSessionParameters vulkan.VideoSessionParametersKHR, updateInfo *vulkan.VideoSessionParametersUpdateInfoKHR) (result vulkan.Result) {
	c_updateInfo := updateInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnUpdateVideoSessionParametersKHR, uintptr(device), uintptr(videoSessionParameters), uintptr(unsafe.Pointer(c_updateInfo)))
	return vulkan.Result(r1)
}
