// Code generated by vk-gen. DO NOT EDIT.

package khr_xlib_surface

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCreateXlibSurfaceKHR                        uintptr
	pfnGetPhysicalDeviceXlibPresentationSupportKHR uintptr
)

// Init resolves and initializes all VK_KHR_xlib_surface extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCreateXlibSurfaceKHR = vulkan.GetInstanceProcAddr(instance, "vkCreateXlibSurfaceKHR")
	pfnGetPhysicalDeviceXlibPresentationSupportKHR = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceXlibPresentationSupportKHR")
}

// CreateXlibSurfaceKHR - Create a VkSurfaceKHR object for an X11 window, using the Xlib client-side library (vkCreateXlibSurfaceKHR).
// Parameters:
//   - instance: is the instance to associate the surface with.
//   - createInfo: is a pointer to a VkXlibSurfaceCreateInfoKHR structure containing the parameters affecting the creation of the surface object.
//   - allocator: is the allocator used for host memory allocated for the surface object when there is no more specific allocator available (see Memory Allocation).
//   - surface: is a pointer to a VkSurfaceKHR handle in which the created surface object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateXlibSurfaceKHR.html
func CreateXlibSurfaceKHR(instance vulkan.Instance, createInfo *vulkan.XlibSurfaceCreateInfoKHR, allocator *vulkan.AllocationCallbacks) (surface vulkan.SurfaceKHR, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateXlibSurfaceKHR, uintptr(instance), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&surface)))
	return surface, vulkan.Result(r1)
}

// GetPhysicalDeviceXlibPresentationSupportKHR - Query physical device for presentation to X11 server using Xlib (vkGetPhysicalDeviceXlibPresentationSupportKHR).
// Parameters:
//   - physicalDevice: is the physical device.
//   - queueFamilyIndex: is the queue family index.
//   - dpy: is a pointer to an Xlib Display connection to the server.
//   - visualID: is an X11 visual (VisualID).
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceXlibPresentationSupportKHR.html
func GetPhysicalDeviceXlibPresentationSupportKHR(physicalDevice vulkan.PhysicalDevice, queueFamilyIndex uint32, visualID uintptr) (dpy uintptr) {
	vulkan.CallSyscall(pfnGetPhysicalDeviceXlibPresentationSupportKHR, uintptr(physicalDevice), uintptr(queueFamilyIndex), uintptr(unsafe.Pointer(&dpy)), uintptr(visualID))
	return dpy
}
