// Code generated by vk-gen. DO NOT EDIT.

// Package nv_external_memory_rdma provides bindings for the VK_NV_external_memory_rdma extension.
// Author: NV
// Contact: Carsten Rohde @crohde
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2021-04-19
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Carsten Rohde, NVIDIA
//
// Description:
//
// This extension adds support for allocating memory which can be used for
// remote direct memory access (RDMA) from other devices.
//
// Issues:
//
// Examples:
//
// VkPhysicalDeviceMemoryBudgetPropertiesEXT memoryBudgetProperties = { VKSTRUCTURETYPEPHYSICALDEVICEMEMORYBUDGETPROPERTIESEXT };
// VkPhysicalDeviceMemoryProperties2 memoryProperties2 = { VKSTRUCTURETYPEPHYSICALDEVICEMEMORYPROPERTIES_2, &memoryBudgetProperties };
// vkGetPhysicalDeviceMemoryProperties2(physicalDevice, &memoryProperties2);
// uint32t heapIndex = (uint32t)-1;
//
//	for (uint32_t memoryType = 0; memoryType < memoryProperties2.memoryProperties.memoryTypeCount; memoryType++) {
//	    if (memoryProperties2.memoryProperties.memoryTypes[memoryType].propertyFlags & VKMEMORYPROPERTYRDMACAPABLEBITNV) {
//	        heapIndex = memoryProperties2.memoryProperties.memoryTypes[memoryType].heapIndex;
//	        break;
//	    }
//	}
//
// if ((heapIndex == (uint32_t)-1) ||
//
//	    (memoryBudgetProperties.heapBudget[heapIndex] < size)) {
//	    return;
//	}
//
// VkPhysicalDeviceExternalBufferInfo externalBufferInfo = { VKSTRUCTURETYPEPHYSICALDEVICEEXTERNALBUFFER_INFO };
// externalBufferInfo.usage = VKBUFFERUSAGETRANSFERSRCBIT | VKBUFFERUSAGETRANSFERDSTBIT;
// externalBufferInfo.handleType = VKEXTERNALMEMORYHANDLETYPERDMAADDRESSBITNV;
//
// VkExternalBufferProperties externalBufferProperties = { VKSTRUCTURETYPEEXTERNALBUFFER_PROPERTIES };
// vkGetPhysicalDeviceExternalBufferProperties(physicalDevice, &externalBufferInfo, &externalBufferProperties);
//
//	if (!(externalBufferProperties.externalMemoryProperties.externalMemoryFeatures & VKEXTERNALMEMORYFEATUREEXPORTABLE_BIT)) {
//	    return;
//	}
//
// VkExternalMemoryBufferCreateInfo externalMemoryBufferCreateInfo = { VKSTRUCTURETYPEEXTERNALMEMORYBUFFERCREATE_INFO };
// externalMemoryBufferCreateInfo.handleTypes = VKEXTERNALMEMORYHANDLETYPERDMAADDRESSBITNV;
//
// VkBufferCreateInfo bufferCreateInfo = { VKSTRUCTURETYPEBUFFERCREATE_INFO, &externalMemoryBufferCreateInfo };
// bufferCreateInfo.size = size;
// bufferCreateInfo.usage = VKBUFFERUSAGETRANSFERSRCBIT | VKBUFFERUSAGETRANSFERDSTBIT;
//
// VkMemoryRequirements mem_reqs;
// vkCreateBuffer(device, &bufferCreateInfo, NULL, &buffer);
// vkGetBufferMemoryRequirements(device, buffer, &mem_reqs);
//
// VkExportMemoryAllocateInfo exportMemoryAllocateInfo = { VKSTRUCTURETYPEEXPORTMEMORYALLOCATEINFO };
// exportMemoryAllocateInfo.handleTypes = VKEXTERNALMEMORYHANDLETYPERDMAADDRESSBITNV;
//
// uint32_t i = 0;
//
//	for (; i < VKMAXMEMORY_TYPES; i++) {
//	    if ((mem_reqs.memoryTypeBits & (1 << i)) &&
//	        (memoryProperties.memoryTypes[i].propertyFlags & VKMEMORYPROPERTYRDMACAPABLEBITNV)) {
//	        break;
//	    }
//	}
//
// VkMemoryAllocateInfo memAllocInfo = { VKSTRUCTURETYPEMEMORYALLOCATE_INFO, &exportMemoryAllocateInfo };
// memAllocInfo.allocationSize = mem_reqs.size;
// memAllocInfo.memoryTypeIndex = i;
//
// vkAllocateMemory(device, &memAllocInfo, NULL, &mem);
// vkBindBufferMemory(device, buffer, mem, 0);
//
// VkMemoryGetRemoteAddressInfoNV getMemoryRemoteAddressInfo = { VKSTRUCTURETYPEMEMORYGETREMOTEADDRESSINFONV };
// getMemoryRemoteAddressInfo.memory = mem;
// getMemoryRemoteAddressInfo.handleType = VKEXTERNALMEMORYHANDLETYPERDMAADDRESSBITNV;
//
// VkRemoteAddressNV rdmaAddress;
// vkGetMemoryRemoteAddressNV(device, &getMemoryRemoteAddressInfo, &rdmaAddress);
//
// Version History:
//
//   - Revision 1, 2020-12-15 (Carsten Rohde)
//   - Internal revisions
package nv_external_memory_rdma
