// Code generated by vk-gen. DO NOT EDIT.

// Package fuchsia_imagepipe_surface provides bindings for the VK_FUCHSIA_imagepipe_surface extension.
// Author: FUCHSIA
// Contact: Craig Stout @cdotstout
// Platform: fuchsia
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2018-07-27
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Craig Stout, Google
//   - Ian Elliott, Google
//   - Jesse Hall, Google
//
// Description:
//
// The VKFUCHSIAimagepipe_surface extension is an instance extension.
// It provides a mechanism to create a VkSurfaceKHR object (defined by
// the VKKHRsurface extension) that refers to a Fuchsia
// imagePipeHandle.
//
// Version History:
//
//   - Revision 1, 2018-07-27 (Craig Stout)
//   - Initial draft.
package fuchsia_imagepipe_surface
