// Code generated by vk-gen. DO NOT EDIT.

package ext_image_drm_format_modifier

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetImageDrmFormatModifierPropertiesEXT uintptr
)

// Init resolves and initializes all VK_EXT_image_drm_format_modifier extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetImageDrmFormatModifierPropertiesEXT = vulkan.GetDeviceProcAddr(device, "vkGetImageDrmFormatModifierPropertiesEXT")
}

// GetImageDrmFormatModifierPropertiesEXT - Returns an image\ (vkGetImageDrmFormatModifierPropertiesEXT).
// Parameters:
//   - device: is the logical device that owns the image.
//   - image: is the queried image.
//   - properties: is a pointer to a VkImageDrmFormatModifierPropertiesEXT structure in which properties of the image's _DRM format modifier_ are returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetImageDrmFormatModifierPropertiesEXT.html
func GetImageDrmFormatModifierPropertiesEXT(device vulkan.Device, image vulkan.Image) (properties vulkan.ImageDrmFormatModifierPropertiesEXT, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnGetImageDrmFormatModifierPropertiesEXT, uintptr(device), uintptr(image), uintptr(unsafe.Pointer(&properties)))
	return properties, vulkan.Result(r1)
}
