// Code generated by vk-gen. DO NOT EDIT.

// Package ext_texture_compression_astc_hdr provides bindings for the VK_EXT_texture_compression_astc_hdr extension.
// Author: ARM
// Contact: Jan-Harald Fredriksen @janharaldfredriksen-arm
// Promoted to: VK_VERSION_1_3
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2019-05-28
//
// IP Status:
//
//	No known issues.
//
// Contributors:
//   - Jan-Harald Fredriksen, Arm
//
// Description:
//
// This extension adds support for textures compressed using the Adaptive
// Scalable Texture Compression (ASTC) High Dynamic Range (HDR) profile.
//
// When this extension is enabled, the HDR profile is supported for all ASTC
// formats listed in <<appendix-compressedtex-astc, ASTC Compressed Image
// Formats>>.
//
// Promotion to Vulkan 1.3:
//
// Vulkan APIs in this extension are included in core Vulkan 1.3, with the EXT
// suffix omitted.
// However, the feature is made optional in Vulkan 1.3.
// External interactions defined by this extension, such as SPIR-V token names,
// retain their original names.
// The original Vulkan API names are still available as aliases of the core
// functionality.
//
// Issues:
//
// 1) Should we add a feature or limit for this functionality?
//
// Yes.
// It is consistent with the ASTC LDR support to add a feature like
// textureCompressionASTC_HDR.
//
// The feature is strictly speaking redundant as long as this is just an
// extension; it would be sufficient to just enable the extension.
// But adding the feature is more forward-looking if wanted to make this an
// optional core feature in the future.
//
// 2) Should we introduce new format enums for HDR?
//
// Yes.
// Vulkan 1.0 describes the ASTC format enums as UNORM, e.g.
// VKFORMATASTC4x4UNORM_BLOCK, so it is confusing to make these
// contain HDR data.
// Note that the OpenGL (ES) extensions did not make this distinction because a
// single ASTC HDR texture may contain both unorm and float blocks.
// Implementations may: not be able to distinguish between LDR and HDR ASTC
// textures internally and just treat them as the same format, i.e. if this
// extension is supported then sampling from a
// VKFORMATASTC4x4UNORM_BLOCK image format may: return HDR results.
// Applications can: get predictable results by using the appropriate image
// format.
//
// Version History:
//
//   - Revision 1, 2019-05-28 (Jan-Harald Fredriksen)
//   - Initial version
package ext_texture_compression_astc_hdr
