// Code generated by vk-gen. DO NOT EDIT.

package ext_color_write_enable

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdSetColorWriteEnableEXT uintptr
)

// Init resolves and initializes all VK_EXT_color_write_enable extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdSetColorWriteEnableEXT = vulkan.GetDeviceProcAddr(device, "vkCmdSetColorWriteEnableEXT")
}

// CmdSetColorWriteEnableEXT - Enable or disable writes to a color attachment dynamically for a command buffer (vkCmdSetColorWriteEnableEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - attachmentCount: is the number of basetype:VkBool32 elements in pColorWriteEnables.
//   - colorWriteEnables: is a pointer to an array of per target attachment boolean values specifying whether color writes are enabled for the given attachment.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetColorWriteEnableEXT.html
func CmdSetColorWriteEnableEXT(commandBuffer vulkan.CommandBuffer, colorWriteEnables []vulkan.Bool32) {
	c_colorWriteEnables := vulkan.SliceData(colorWriteEnables)
	vulkan.CallSyscall(pfnCmdSetColorWriteEnableEXT, uintptr(commandBuffer), uintptr(len(colorWriteEnables)), uintptr(unsafe.Pointer(c_colorWriteEnables)))
}
