// Code generated by vk-gen. DO NOT EDIT.

// Package amd_texture_gather_bias_lod provides bindings for the VK_AMD_texture_gather_bias_lod extension.
// Author: AMD
// Contact: Rex Xu @amdrexu
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2017-03-21
//
// IP Status:
//
//	No known IP claims.
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLregistry}/AMD/AMDtexturegatherbiaslod.txt[GLAMDtexturegatherbias_lod]
//
// Contributors:
//   - Dominik Witczak, AMD
//   - Daniel Rakos, AMD
//   - Graham Sellers, AMD
//   - Matthaeus G. Chajdas, AMD
//   - Qun Lin, AMD
//   - Rex Xu, AMD
//   - Timothy Lottes, AMD
//
// Description:
//
// This extension adds two related features.
//
// Firstly, support for the following SPIR-V extension in Vulkan is added:
//
//   - SPVAMDtexturegatherbias_lod
//
// Secondly, the extension allows the application to query which formats can be
// used together with the new function prototypes introduced by the SPIR-V
// extension.
//
// New SPIR-V Capabilities:
//
//   - <<spirvenv-capabilities-table-ImageGatherBiasLodAMD,
//     ImageGatherBiasLodAMD>>
//
// Examples:
//
// struct VkTextureLODGatherFormatPropertiesAMD
//
//	{
//	    VkStructureType sType;
//	    const void*     pNext;
//	    VkBool32        supportsTextureGatherLODBiasAMD;
//	};
//
// VkPhysicalDeviceImageFormatInfo2   formatInfo;
// VkImageFormatProperties2           formatProps;
// VkTextureLODGatherFormatPropertiesAMD textureLODGatherSupport;
//
// textureLODGatherSupport.sType = VKSTRUCTURETYPETEXTURELODGATHERFORMATPROPERTIESAMD;
// textureLODGatherSupport.pNext = nullptr;
//
// formatInfo.sType  = VKSTRUCTURETYPEPHYSICALDEVICEIMAGEFORMATINFO2;
// formatInfo.pNext  = nullptr;
// formatInfo.format = ...;
// formatInfo.type   = ...;
// formatInfo.tiling = ...;
// formatInfo.usage  = ...;
// formatInfo.flags  = ...;
//
// formatProps.sType = VKSTRUCTURETYPEIMAGEFORMATPROPERTIES2;
// formatProps.pNext = &textureLODGatherSupport;
//
// vkGetPhysicalDeviceImageFormatProperties2(physical_device, &formatInfo, &formatProps);
//
// if (textureLODGatherSupport.supportsTextureGatherLODBiasAMD == VK_TRUE)
// {
// }
// else
// {
// }
//
// Version History:
//
//   - Revision 1, 2017-03-21 (Dominik Witczak)
//   - Initial draft
package amd_texture_gather_bias_lod
