// Code generated by vk-gen. DO NOT EDIT.

// Package ext_vertex_input_dynamic_state provides bindings for the VK_EXT_vertex_input_dynamic_state extension.
// Author: EXT
// Contact: Piers Daniell @pdaniell-nv
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2020-08-21
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Jeff Bolz, NVIDIA
//   - Spencer Fricke, Samsung
//   - Stu Smith, AMD
//
// Description:
//
// One of the states that contributes to the combinatorial explosion of
// pipeline state objects that need to be created, is the vertex input binding
// and attribute descriptions.
// By allowing them to be dynamic applications may reduce the number of
// pipeline objects they need to create.
//
// This extension adds dynamic state support for what is normally static state
// in VkPipelineVertexInputStateCreateInfo.
//
// Version History:
//
//   - Revision 2, 2020-11-05 (Piers Daniell)
//
//   - Make VkVertexInputBindingDescription2EXT extensible
//
//   - Add new VkVertexInputAttributeDescription2EXT structure for the
//     pVertexAttributeDescriptions parameter to
//     vkCmdSetVertexInputEXT so it is also extensible
//
//   - Revision 1, 2020-08-21 (Piers Daniell)
//
//   - Internal revisions
package ext_vertex_input_dynamic_state
