// Code generated by vk-gen. DO NOT EDIT.

// Package khr_device_group_creation provides bindings for the VK_KHR_device_group_creation extension.
// Author: KHR
// Contact: Jeff Bolz @jeffbolznv
// Promoted to: VK_VERSION_1_1
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2016-10-19
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Jeff Bolz, NVIDIA
//
// Description:
//
// This extension provides instance-level commands to enumerate groups of
// physical devices, and to create a logical device from a subset of one of
// those groups.
// Such a logical device can then be used with new features in the
// VKKHRdevice_group extension.
//
// Promotion to Vulkan 1.1:
//
// All functionality in this extension is included in core Vulkan 1.1, with the
// KHR suffix omitted.
// The original type, enum, and command names are still available as aliases of
// the core functionality.
//
// Examples:
//
//	VkDeviceCreateInfo devCreateInfo = { VKSTRUCTURETYPEDEVICECREATE_INFO };
//	uint32_t deviceGroupCount = 0;
//	VkPhysicalDeviceGroupPropertiesKHR *props = NULL;
//
//	vkEnumeratePhysicalDeviceGroupsKHR(g_vkInstance, &deviceGroupCount, NULL);
//
//	props = (VkPhysicalDeviceGroupPropertiesKHR )malloc(deviceGroupCountsizeof(VkPhysicalDeviceGroupPropertiesKHR));
//	for (i = 0; i < deviceGroupCount; ++i) {
//	    props[i].sType = VKSTRUCTURETYPEPHYSICALDEVICEGROUPPROPERTIES_KHR;
//	    props[i].pNext = NULL;
//	}
//	vkEnumeratePhysicalDeviceGroupsKHR(g_vkInstance, &deviceGroupCount, props);
//
//	VkDeviceGroupDeviceCreateInfoKHR deviceGroupInfo = { VKSTRUCTURETYPEDEVICEGROUPDEVICECREATEINFOKHR };
//	if (props[0].physicalDeviceCount > 1) {
//	    deviceGroupInfo.physicalDeviceCount = props[0].physicalDeviceCount;
//	    deviceGroupInfo.pPhysicalDevices = props[0].physicalDevices;
//	    devCreateInfo.pNext = &deviceGroupInfo;
//	}
//
//	vkCreateDevice(props[0].physicalDevices[0], &devCreateInfo, NULL, &g_vkDevice);
//	free(props);
//
// Version History:
//
//   - Revision 1, 2016-10-19 (Jeff Bolz)
//   - Internal revisions
package khr_device_group_creation
