// Code generated by vk-gen. DO NOT EDIT.

// Package nv_ray_tracing_linear_swept_spheres provides bindings for the VK_NV_ray_tracing_linear_swept_spheres extension.
// Author: NV
// Contact: Vikram Kushwaha @vkushwaha
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2025-01-03
//
// Interactions and External Dependencies:
//   - This extension requires
//     {spirv}/NV/SPVNVlinearsweptspheres.html[SPVNVlinearsweptspheres]
//   - This extension provides API support for
//     {GLSLregistry}/nv/GLSLNVlinearsweptspheres.txt[GLNVlinearsweptspheres]
//
// Contributors:
//   - Vikram Kushwaha, NVIDIA
//   - Eric Werness, NVIDIA
//   - Daniel Koch, NVIDIA
//   - Ashwin Lele, NVIDIA
//   - Nathan Morrical, NVIDIA
//
// Description:
//
// This extension adds two new primitives for ray tracing: a sphere primitive
// and a linear swept sphere (LSS) primitive.
// The purpose of the LSS primitive is to enable rendering of high quality hair
// and fur using a compact primitive representation encoded in the acceleration
// structure.
// Sphere primitives are defined by a position and a radius and are a subset of
// LSS, but are useful in their own right, for example for particle systems.
//
// This extension adds support for the following SPIR-V extension in Vulkan:
//
//   - SPVNVlinearsweptspheres
//
// New or Modified Built-In Variables:
//
//   - HitIsSphereNV
//   - HitIsLSSNV
//   - HitSpherePositionNV
//   - HitSphereRadiusNV
//   - HitLSSPositionsNV
//   - HitLSSRadiiNV
//
// New SPIR-V Capabilities:
//
//   - <<spirvenv-capabilities-table-RayTracingSpheresGeometryNV,
//     RayTracingSpheresGeometryNV>>
//   - <<spirvenv-capabilities-table-RayTracingLinearSweptSpheresGeometryNV,
//     RayTracingLinearSweptSpheresGeometryNV>>
//
// Version History:
//
//   - Revision 1, 2025-01-03 (Vikram Kushwaha)
//   - Initial draft
package nv_ray_tracing_linear_swept_spheres
