// Code generated by vk-gen. DO NOT EDIT.

// Package khr_device_group provides bindings for the VK_KHR_device_group extension.
// Author: KHR
// Contact: Jeff Bolz @jeffbolznv
// Promoted to: VK_VERSION_1_1
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2017-10-10
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Jeff Bolz, NVIDIA
//   - Tobias Hector, Imagination Technologies
//
// Description:
//
// This extension provides functionality to use a logical device that consists
// of multiple physical devices, as created with the
// VKKHRdevicegroupcreation extension.
// A device group can allocate memory across the subdevices, bind memory from
// one subdevice to a resource on another subdevice, record command buffers
// where some work executes on an arbitrary subset of the subdevices, and
// potentially present a swapchain image from one or more subdevices.
//
// Promotion to Vulkan 1.1:
//
// The following enums, types, and commands are included as interactions with
// VKKHRswapchain:
//
//   - VKSTRUCTURETYPEDEVICEGROUPPRESENTCAPABILITIES_KHR
//   - VKSTRUCTURETYPEIMAGESWAPCHAINCREATEINFO_KHR
//   - VKSTRUCTURETYPEBINDIMAGEMEMORYSWAPCHAININFOKHR
//   - VKSTRUCTURETYPEACQUIRENEXTIMAGEINFO_KHR
//   - VKSTRUCTURETYPEDEVICEGROUPPRESENTINFO_KHR
//   - VKSTRUCTURETYPEDEVICEGROUPSWAPCHAINCREATEINFOKHR
//   - VKSWAPCHAINCREATESPLITINSTANCEBINDREGIONSBITKHR
//   - VkDeviceGroupPresentModeFlagBitsKHR
//   - VkDeviceGroupPresentCapabilitiesKHR
//   - VkImageSwapchainCreateInfoKHR
//   - VkBindImageMemorySwapchainInfoKHR
//   - VkAcquireNextImageInfoKHR
//   - VkDeviceGroupPresentInfoKHR
//   - VkDeviceGroupSwapchainCreateInfoKHR
//   - vkGetDeviceGroupPresentCapabilitiesKHR
//   - vkGetDeviceGroupSurfacePresentModesKHR
//   - vkGetPhysicalDevicePresentRectanglesKHR
//   - vkAcquireNextImage2KHR
//
// If Vulkan 1.1 and VKKHRswapchain are supported, these are
// included by VKKHRswapchain.
//
// The base functionality in this extension is included in core Vulkan 1.1,
// with the KHR suffix omitted.
// The original type, enum, and command names are still available as aliases of
// the core functionality.
//
// New Built-in Variables:
//
//   - DeviceIndex
//
// New SPIR-V Capabilities:
//
//   - DeviceGroup
//
// Version History:
//
//   - Revision 1, 2016-10-19 (Jeff Bolz)
//   - Internal revisions
//   - Revision 2, 2017-05-19 (Tobias Hector)
//   - Removed extended memory bind functions to VKKHRbind_memory2, added
//     dependency on that extension, and device-group-specific structs for
//     those functions.
//   - Revision 3, 2017-10-06 (Ian Elliott)
//   - Corrected Vulkan 1.1 interactions with the WSI extensions.
//     All Vulkan 1.1 WSI interactions are with the VKKHRswapchain
//     extension.
//   - Revision 4, 2017-10-10 (Jeff Bolz)
//   - Rename "SFR" bits and structure members to use the phrase "`split
//     instance bind regions`".
package khr_device_group
