// Code generated by vk-gen. DO NOT EDIT.

package khr_copy_commands2

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdBlitImage2KHR         uintptr
	pfnCmdCopyBuffer2KHR        uintptr
	pfnCmdCopyBufferToImage2KHR uintptr
	pfnCmdCopyImage2KHR         uintptr
	pfnCmdCopyImageToBuffer2KHR uintptr
	pfnCmdResolveImage2KHR      uintptr
)

// Init resolves and initializes all VK_KHR_copy_commands2 extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdBlitImage2KHR = vulkan.GetInstanceProcAddr(instance, "vkCmdBlitImage2KHR")
	pfnCmdCopyBuffer2KHR = vulkan.GetInstanceProcAddr(instance, "vkCmdCopyBuffer2KHR")
	pfnCmdCopyBufferToImage2KHR = vulkan.GetInstanceProcAddr(instance, "vkCmdCopyBufferToImage2KHR")
	pfnCmdCopyImage2KHR = vulkan.GetInstanceProcAddr(instance, "vkCmdCopyImage2KHR")
	pfnCmdCopyImageToBuffer2KHR = vulkan.GetInstanceProcAddr(instance, "vkCmdCopyImageToBuffer2KHR")
	pfnCmdResolveImage2KHR = vulkan.GetInstanceProcAddr(instance, "vkCmdResolveImage2KHR")
}

// CmdBlitImage2KHR executes vkCmdBlitImage2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBlitImage2KHR.html
func CmdBlitImage2KHR() {
	vulkan.CallSyscall(pfnCmdBlitImage2KHR)
}

// CmdCopyBuffer2KHR executes vkCmdCopyBuffer2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyBuffer2KHR.html
func CmdCopyBuffer2KHR() {
	vulkan.CallSyscall(pfnCmdCopyBuffer2KHR)
}

// CmdCopyBufferToImage2KHR executes vkCmdCopyBufferToImage2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyBufferToImage2KHR.html
func CmdCopyBufferToImage2KHR() {
	vulkan.CallSyscall(pfnCmdCopyBufferToImage2KHR)
}

// CmdCopyImage2KHR executes vkCmdCopyImage2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyImage2KHR.html
func CmdCopyImage2KHR() {
	vulkan.CallSyscall(pfnCmdCopyImage2KHR)
}

// CmdCopyImageToBuffer2KHR executes vkCmdCopyImageToBuffer2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyImageToBuffer2KHR.html
func CmdCopyImageToBuffer2KHR() {
	vulkan.CallSyscall(pfnCmdCopyImageToBuffer2KHR)
}

// CmdResolveImage2KHR executes vkCmdResolveImage2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdResolveImage2KHR.html
func CmdResolveImage2KHR() {
	vulkan.CallSyscall(pfnCmdResolveImage2KHR)
}
