// Code generated by vk-gen. DO NOT EDIT.

// Package ext_scalar_block_layout provides bindings for the VK_EXT_scalar_block_layout extension.
// Author: EXT
// Contact: Tobias Hector @tobski
// Promoted to: VK_VERSION_1_2
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2018-11-14
//
// Contributors:
//   - Jeff Bolz
//   - Jan-Harald Fredriksen
//   - Graeme Leese
//   - Faith Ekstrand
//   - John Kessenich
//
// Description:
//
// This extension enables C-like structure layout for SPIR-V blocks.
// It modifies the alignment rules for uniform buffers, storage buffers and
// push constants, allowing non-scalar types to be aligned solely based on the
// size of their components, without additional requirements.
//
// Promotion to Vulkan 1.2:
//
// Vulkan APIs in this extension are included in core Vulkan 1.2, with the EXT
// suffix omitted.
// However, if Vulkan 1.2 is supported and this extension is not, the
// scalarBlockLayout capability is optional.
// External interactions defined by this extension, such as SPIR-V token names,
// retain their original names.
// The original Vulkan API names are still available as aliases of the core
// functionality.
//
// Promotion to Vulkan 1.4:
//
// If Vulkan 1.4 is supported, support for the scalarBlockLayout
// capability is required.
//
// Version History:
//
//   - Revision 1, 2018-11-14 (Tobias Hector)
//   - Initial draft
package ext_scalar_block_layout
