// Code generated by vk-gen. DO NOT EDIT.

package ext_line_rasterization

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdSetLineStippleEXT uintptr
)

// Init resolves and initializes all VK_EXT_line_rasterization extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdSetLineStippleEXT = vulkan.GetInstanceProcAddr(instance, "vkCmdSetLineStippleEXT")
}

// CmdSetLineStippleEXT executes vkCmdSetLineStippleEXT.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetLineStippleEXT.html
func CmdSetLineStippleEXT() {
	vulkan.CallSyscall(pfnCmdSetLineStippleEXT)
}
