// Code generated by vk-gen. DO NOT EDIT.

// Package ext_mesh_shader provides bindings for the VK_EXT_mesh_shader extension.
// Author: EXT
// Contact: Christoph Kubisch @pixeljetstream
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2022-01-20
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     https://github.com/KhronosGroup/GLSL/blob/main/extensions/ext/GLSLEXTmeshshader.txt[GLSLEXTmeshshader]
//   - Interacts with Vulkan 1.1
//   - Interacts with VKKHRmultiview
//   - Interacts with VKKHRfragmentshadingrate
//
// Contributors:
//   - Christoph Kubisch, NVIDIA
//   - Pat Brown, NVIDIA
//   - Jeff Bolz, NVIDIA
//   - Daniel Koch, NVIDIA
//   - Piers Daniell, NVIDIA
//   - Pierre Boudier, NVIDIA
//   - Patrick Mours, NVIDIA
//   - David Zhao Akeley, NVIDIA
//   - Kedarnath Thangudu, NVIDIA
//   - Timur Kristóf, Valve
//   - Hans-Kristian Arntzen, Valve
//   - Philip Rebohle, Valve
//   - Mike Blumenkrantz, Valve
//   - Slawomir Grajewski, Intel
//   - Michal Pietrasiuk, Intel
//   - Mariusz Merecki, Intel
//   - Tom Olson, ARM
//   - Jan-Harald Fredriksen, ARM
//   - Sandeep Kakarlapudi, ARM
//   - Ruihao Zhang, QUALCOMM
//   - Ricardo Garcia, Igalia, S.L.
//   - Tobias Hector, AMD
//   - Stu Smith, AMD
//
// Description:
//
// This extension provides a new mechanism allowing applications to generate
// collections of geometric primitives via programmable mesh shading.
// It is an alternative to the existing programmable primitive shading
// pipeline, which relied on generating input primitives by a fixed function
// assembler as well as fixed function vertex fetch.
//
// This extension also adds support for the following SPIR-V extension in
// Vulkan:
//
//   - {spirv}/EXT/SPVEXTmeshshader.html[SPVEXTmeshshader]
//
// New or Modified Built-In Variables:
//
//   - CullPrimitiveEXT
//   - PrimitivePointIndicesEXT
//   - PrimitiveLineIndicesEXT
//   - PrimitiveTriangleIndicesEXT
//   - (modified)Position
//   - (modified)PointSize
//   - (modified)ClipDistance
//   - (modified)CullDistance
//   - (modified)PrimitiveId
//   - (modified)Layer
//   - (modified)ViewportIndex
//   - (modified)NumWorkgroups
//   - (modified)WorkgroupSize
//   - (modified)WorkgroupId
//   - (modified)LocalInvocationId
//   - (modified)GlobalInvocationId
//   - (modified)LocalInvocationIndex
//   - (modified)NumSubgroups
//   - (modified)SubgroupId
//   - (modified)DrawIndex
//   - (modified)PrimitiveShadingRateKHR
//   - (modified)ViewIndex
//
// New SPIR-V Capability:
//
//   - MeshShadingEXT
//
// Version History:
//
//   - Revision 1, 2022-03-08 (Christoph Kubisch, Daniel Koch, Patrick Mours)
//   - Initial revision
package ext_mesh_shader
