// Code generated by vk-gen. DO NOT EDIT.

package khr_maintenance5

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdBindIndexBuffer2KHR             uintptr
	pfnGetDeviceImageSubresourceLayoutKHR uintptr
	pfnGetImageSubresourceLayout2KHR      uintptr
	pfnGetRenderingAreaGranularityKHR     uintptr
)

// Init resolves and initializes all VK_KHR_maintenance5 extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdBindIndexBuffer2KHR = vulkan.GetInstanceProcAddr(instance, "vkCmdBindIndexBuffer2KHR")
	pfnGetDeviceImageSubresourceLayoutKHR = vulkan.GetInstanceProcAddr(instance, "vkGetDeviceImageSubresourceLayoutKHR")
	pfnGetImageSubresourceLayout2KHR = vulkan.GetInstanceProcAddr(instance, "vkGetImageSubresourceLayout2KHR")
	pfnGetRenderingAreaGranularityKHR = vulkan.GetInstanceProcAddr(instance, "vkGetRenderingAreaGranularityKHR")
}

// CmdBindIndexBuffer2KHR executes vkCmdBindIndexBuffer2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBindIndexBuffer2KHR.html
func CmdBindIndexBuffer2KHR() {
	vulkan.CallSyscall(pfnCmdBindIndexBuffer2KHR)
}

// GetDeviceImageSubresourceLayoutKHR executes vkGetDeviceImageSubresourceLayoutKHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetDeviceImageSubresourceLayoutKHR.html
func GetDeviceImageSubresourceLayoutKHR() {
	vulkan.CallSyscall(pfnGetDeviceImageSubresourceLayoutKHR)
}

// GetImageSubresourceLayout2KHR executes vkGetImageSubresourceLayout2KHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetImageSubresourceLayout2KHR.html
func GetImageSubresourceLayout2KHR() {
	vulkan.CallSyscall(pfnGetImageSubresourceLayout2KHR)
}

// GetRenderingAreaGranularityKHR executes vkGetRenderingAreaGranularityKHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetRenderingAreaGranularityKHR.html
func GetRenderingAreaGranularityKHR() {
	vulkan.CallSyscall(pfnGetRenderingAreaGranularityKHR)
}
