// Code generated by vk-gen. DO NOT EDIT.

// Package khr_unified_image_layouts provides bindings for the VK_KHR_unified_image_layouts extension.
// Author: KHR
// Contact: Shahbaz Youssefi @syoussefi
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2024-10-15
//
// Interactions and External Dependencies:
//   - This extension interacts with
//     VKEXTattachmentfeedbackloop_layout
//   - This extension interacts with VKKHRvideodecodequeue
//   - This extension interacts with VKKHRvideoencodequeue
//   - This extension interacts with
//     VKKHRvideoencodequantization_map
//
// Contributors:
//   - Ahmed Abdelkhalek, AMD
//   - Tobias Hector, AMD
//   - Jan-Harald Fredriksen, ARM
//   - Ting Wei, ARM
//   - Faith Ekstrand, Collabora
//   - Lina Versace, Google
//   - Shahbaz Youssefi, Google
//   - James Fitzpatrick, Imagination
//   - Daniel Story, Nintendo
//   - James Jones, NVIDIA
//   - Jeff Juliano, NVIDIA
//   - Piers Daniell, NVIDIA
//   - Tony Zlatinski, NVIDIA
//   - Matthew Netsch, Qualcomm
//   - Patrick Boyle, Qualcomm
//   - Daniel Rakos, RasterGrid
//   - Ralph Potter, Samsung
//   - Hans-Kristian Arntzen, VALVE
//   - Samuel Pitoiset, VALVE
//
// Description:
//
// This extension significantly simplifies synchronization in Vulkan by
// removing the need for image layout transitions in most cases.
// In particular, it guarantees that using the VKIMAGELAYOUT_GENERAL layout
// everywhere possible is just as efficient as using the other layouts.
//
// Version History:
//
//   - Revision 1, 2024-10-15 (Shahbaz Youssefi)
//   - Initial revision
package khr_unified_image_layouts
