// Code generated by vk-gen. DO NOT EDIT.

// Package ext_depth_range_unrestricted provides bindings for the VK_EXT_depth_range_unrestricted extension.
// Author: NV
// Contact: Piers Daniell @pdaniell-nv
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2017-06-22
//
// Contributors:
//   - Daniel Koch, NVIDIA
//   - Jeff Bolz, NVIDIA
//
// Description:
//
// This extension removes the VkViewport minDepth and
// maxDepth restrictions that the values must be between 0.0 and 1.0,
// inclusive.
// It also removes the same restriction on
// VkPipelineDepthStencilStateCreateInfo minDepthBounds and
// maxDepthBounds.
// Finally it removes the restriction on the depth value in
// VkClearDepthStencilValue.
//
// Issues:
//
// 1) How do VkViewport minDepth and maxDepth values outside
// of the 0.0 to 1.0 range interact with
// Primitive Clipping?
//
// RESOLVED:
// Clipping>> still applies.
// If depth clamping is disabled the depth values are still clipped to [eq]#0
// {leq} z~c~ {leq} w~c~# before the viewport transform.
// If depth clamping is enabled the above equation is ignored and the depth
// values are instead clamped to the VkViewport minDepth and
// maxDepth values, which in the case of this extension can be outside of
// the 0.0 to 1.0 range.
//
// 2) What happens if a resulting depth fragment is outside of the 0.0 to
// 1.0 range and the depth buffer is fixed-point rather than floating-point?
//
// RESOLVED:
// fragment shaders replace depth values, for example), and this extension does
// not change the behavior, which is defined in the <<fragops-depth,Depth
// Test>> section of the Fragment Operations chapter.
//
// Version History:
//
//   - Revision 1, 2017-06-22 (Piers Daniell)
//   - Internal revisions
package ext_depth_range_unrestricted
