// Code generated by vk-gen. DO NOT EDIT.

package nv_external_memory_capabilities

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetPhysicalDeviceExternalImageFormatPropertiesNV uintptr
)

// Init resolves and initializes all VK_NV_external_memory_capabilities extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetPhysicalDeviceExternalImageFormatPropertiesNV = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalImageFormatPropertiesNV")
}

// GetPhysicalDeviceExternalImageFormatPropertiesNV - Determine image capabilities compatible with external memory handle types (vkGetPhysicalDeviceExternalImageFormatPropertiesNV).
// Parameters:
//   - physicalDevice: is the physical device from which to query the image capabilities
//   - format: is the image format, corresponding to VkImageCreateInfo::pname:format.
//   - typ: is the image type, corresponding to VkImageCreateInfo::pname:imageType.
//   - tiling: is the image tiling, corresponding to VkImageCreateInfo::pname:tiling.
//   - usage: is the intended usage of the image, corresponding to VkImageCreateInfo::pname:usage.
//   - flags: is a bitmask describing additional parameters of the image, corresponding to VkImageCreateInfo::pname:flags.
//   - externalHandleType: is either one of the bits from VkExternalMemoryHandleTypeFlagBitsNV, or 0.
//   - externalImageFormatProperties: is a pointer to a VkExternalImageFormatPropertiesNV structure in which capabilities are returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_FORMAT_NOT_SUPPORTED, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceExternalImageFormatPropertiesNV.html
func GetPhysicalDeviceExternalImageFormatPropertiesNV(physicalDevice vulkan.PhysicalDevice, format vulkan.Format, typ vulkan.ImageType, tiling vulkan.ImageTiling, usage vulkan.ImageUsageFlags, flags vulkan.ImageCreateFlags, externalHandleType vulkan.ExternalMemoryHandleTypeFlagsNV) (externalImageFormatProperties vulkan.ExternalImageFormatPropertiesNV, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnGetPhysicalDeviceExternalImageFormatPropertiesNV, uintptr(physicalDevice), uintptr(format), uintptr(typ), uintptr(tiling), uintptr(usage), uintptr(flags), uintptr(externalHandleType), uintptr(unsafe.Pointer(&externalImageFormatProperties)))
	return externalImageFormatProperties, vulkan.Result(r1)
}
