// Code generated by vk-gen. DO NOT EDIT.

// Package khr_synchronization2 provides bindings for the VK_KHR_synchronization2 extension.
// Author: KHR
// Contact: Tobias Hector @tobski
// Promoted to: VK_VERSION_1_3
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2020-12-03
//
// Interactions and External Dependencies:
//   - Interacts with VKKHRcreate_renderpass2
//
// Contributors:
//   - Tobias Hector
//
// Description:
//
// This extension modifies the original core synchronization APIs to simplify
// the interface and improve usability of these APIs.
// It also adds new pipeline stage and access flag types that extend into the
// 64-bit range, as we have run out within the 32-bit range.
// The new flags are identical to the old values within the 32-bit range, with
// new stages and bits beyond that.
//
// Pipeline stages and access flags are now specified together in memory
// barrier structures, making the connection between the two more obvious.
// Additionally, scoping the pipeline stages into the barrier structs allows
// the use of the MEMORYREAD and MEMORYWRITE flags without
// sacrificing precision.
// The per-stage access flags should be used to disambiguate specific accesses
// in a given stage or set of stages - for instance, between uniform reads and
// sampling operations.
//
// Layout transitions have been simplified as well; rather than requiring a
// different set of layouts for depth/stencil/color attachments, there are
// generic VKIMAGELAYOUTATTACHMENTOPTIMAL_KHR and
// VKIMAGELAYOUTREADONLYOPTIMALKHR layouts which are contextually
// applied based on the image format.
// For example, for a depth format image,
// VKIMAGELAYOUTREADONLYOPTIMALKHR is equivalent to
// VKIMAGELAYOUTDEPTHREADONLYOPTIMAL_KHR.
// VKIMAGELAYOUTREADONLYOPTIMALKHR also functionally replaces
// VKIMAGELAYOUTSHADERREADONLYOPTIMAL.
//
// Events are now more efficient, because they include memory dependency
// information when you set them on the device.
// Previously, this information was only known when waiting on an event, so the
// dependencies could not be satisfied until the wait occurred.
// That sometimes meant stalling the pipeline when the wait occurred.
// The new API provides enough information for implementations to satisfy these
// dependencies in parallel with other tasks.
//
// Queue submission has been changed to wrap command buffers and semaphores in
// extensible structures, which incorporate changes from Vulkan 1.1,
// VKKHRdevicegroup, and VKKHRtimelinesemaphore.
// This also adds a pipeline stage to the semaphore signal operation, mirroring
// the existing pipeline stage specification for wait operations.
//
// Other miscellaneous changes include:
//
//   - Events can now be specified as interacting only with the device,
//     allowing more efficient access to the underlying object.
//   - Image memory barriers that do not perform an image layout transition can
//     be specified by setting oldLayout equal to newLayout.
//   - E.g. the old and new layout can both be set to
//     VKIMAGELAYOUT_UNDEFINED, without discarding data in the image.
//   - Queue family ownership transfer parameters are simplified in some cases.
//   - Extensions with commands or functions with a VkPipelineStageFlags
//     or VkPipelineStageFlagBits parameter have had those APIs replaced
//     with equivalents using VkPipelineStageFlags2KHR.
//   - The new event and barrier interfaces are now more extensible for future
//     changes.
//   - Relevant pipeline stage masks can now be specified as empty with the new
//     VKPIPELINESTAGENONEKHR and VKPIPELINESTAGE2NONE_KHR
//     values.
//   - VkMemoryBarrier2KHR can be chained to VkSubpassDependency2,
//     overriding the original 32-bit stage and access masks.
//
// Promotion to Vulkan 1.3:
//
// Vulkan APIs in this extension are included in core Vulkan 1.3, with the KHR
// suffix omitted.
// External interactions defined by this extension, such as SPIR-V token names,
// retain their original names.
// The original Vulkan API names are still available as aliases of the core
// functionality.
//
// Examples:
//
// See
// https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples
//
// Version History:
//
//   - Revision 1, 2020-12-03 (Tobias Hector)
//   - Internal revisions
package khr_synchronization2
