// Code generated by vk-gen. DO NOT EDIT.

// Package amd_shader_trinary_minmax provides bindings for the VK_AMD_shader_trinary_minmax extension.
// Author: AMD
// Contact: Qun Lin @linqun
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2016-05-10
//
// IP Status:
//
//	No known IP claims.
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLregistry}/AMD/AMDshadertrinaryminmax.txt[GLAMDshadertrinary_minmax]
//
// Contributors:
//   - Matthaeus G. Chajdas, AMD
//   - Qun Lin, AMD
//   - Daniel Rakos, AMD
//   - Graham Sellers, AMD
//   - Rex Xu, AMD
//
// Description:
//
// This extension adds support for the following SPIR-V extension in Vulkan:
//
//   - {spirv}/AMD/SPVAMDshadertrinaryminmax.html[SPVAMDshadertrinaryminmax]
//
// Version History:
//
//   - Revision 1, 2016-05-10 (Daniel Rakos)
//   - Initial draft
package amd_shader_trinary_minmax
