// Code generated by vk-gen. DO NOT EDIT.

// Package khr_video_encode_av1 provides bindings for the VK_KHR_video_encode_av1 extension.
// Author: KHR
// Contact: Daniel Rakos @aqnuep
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2024-09-23
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Ahmed Abdelkhalek, AMD
//   - Benjamin Cheng, AMD
//   - Ho Hin Lau, AMD
//   - Lynne Iribarren, Independent
//   - David Airlie, Red Hat, Inc.
//   - Ping Liu, Intel
//   - Srinath Kumarapuram, NVIDIA
//   - Vassili Nikolaev, NVIDIA
//   - Tony Zlatinski, NVIDIA
//   - Konda Raju, NVIDIA
//   - Charlie Turner, Igalia
//   - Daniel Almeida, Collabora
//   - Nicolas Dufresne, Collabora
//   - Daniel Rakos, RasterGrid
//
// Description:
//
// This extension builds upon the VKKHRvideoencodequeue extension
// by adding support for encoding elementary video stream sequences compliant
// with the AV1 video compression standard.
//
// Version History:
//
//   - Revision 1, 2024-09-23 (Daniel Rakos)
//   - Internal revisions
package khr_video_encode_av1
