// Code generated by vk-gen. DO NOT EDIT.

package intel_performance_query

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Commands holds resolved procedure addresses for an instance and/or device.
type Commands struct {
	pfnAcquirePerformanceConfigurationINTEL  uintptr
	pfnCmdSetPerformanceMarkerINTEL          uintptr
	pfnCmdSetPerformanceOverrideINTEL        uintptr
	pfnCmdSetPerformanceStreamMarkerINTEL    uintptr
	pfnGetPerformanceParameterINTEL          uintptr
	pfnInitializePerformanceApiINTEL         uintptr
	pfnQueueSetPerformanceConfigurationINTEL uintptr
	pfnReleasePerformanceConfigurationINTEL  uintptr
	pfnUninitializePerformanceApiINTEL       uintptr
}

// Default procedure addresses resolved by Init
var (
	pfnAcquirePerformanceConfigurationINTEL  uintptr
	pfnCmdSetPerformanceMarkerINTEL          uintptr
	pfnCmdSetPerformanceOverrideINTEL        uintptr
	pfnCmdSetPerformanceStreamMarkerINTEL    uintptr
	pfnGetPerformanceParameterINTEL          uintptr
	pfnInitializePerformanceApiINTEL         uintptr
	pfnQueueSetPerformanceConfigurationINTEL uintptr
	pfnReleasePerformanceConfigurationINTEL  uintptr
	pfnUninitializePerformanceApiINTEL       uintptr
)

// Init resolves and initializes all VK_INTEL_performance_query extension procedure addresses, setting default globals and returning a Commands instance for multi-device support.
func Init(instance vulkan.Instance, device vulkan.Device) *Commands {
	cmds := &Commands{
		pfnAcquirePerformanceConfigurationINTEL:  vulkan.GetDeviceProcAddr(device, "vkAcquirePerformanceConfigurationINTEL"),
		pfnCmdSetPerformanceMarkerINTEL:          vulkan.GetDeviceProcAddr(device, "vkCmdSetPerformanceMarkerINTEL"),
		pfnCmdSetPerformanceOverrideINTEL:        vulkan.GetDeviceProcAddr(device, "vkCmdSetPerformanceOverrideINTEL"),
		pfnCmdSetPerformanceStreamMarkerINTEL:    vulkan.GetDeviceProcAddr(device, "vkCmdSetPerformanceStreamMarkerINTEL"),
		pfnGetPerformanceParameterINTEL:          vulkan.GetDeviceProcAddr(device, "vkGetPerformanceParameterINTEL"),
		pfnInitializePerformanceApiINTEL:         vulkan.GetDeviceProcAddr(device, "vkInitializePerformanceApiINTEL"),
		pfnQueueSetPerformanceConfigurationINTEL: vulkan.GetDeviceProcAddr(device, "vkQueueSetPerformanceConfigurationINTEL"),
		pfnReleasePerformanceConfigurationINTEL:  vulkan.GetDeviceProcAddr(device, "vkReleasePerformanceConfigurationINTEL"),
		pfnUninitializePerformanceApiINTEL:       vulkan.GetDeviceProcAddr(device, "vkUninitializePerformanceApiINTEL"),
	}
	pfnAcquirePerformanceConfigurationINTEL = cmds.pfnAcquirePerformanceConfigurationINTEL
	pfnCmdSetPerformanceMarkerINTEL = cmds.pfnCmdSetPerformanceMarkerINTEL
	pfnCmdSetPerformanceOverrideINTEL = cmds.pfnCmdSetPerformanceOverrideINTEL
	pfnCmdSetPerformanceStreamMarkerINTEL = cmds.pfnCmdSetPerformanceStreamMarkerINTEL
	pfnGetPerformanceParameterINTEL = cmds.pfnGetPerformanceParameterINTEL
	pfnInitializePerformanceApiINTEL = cmds.pfnInitializePerformanceApiINTEL
	pfnQueueSetPerformanceConfigurationINTEL = cmds.pfnQueueSetPerformanceConfigurationINTEL
	pfnReleasePerformanceConfigurationINTEL = cmds.pfnReleasePerformanceConfigurationINTEL
	pfnUninitializePerformanceApiINTEL = cmds.pfnUninitializePerformanceApiINTEL
	return cmds
}

// AcquirePerformanceConfigurationINTEL - Acquire the performance query capability (vkAcquirePerformanceConfigurationINTEL).
// Parameters:
//   - device: is the logical device that the performance query commands will be submitted to.
//   - acquireInfo: is a pointer to a VkPerformanceConfigurationAcquireInfoINTEL structure, specifying the performance configuration to acquire.
//   - configuration: is a pointer to a VkPerformanceConfigurationINTEL handle in which the resulting configuration object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkAcquirePerformanceConfigurationINTEL.html
func (c *Commands) AcquirePerformanceConfigurationINTEL(device vulkan.Device, acquireInfo *vulkan.PerformanceConfigurationAcquireInfoINTEL) (configuration vulkan.PerformanceConfigurationINTEL, result vulkan.Result) {
	c_acquireInfo := acquireInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnAcquirePerformanceConfigurationINTEL, uintptr(device), uintptr(unsafe.Pointer(c_acquireInfo)), uintptr(unsafe.Pointer(&configuration)))
	return configuration, vulkan.Result(r1)
}

func AcquirePerformanceConfigurationINTEL(device vulkan.Device, acquireInfo *vulkan.PerformanceConfigurationAcquireInfoINTEL) (configuration vulkan.PerformanceConfigurationINTEL, result vulkan.Result) {
	c_acquireInfo := acquireInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnAcquirePerformanceConfigurationINTEL, uintptr(device), uintptr(unsafe.Pointer(c_acquireInfo)), uintptr(unsafe.Pointer(&configuration)))
	return configuration, vulkan.Result(r1)
}

// CmdSetPerformanceMarkerINTEL - Markers (vkCmdSetPerformanceMarkerINTEL).
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetPerformanceMarkerINTEL.html
func (c *Commands) CmdSetPerformanceMarkerINTEL(commandBuffer vulkan.CommandBuffer, markerInfo *vulkan.PerformanceMarkerInfoINTEL) (result vulkan.Result) {
	c_markerInfo := markerInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnCmdSetPerformanceMarkerINTEL, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_markerInfo)))
	return vulkan.Result(r1)
}

func CmdSetPerformanceMarkerINTEL(commandBuffer vulkan.CommandBuffer, markerInfo *vulkan.PerformanceMarkerInfoINTEL) (result vulkan.Result) {
	c_markerInfo := markerInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCmdSetPerformanceMarkerINTEL, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_markerInfo)))
	return vulkan.Result(r1)
}

// CmdSetPerformanceOverrideINTEL - Performance override settings (vkCmdSetPerformanceOverrideINTEL).
// Parameters:
//   - commandBuffer: is the command buffer where the override takes place.
//   - overrideInfo: is a pointer to a VkPerformanceOverrideInfoINTEL structure selecting the parameter to override.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetPerformanceOverrideINTEL.html
func (c *Commands) CmdSetPerformanceOverrideINTEL(commandBuffer vulkan.CommandBuffer, overrideInfo *vulkan.PerformanceOverrideInfoINTEL) (result vulkan.Result) {
	c_overrideInfo := overrideInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnCmdSetPerformanceOverrideINTEL, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_overrideInfo)))
	return vulkan.Result(r1)
}

func CmdSetPerformanceOverrideINTEL(commandBuffer vulkan.CommandBuffer, overrideInfo *vulkan.PerformanceOverrideInfoINTEL) (result vulkan.Result) {
	c_overrideInfo := overrideInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCmdSetPerformanceOverrideINTEL, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_overrideInfo)))
	return vulkan.Result(r1)
}

// CmdSetPerformanceStreamMarkerINTEL - Markers (vkCmdSetPerformanceStreamMarkerINTEL).
// Parameters:
//   - commandBuffer: is a VkCommandBuffer into which a stream marker is added.
//   - markerInfo: is a pointer to a VkPerformanceStreamMarkerInfoINTEL structure describing the marker to insert.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetPerformanceStreamMarkerINTEL.html
func (c *Commands) CmdSetPerformanceStreamMarkerINTEL(commandBuffer vulkan.CommandBuffer, markerInfo *vulkan.PerformanceStreamMarkerInfoINTEL) (result vulkan.Result) {
	c_markerInfo := markerInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnCmdSetPerformanceStreamMarkerINTEL, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_markerInfo)))
	return vulkan.Result(r1)
}

func CmdSetPerformanceStreamMarkerINTEL(commandBuffer vulkan.CommandBuffer, markerInfo *vulkan.PerformanceStreamMarkerInfoINTEL) (result vulkan.Result) {
	c_markerInfo := markerInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCmdSetPerformanceStreamMarkerINTEL, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_markerInfo)))
	return vulkan.Result(r1)
}

// GetPerformanceParameterINTEL - Query performance capabilities of the device (vkGetPerformanceParameterINTEL).
// Parameters:
//   - device: is the logical device to query.
//   - parameter: is the parameter to query.
//   - value: is a pointer to a VkPerformanceValueINTEL structure in which the type and value of the parameter are returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPerformanceParameterINTEL.html
func (c *Commands) GetPerformanceParameterINTEL(device vulkan.Device, parameter vulkan.PerformanceParameterTypeINTEL) (value vulkan.PerformanceValueINTEL, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(c.pfnGetPerformanceParameterINTEL, uintptr(device), uintptr(parameter), uintptr(unsafe.Pointer(&value)))
	return value, vulkan.Result(r1)
}

func GetPerformanceParameterINTEL(device vulkan.Device, parameter vulkan.PerformanceParameterTypeINTEL) (value vulkan.PerformanceValueINTEL, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnGetPerformanceParameterINTEL, uintptr(device), uintptr(parameter), uintptr(unsafe.Pointer(&value)))
	return value, vulkan.Result(r1)
}

// InitializePerformanceApiINTEL - Initialize a device for performance queries (vkInitializePerformanceApiINTEL).
// Parameters:
//   - device: is the logical device used for the queries.
//   - initializeInfo: is a pointer to a VkInitializePerformanceApiInfoINTEL structure specifying initialization parameters.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkInitializePerformanceApiINTEL.html
func (c *Commands) InitializePerformanceApiINTEL(device vulkan.Device, initializeInfo *vulkan.InitializePerformanceApiInfoINTEL) (result vulkan.Result) {
	c_initializeInfo := initializeInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnInitializePerformanceApiINTEL, uintptr(device), uintptr(unsafe.Pointer(c_initializeInfo)))
	return vulkan.Result(r1)
}

func InitializePerformanceApiINTEL(device vulkan.Device, initializeInfo *vulkan.InitializePerformanceApiInfoINTEL) (result vulkan.Result) {
	c_initializeInfo := initializeInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnInitializePerformanceApiINTEL, uintptr(device), uintptr(unsafe.Pointer(c_initializeInfo)))
	return vulkan.Result(r1)
}

// QueueSetPerformanceConfigurationINTEL - Set a performance query (vkQueueSetPerformanceConfigurationINTEL).
// Parameters:
//   - queue: is the queue on which the configuration will be used.
//   - configuration: is the configuration to use.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkQueueSetPerformanceConfigurationINTEL.html
func (c *Commands) QueueSetPerformanceConfigurationINTEL(queue vulkan.Queue, configuration vulkan.PerformanceConfigurationINTEL) (result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(c.pfnQueueSetPerformanceConfigurationINTEL, uintptr(queue), uintptr(configuration))
	return vulkan.Result(r1)
}

func QueueSetPerformanceConfigurationINTEL(queue vulkan.Queue, configuration vulkan.PerformanceConfigurationINTEL) (result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnQueueSetPerformanceConfigurationINTEL, uintptr(queue), uintptr(configuration))
	return vulkan.Result(r1)
}

// ReleasePerformanceConfigurationINTEL - Release a configuration to capture performance data (vkReleasePerformanceConfigurationINTEL).
// Parameters:
//   - device: is the device associated to the configuration object to release.
//   - configuration: is the configuration object to release.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkReleasePerformanceConfigurationINTEL.html
func (c *Commands) ReleasePerformanceConfigurationINTEL(device vulkan.Device, configuration vulkan.PerformanceConfigurationINTEL) (result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(c.pfnReleasePerformanceConfigurationINTEL, uintptr(device), uintptr(configuration))
	return vulkan.Result(r1)
}

func ReleasePerformanceConfigurationINTEL(device vulkan.Device, configuration vulkan.PerformanceConfigurationINTEL) (result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnReleasePerformanceConfigurationINTEL, uintptr(device), uintptr(configuration))
	return vulkan.Result(r1)
}

// UninitializePerformanceApiINTEL - Uninitialize a device for performance queries (vkUninitializePerformanceApiINTEL).
// Parameters:
//   - device: is the logical device used for the queries.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkUninitializePerformanceApiINTEL.html
func (c *Commands) UninitializePerformanceApiINTEL(device vulkan.Device) {
	vulkan.CallSyscall(c.pfnUninitializePerformanceApiINTEL, uintptr(device))
}

func UninitializePerformanceApiINTEL(device vulkan.Device) {
	vulkan.CallSyscall(pfnUninitializePerformanceApiINTEL, uintptr(device))
}
