// Code generated by vk-gen. DO NOT EDIT.

// Package khr_video_decode_vp9 provides bindings for the VK_KHR_video_decode_vp9 extension.
// Author: KHR
// Contact: Ahmed Abdelkhalek @aabdelkh
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2025-04-11
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Ahmed Abdelkhalek, AMD
//   - Benjamin Cheng, AMD
//   - Lynne Iribarren, Independent
//   - David Airlie, Red Hat, Inc.
//   - Ping Liu, Intel
//   - Srinath Kumarapuram, NVIDIA
//   - Vassili Nikolaev, NVIDIA
//   - Tony Zlatinski, NVIDIA
//   - Konda Raju, NVIDIA
//   - Daniel Almeida, Collabora
//   - Nicolas Dufresne, Collabora
//   - Daniel Rakos, RasterGrid
//
// Description:
//
// This extension builds upon the VKKHRvideodecodequeue extension
// by adding support for decoding elementary video stream sequences compliant
// with the VP9 video compression standard.
//
// Version History:
//
//   - Revision 1, 2025-04-11 (Daniel Rakos)
//   - Internal revisions
package khr_video_decode_vp9
