// Code generated by vk-gen. DO NOT EDIT.

package ext_fragment_density_map_offset

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdEndRendering2EXT uintptr
)

// Init resolves and initializes all VK_EXT_fragment_density_map_offset extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdEndRendering2EXT = vulkan.GetInstanceProcAddr(instance, "vkCmdEndRendering2EXT")
}

// CmdEndRendering2EXT executes vkCmdEndRendering2EXT.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdEndRendering2EXT.html
func CmdEndRendering2EXT() {
	vulkan.CallSyscall(pfnCmdEndRendering2EXT)
}
