// Code generated by vk-gen. DO NOT EDIT.

// Package ext_ray_tracing_invocation_reorder provides bindings for the VK_EXT_ray_tracing_invocation_reorder extension.
// Author: EXT
// Contact: Eric Werness @ewerness-nv
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2026-04-02
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLSLregistry}/ext/GLSLEXTshaderinvocationreorder.txt[GLEXTshaderinvocationreorder]
//
// Contributors:
//   - Eric Werness, NVIDIA
//   - Ashwin Lele, NVIDIA
//   - Daniel Koch, NVIDIA
//   - Vikram Kushwaha, NVIDIA
//   - Piers Daniell, NVIDIA
//   - Stu Smith, AMD
//   - Aaron Hagan, AMD
//   - Tyler Nowicki, AMD
//   - Sebastian Neubauer, AMD
//   - Radoslaw Drabinski, Intel
//   - Sven Woop, Intel
//   - Aleksandra Krstic, QUALCOMM
//   - Andrew Garrard, Imagination Technologies
//   - Mathieu Robart, Arm Limited
//   - Tom Olson, Khronos
//   - Ralph Potter, Samsung Electronics
//   - Antonio Caggiano, LunarG
//
// Description:
//
// The ray tracing pipeline API provides some ability to reorder for locality,
// but it is useful to have more control over how the reordering happens and
// what information is included in the reordering.
// The shader API provides a hit object to contain result information from the
// hit which can be used as part of the explicit sorting plus options that
// contain an integer for hint bits to use to add more coherency.
//
// Version History:
//
//   - Revision 2, 2026-04-02 (Vikram Kushwaha)
//   - Add hitKind overload for hitObjectRecordFromQueryEXT in
//     GLEXTshaderinvocationreorder, and fix for
//     https://github.com/KhronosGroup/SPIRV-Registry/issues/373
//   - Revision 1, 2025-11-12 (Eric Werness)
//   - Internal development - forked from NV
package ext_ray_tracing_invocation_reorder
