// Code generated by vk-gen. DO NOT EDIT.

package ext_sample_locations

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdSetSampleLocationsEXT                  uintptr
	pfnGetPhysicalDeviceMultisamplePropertiesEXT uintptr
)

// Init resolves and initializes all VK_EXT_sample_locations extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdSetSampleLocationsEXT = vulkan.GetDeviceProcAddr(device, "vkCmdSetSampleLocationsEXT")
	pfnGetPhysicalDeviceMultisamplePropertiesEXT = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceMultisamplePropertiesEXT")
}

// CmdSetSampleLocationsEXT - Set sample locations dynamically for a command buffer (vkCmdSetSampleLocationsEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - sampleLocationsInfo: is the sample locations state to set.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetSampleLocationsEXT.html
func CmdSetSampleLocationsEXT(commandBuffer vulkan.CommandBuffer, sampleLocationsInfo *vulkan.SampleLocationsInfoEXT) {
	c_sampleLocationsInfo := sampleLocationsInfo.Raw()
	vulkan.CallSyscall(pfnCmdSetSampleLocationsEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_sampleLocationsInfo)))
}

// GetPhysicalDeviceMultisamplePropertiesEXT - Report sample count specific multisampling capabilities of a physical device (vkGetPhysicalDeviceMultisamplePropertiesEXT).
// Parameters:
//   - physicalDevice: is the physical device from which to query the additional multisampling capabilities.
//   - samples: is a VkSampleCountFlagBits value specifying the sample count to query capabilities for.
//   - multisampleProperties: is a pointer to a VkMultisamplePropertiesEXT structure in which information about additional multisampling capabilities specific to the sample count is returned.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceMultisamplePropertiesEXT.html
func GetPhysicalDeviceMultisamplePropertiesEXT(physicalDevice vulkan.PhysicalDevice, samples vulkan.SampleCountFlagBits) (multisampleProperties vulkan.MultisamplePropertiesEXT) {
	vulkan.CallSyscall(pfnGetPhysicalDeviceMultisamplePropertiesEXT, uintptr(physicalDevice), uintptr(samples), uintptr(unsafe.Pointer(&multisampleProperties)))
	return multisampleProperties
}
