// Code generated by vk-gen. DO NOT EDIT.

// Package khr_shared_presentable_image provides bindings for the VK_KHR_shared_presentable_image extension.
// Author: KHR
// Contact: Alon Or-bach @alonorbach
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2017-03-20
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Alon Or-bach, Samsung Electronics
//   - Ian Elliott, Google
//   - Jesse Hall, Google
//   - Pablo Ceballos, Google
//   - Chris Forbes, Google
//   - Jeff Juliano, NVIDIA
//   - James Jones, NVIDIA
//   - Daniel Rakos, AMD
//   - Tobias Hector, Imagination Technologies
//   - Graham Connor, Imagination Technologies
//   - Michael Worcester, Imagination Technologies
//   - Cass Everitt, Oculus
//   - Johannes Van Waveren, Oculus
//
// Description:
//
// This extension extends VKKHRswapchain to enable creation of a
// shared presentable image.
// This allows the application to use the image while the presention engine is
// accessing it, in order to reduce the latency between rendering and
// presentation.
//
// Issues:
//
// 1) Should we allow a Vulkan WSI swapchain to toggle between normal usage and
// shared presentation usage?
//
// RESOLVED:
// WSI swapchains are typically recreated with new properties instead of having
// their properties changed.
// This can also save resources, assuming that fewer images are needed for
// shared presentation, and assuming that most VR applications do not need to
// switch between normal and shared usage.
//
// 2) Should we have a query for determining how the presentation engine
// refresh is triggered?
//
// RESOLVED:
// This is done via which presentation modes a surface supports.
//
// 3) Should the object representing a shared presentable image be an extension
// of a VkSwapchainKHR or a separate object?
//
// RESOLVED:
// and to allow common functionality between shared and normal presentable
// images and swapchains.
//
// 4) What should we call the extension and the new structures it creates?
//
// RESOLVED:
//
// 5) Should the minImageCount and presentMode values of the
// VkSwapchainCreateInfoKHR be ignored, or required to be compatible
// values?
//
// RESOLVED:
// set to either VKPRESENTMODESHAREDDEMANDREFRESHKHR or
// VKPRESENTMODESHAREDCONTINUOUSREFRESHKHR.
//
// 6) What should the layout of the shared presentable image be?
//
// RESOLVED:
// must transition it to the VKIMAGELAYOUTSHAREDPRESENT_KHR layout
// prior to it being used.
// After this initial transition, any image usage that was requested during
// swapchain creation can: be performed on the image without layout transitions
// being performed.
//
// 7) Do we need a new API for the trigger to refresh new content?
//
// RESOLVED:
// will allow combination with other compatible extensions to
// vkQueuePresentKHR.
//
// 8) How should an application detect a VKERROROUTOFDATE_KHR error
// on a swapchain using the VKPRESENTMODESHAREDCONTINUOUSREFRESHKHR
// present mode?
//
// RESOLVED:
// query the status of a swapchain using a shared presentation mode.
//
// 9) What should subsequent calls to vkQueuePresentKHR for
// VKPRESENTMODESHAREDCONTINUOUSREFRESHKHR swapchains be defined to
// do?
//
// RESOLVED:
// content.
//
// 10) Can the ownership of a shared presentable image be transferred to a
// different queue?
//
// RESOLVED:
// It is not possible to transfer ownership of a shared presentable image
// obtained from a swapchain created using VKSHARINGMODE_EXCLUSIVE
// after it has been presented.
//
// 11) How should vkQueueSubmit behave if a command buffer uses an image
// from a VKERROROUTOFDATE_KHR swapchain?
//
// RESOLVED:
// VKERRORDEVICE_LOST error.
//
// 12) Can Vulkan provide any guarantee on the order of rendering, to enable
// beam chasing?
//
// RESOLVED:
// rendering.
//
// Version History:
//
//   - Revision 1, 2017-03-20 (Alon Or-bach)
//   - Internal revisions
package khr_shared_presentable_image
