// Code generated by vk-gen. DO NOT EDIT.

package vulkansc

import (
	"fmt"
	"unsafe"
)

// Basic Vulkan primitive types
type (
	// Bool32 is a Vulkan 32-bit boolean type.
	Bool32 uint32

	// DeviceSize is a Vulkan size type for memory allocations and buffer offsets.
	DeviceSize uint64

	// DeviceAddress is a Vulkan 64-bit device address type.
	DeviceAddress uint64

	// Flags is a 32-bit bitmask type.
	Flags uint32

	// Flags64 is a 64-bit bitmask type.
	Flags64 uint64

	// SampleMask is a 32-bit sample mask type.
	SampleMask uint32

	// RemoteAddressNV is a generic pointer type.
	RemoteAddressNV unsafe.Pointer
)

const (
	True       Bool32 = 1
	False      Bool32 = 0
	NullHandle        = 0
)

// Bool converts Bool32 to Go bool.
func (b Bool32) Bool() bool {
	return b != 0
}

// FromBool converts Go bool to Bool32.
func FromBool(b bool) Bool32 {
	if b {
		return True
	}
	return False
}

// --- Vulkan Handles ---

// AccelerationStructureKHR is a Vulkan VkAccelerationStructureKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureKHR.html
type AccelerationStructureKHR uint64

// IsValid returns true if the AccelerationStructureKHR handle is not NULL.
func (h AccelerationStructureKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h AccelerationStructureKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h AccelerationStructureKHR) String() string {
	return fmt.Sprintf("AccelerationStructureKHR(0x%X)", uint64(h))
}

// AccelerationStructureNV is a Vulkan VkAccelerationStructureNV handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureNV.html
type AccelerationStructureNV uint64

// IsValid returns true if the AccelerationStructureNV handle is not NULL.
func (h AccelerationStructureNV) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h AccelerationStructureNV) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h AccelerationStructureNV) String() string {
	return fmt.Sprintf("AccelerationStructureNV(0x%X)", uint64(h))
}

// Buffer is a Vulkan VkBuffer handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkBuffer.html
type Buffer uint64

// IsValid returns true if the Buffer handle is not NULL.
func (h Buffer) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Buffer) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Buffer) String() string {
	return fmt.Sprintf("Buffer(0x%X)", uint64(h))
}

// BufferCollectionFUCHSIA is a Vulkan VkBufferCollectionFUCHSIA handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkBufferCollectionFUCHSIA.html
type BufferCollectionFUCHSIA uint64

// IsValid returns true if the BufferCollectionFUCHSIA handle is not NULL.
func (h BufferCollectionFUCHSIA) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h BufferCollectionFUCHSIA) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h BufferCollectionFUCHSIA) String() string {
	return fmt.Sprintf("BufferCollectionFUCHSIA(0x%X)", uint64(h))
}

// BufferView is a Vulkan VkBufferView handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkBufferView.html
type BufferView uint64

// IsValid returns true if the BufferView handle is not NULL.
func (h BufferView) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h BufferView) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h BufferView) String() string {
	return fmt.Sprintf("BufferView(0x%X)", uint64(h))
}

// CommandBuffer is a Vulkan VkCommandBuffer handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCommandBuffer.html
type CommandBuffer uintptr

// IsValid returns true if the CommandBuffer handle is not NULL.
func (h CommandBuffer) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uintptr value.
func (h CommandBuffer) Handle() uintptr {
	return uintptr(h)
}

// String formats the handle as a hex string.
func (h CommandBuffer) String() string {
	return fmt.Sprintf("CommandBuffer(0x%X)", uintptr(h))
}

// CommandPool is a Vulkan VkCommandPool handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCommandPool.html
type CommandPool uint64

// IsValid returns true if the CommandPool handle is not NULL.
func (h CommandPool) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h CommandPool) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h CommandPool) String() string {
	return fmt.Sprintf("CommandPool(0x%X)", uint64(h))
}

// CuFunctionNVX is a Vulkan VkCuFunctionNVX handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCuFunctionNVX.html
type CuFunctionNVX uint64

// IsValid returns true if the CuFunctionNVX handle is not NULL.
func (h CuFunctionNVX) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h CuFunctionNVX) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h CuFunctionNVX) String() string {
	return fmt.Sprintf("CuFunctionNVX(0x%X)", uint64(h))
}

// CuModuleNVX is a Vulkan VkCuModuleNVX handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCuModuleNVX.html
type CuModuleNVX uint64

// IsValid returns true if the CuModuleNVX handle is not NULL.
func (h CuModuleNVX) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h CuModuleNVX) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h CuModuleNVX) String() string {
	return fmt.Sprintf("CuModuleNVX(0x%X)", uint64(h))
}

// CudaFunctionNV is a Vulkan VkCudaFunctionNV handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCudaFunctionNV.html
type CudaFunctionNV uint64

// IsValid returns true if the CudaFunctionNV handle is not NULL.
func (h CudaFunctionNV) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h CudaFunctionNV) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h CudaFunctionNV) String() string {
	return fmt.Sprintf("CudaFunctionNV(0x%X)", uint64(h))
}

// CudaModuleNV is a Vulkan VkCudaModuleNV handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCudaModuleNV.html
type CudaModuleNV uint64

// IsValid returns true if the CudaModuleNV handle is not NULL.
func (h CudaModuleNV) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h CudaModuleNV) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h CudaModuleNV) String() string {
	return fmt.Sprintf("CudaModuleNV(0x%X)", uint64(h))
}

// DataGraphPipelineSessionARM is a Vulkan VkDataGraphPipelineSessionARM handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDataGraphPipelineSessionARM.html
type DataGraphPipelineSessionARM uint64

// IsValid returns true if the DataGraphPipelineSessionARM handle is not NULL.
func (h DataGraphPipelineSessionARM) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DataGraphPipelineSessionARM) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DataGraphPipelineSessionARM) String() string {
	return fmt.Sprintf("DataGraphPipelineSessionARM(0x%X)", uint64(h))
}

// DebugReportCallbackEXT is a Vulkan VkDebugReportCallbackEXT handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDebugReportCallbackEXT.html
type DebugReportCallbackEXT uint64

// IsValid returns true if the DebugReportCallbackEXT handle is not NULL.
func (h DebugReportCallbackEXT) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DebugReportCallbackEXT) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DebugReportCallbackEXT) String() string {
	return fmt.Sprintf("DebugReportCallbackEXT(0x%X)", uint64(h))
}

// DebugUtilsMessengerEXT is a Vulkan VkDebugUtilsMessengerEXT handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessengerEXT.html
type DebugUtilsMessengerEXT uint64

// IsValid returns true if the DebugUtilsMessengerEXT handle is not NULL.
func (h DebugUtilsMessengerEXT) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DebugUtilsMessengerEXT) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DebugUtilsMessengerEXT) String() string {
	return fmt.Sprintf("DebugUtilsMessengerEXT(0x%X)", uint64(h))
}

// DeferredOperationKHR is a Vulkan VkDeferredOperationKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDeferredOperationKHR.html
type DeferredOperationKHR uint64

// IsValid returns true if the DeferredOperationKHR handle is not NULL.
func (h DeferredOperationKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DeferredOperationKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DeferredOperationKHR) String() string {
	return fmt.Sprintf("DeferredOperationKHR(0x%X)", uint64(h))
}

// DescriptorPool is a Vulkan VkDescriptorPool handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorPool.html
type DescriptorPool uint64

// IsValid returns true if the DescriptorPool handle is not NULL.
func (h DescriptorPool) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DescriptorPool) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DescriptorPool) String() string {
	return fmt.Sprintf("DescriptorPool(0x%X)", uint64(h))
}

// DescriptorSet is a Vulkan VkDescriptorSet handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSet.html
type DescriptorSet uint64

// IsValid returns true if the DescriptorSet handle is not NULL.
func (h DescriptorSet) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DescriptorSet) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DescriptorSet) String() string {
	return fmt.Sprintf("DescriptorSet(0x%X)", uint64(h))
}

// DescriptorSetLayout is a Vulkan VkDescriptorSetLayout handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayout.html
type DescriptorSetLayout uint64

// IsValid returns true if the DescriptorSetLayout handle is not NULL.
func (h DescriptorSetLayout) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DescriptorSetLayout) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DescriptorSetLayout) String() string {
	return fmt.Sprintf("DescriptorSetLayout(0x%X)", uint64(h))
}

// DescriptorUpdateTemplate is a Vulkan VkDescriptorUpdateTemplate handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorUpdateTemplate.html
type DescriptorUpdateTemplate uint64

// IsValid returns true if the DescriptorUpdateTemplate handle is not NULL.
func (h DescriptorUpdateTemplate) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DescriptorUpdateTemplate) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DescriptorUpdateTemplate) String() string {
	return fmt.Sprintf("DescriptorUpdateTemplate(0x%X)", uint64(h))
}

// Device is a Vulkan VkDevice handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDevice.html
type Device uintptr

// IsValid returns true if the Device handle is not NULL.
func (h Device) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uintptr value.
func (h Device) Handle() uintptr {
	return uintptr(h)
}

// String formats the handle as a hex string.
func (h Device) String() string {
	return fmt.Sprintf("Device(0x%X)", uintptr(h))
}

// DeviceMemory is a Vulkan VkDeviceMemory handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDeviceMemory.html
type DeviceMemory uint64

// IsValid returns true if the DeviceMemory handle is not NULL.
func (h DeviceMemory) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DeviceMemory) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DeviceMemory) String() string {
	return fmt.Sprintf("DeviceMemory(0x%X)", uint64(h))
}

// DisplayKHR is a Vulkan VkDisplayKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDisplayKHR.html
type DisplayKHR uint64

// IsValid returns true if the DisplayKHR handle is not NULL.
func (h DisplayKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DisplayKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DisplayKHR) String() string {
	return fmt.Sprintf("DisplayKHR(0x%X)", uint64(h))
}

// DisplayModeKHR is a Vulkan VkDisplayModeKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDisplayModeKHR.html
type DisplayModeKHR uint64

// IsValid returns true if the DisplayModeKHR handle is not NULL.
func (h DisplayModeKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h DisplayModeKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h DisplayModeKHR) String() string {
	return fmt.Sprintf("DisplayModeKHR(0x%X)", uint64(h))
}

// Event is a Vulkan VkEvent handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkEvent.html
type Event uint64

// IsValid returns true if the Event handle is not NULL.
func (h Event) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Event) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Event) String() string {
	return fmt.Sprintf("Event(0x%X)", uint64(h))
}

// ExternalComputeQueueNV is a Vulkan VkExternalComputeQueueNV handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkExternalComputeQueueNV.html
type ExternalComputeQueueNV uintptr

// IsValid returns true if the ExternalComputeQueueNV handle is not NULL.
func (h ExternalComputeQueueNV) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uintptr value.
func (h ExternalComputeQueueNV) Handle() uintptr {
	return uintptr(h)
}

// String formats the handle as a hex string.
func (h ExternalComputeQueueNV) String() string {
	return fmt.Sprintf("ExternalComputeQueueNV(0x%X)", uintptr(h))
}

// Fence is a Vulkan VkFence handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFence.html
type Fence uint64

// IsValid returns true if the Fence handle is not NULL.
func (h Fence) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Fence) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Fence) String() string {
	return fmt.Sprintf("Fence(0x%X)", uint64(h))
}

// Framebuffer is a Vulkan VkFramebuffer handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFramebuffer.html
type Framebuffer uint64

// IsValid returns true if the Framebuffer handle is not NULL.
func (h Framebuffer) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Framebuffer) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Framebuffer) String() string {
	return fmt.Sprintf("Framebuffer(0x%X)", uint64(h))
}

// GpaSessionAMD is a Vulkan VkGpaSessionAMD handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkGpaSessionAMD.html
type GpaSessionAMD uint64

// IsValid returns true if the GpaSessionAMD handle is not NULL.
func (h GpaSessionAMD) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h GpaSessionAMD) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h GpaSessionAMD) String() string {
	return fmt.Sprintf("GpaSessionAMD(0x%X)", uint64(h))
}

// Image is a Vulkan VkImage handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImage.html
type Image uint64

// IsValid returns true if the Image handle is not NULL.
func (h Image) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Image) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Image) String() string {
	return fmt.Sprintf("Image(0x%X)", uint64(h))
}

// ImageView is a Vulkan VkImageView handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageView.html
type ImageView uint64

// IsValid returns true if the ImageView handle is not NULL.
func (h ImageView) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h ImageView) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h ImageView) String() string {
	return fmt.Sprintf("ImageView(0x%X)", uint64(h))
}

// IndirectCommandsLayoutEXT is a Vulkan VkIndirectCommandsLayoutEXT handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkIndirectCommandsLayoutEXT.html
type IndirectCommandsLayoutEXT uint64

// IsValid returns true if the IndirectCommandsLayoutEXT handle is not NULL.
func (h IndirectCommandsLayoutEXT) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h IndirectCommandsLayoutEXT) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h IndirectCommandsLayoutEXT) String() string {
	return fmt.Sprintf("IndirectCommandsLayoutEXT(0x%X)", uint64(h))
}

// IndirectCommandsLayoutNV is a Vulkan VkIndirectCommandsLayoutNV handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkIndirectCommandsLayoutNV.html
type IndirectCommandsLayoutNV uint64

// IsValid returns true if the IndirectCommandsLayoutNV handle is not NULL.
func (h IndirectCommandsLayoutNV) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h IndirectCommandsLayoutNV) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h IndirectCommandsLayoutNV) String() string {
	return fmt.Sprintf("IndirectCommandsLayoutNV(0x%X)", uint64(h))
}

// IndirectExecutionSetEXT is a Vulkan VkIndirectExecutionSetEXT handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkIndirectExecutionSetEXT.html
type IndirectExecutionSetEXT uint64

// IsValid returns true if the IndirectExecutionSetEXT handle is not NULL.
func (h IndirectExecutionSetEXT) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h IndirectExecutionSetEXT) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h IndirectExecutionSetEXT) String() string {
	return fmt.Sprintf("IndirectExecutionSetEXT(0x%X)", uint64(h))
}

// Instance is a Vulkan VkInstance handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkInstance.html
type Instance uintptr

// IsValid returns true if the Instance handle is not NULL.
func (h Instance) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uintptr value.
func (h Instance) Handle() uintptr {
	return uintptr(h)
}

// String formats the handle as a hex string.
func (h Instance) String() string {
	return fmt.Sprintf("Instance(0x%X)", uintptr(h))
}

// MicromapEXT is a Vulkan VkMicromapEXT handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkMicromapEXT.html
type MicromapEXT uint64

// IsValid returns true if the MicromapEXT handle is not NULL.
func (h MicromapEXT) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h MicromapEXT) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h MicromapEXT) String() string {
	return fmt.Sprintf("MicromapEXT(0x%X)", uint64(h))
}

// OpticalFlowSessionNV is a Vulkan VkOpticalFlowSessionNV handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkOpticalFlowSessionNV.html
type OpticalFlowSessionNV uint64

// IsValid returns true if the OpticalFlowSessionNV handle is not NULL.
func (h OpticalFlowSessionNV) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h OpticalFlowSessionNV) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h OpticalFlowSessionNV) String() string {
	return fmt.Sprintf("OpticalFlowSessionNV(0x%X)", uint64(h))
}

// PerformanceConfigurationINTEL is a Vulkan VkPerformanceConfigurationINTEL handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPerformanceConfigurationINTEL.html
type PerformanceConfigurationINTEL uint64

// IsValid returns true if the PerformanceConfigurationINTEL handle is not NULL.
func (h PerformanceConfigurationINTEL) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h PerformanceConfigurationINTEL) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h PerformanceConfigurationINTEL) String() string {
	return fmt.Sprintf("PerformanceConfigurationINTEL(0x%X)", uint64(h))
}

// PhysicalDevice is a Vulkan VkPhysicalDevice handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDevice.html
type PhysicalDevice uintptr

// IsValid returns true if the PhysicalDevice handle is not NULL.
func (h PhysicalDevice) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uintptr value.
func (h PhysicalDevice) Handle() uintptr {
	return uintptr(h)
}

// String formats the handle as a hex string.
func (h PhysicalDevice) String() string {
	return fmt.Sprintf("PhysicalDevice(0x%X)", uintptr(h))
}

// Pipeline is a Vulkan VkPipeline handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipeline.html
type Pipeline uint64

// IsValid returns true if the Pipeline handle is not NULL.
func (h Pipeline) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Pipeline) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Pipeline) String() string {
	return fmt.Sprintf("Pipeline(0x%X)", uint64(h))
}

// PipelineBinaryKHR is a Vulkan VkPipelineBinaryKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineBinaryKHR.html
type PipelineBinaryKHR uint64

// IsValid returns true if the PipelineBinaryKHR handle is not NULL.
func (h PipelineBinaryKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h PipelineBinaryKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h PipelineBinaryKHR) String() string {
	return fmt.Sprintf("PipelineBinaryKHR(0x%X)", uint64(h))
}

// PipelineCache is a Vulkan VkPipelineCache handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineCache.html
type PipelineCache uint64

// IsValid returns true if the PipelineCache handle is not NULL.
func (h PipelineCache) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h PipelineCache) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h PipelineCache) String() string {
	return fmt.Sprintf("PipelineCache(0x%X)", uint64(h))
}

// PipelineLayout is a Vulkan VkPipelineLayout handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineLayout.html
type PipelineLayout uint64

// IsValid returns true if the PipelineLayout handle is not NULL.
func (h PipelineLayout) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h PipelineLayout) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h PipelineLayout) String() string {
	return fmt.Sprintf("PipelineLayout(0x%X)", uint64(h))
}

// PrivateDataSlot is a Vulkan VkPrivateDataSlot handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPrivateDataSlot.html
type PrivateDataSlot uint64

// IsValid returns true if the PrivateDataSlot handle is not NULL.
func (h PrivateDataSlot) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h PrivateDataSlot) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h PrivateDataSlot) String() string {
	return fmt.Sprintf("PrivateDataSlot(0x%X)", uint64(h))
}

// QueryPool is a Vulkan VkQueryPool handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkQueryPool.html
type QueryPool uint64

// IsValid returns true if the QueryPool handle is not NULL.
func (h QueryPool) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h QueryPool) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h QueryPool) String() string {
	return fmt.Sprintf("QueryPool(0x%X)", uint64(h))
}

// Queue is a Vulkan VkQueue handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkQueue.html
type Queue uintptr

// IsValid returns true if the Queue handle is not NULL.
func (h Queue) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uintptr value.
func (h Queue) Handle() uintptr {
	return uintptr(h)
}

// String formats the handle as a hex string.
func (h Queue) String() string {
	return fmt.Sprintf("Queue(0x%X)", uintptr(h))
}

// RenderPass is a Vulkan VkRenderPass handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkRenderPass.html
type RenderPass uint64

// IsValid returns true if the RenderPass handle is not NULL.
func (h RenderPass) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h RenderPass) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h RenderPass) String() string {
	return fmt.Sprintf("RenderPass(0x%X)", uint64(h))
}

// Sampler is a Vulkan VkSampler handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSampler.html
type Sampler uint64

// IsValid returns true if the Sampler handle is not NULL.
func (h Sampler) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Sampler) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Sampler) String() string {
	return fmt.Sprintf("Sampler(0x%X)", uint64(h))
}

// SamplerYcbcrConversion is a Vulkan VkSamplerYcbcrConversion handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSamplerYcbcrConversion.html
type SamplerYcbcrConversion uint64

// IsValid returns true if the SamplerYcbcrConversion handle is not NULL.
func (h SamplerYcbcrConversion) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h SamplerYcbcrConversion) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h SamplerYcbcrConversion) String() string {
	return fmt.Sprintf("SamplerYcbcrConversion(0x%X)", uint64(h))
}

// Semaphore is a Vulkan VkSemaphore handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSemaphore.html
type Semaphore uint64

// IsValid returns true if the Semaphore handle is not NULL.
func (h Semaphore) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h Semaphore) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h Semaphore) String() string {
	return fmt.Sprintf("Semaphore(0x%X)", uint64(h))
}

// SemaphoreSciSyncPoolNV is a Vulkan VkSemaphoreSciSyncPoolNV handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSemaphoreSciSyncPoolNV.html
type SemaphoreSciSyncPoolNV uint64

// IsValid returns true if the SemaphoreSciSyncPoolNV handle is not NULL.
func (h SemaphoreSciSyncPoolNV) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h SemaphoreSciSyncPoolNV) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h SemaphoreSciSyncPoolNV) String() string {
	return fmt.Sprintf("SemaphoreSciSyncPoolNV(0x%X)", uint64(h))
}

// ShaderEXT is a Vulkan VkShaderEXT handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkShaderEXT.html
type ShaderEXT uint64

// IsValid returns true if the ShaderEXT handle is not NULL.
func (h ShaderEXT) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h ShaderEXT) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h ShaderEXT) String() string {
	return fmt.Sprintf("ShaderEXT(0x%X)", uint64(h))
}

// ShaderInstrumentationARM is a Vulkan VkShaderInstrumentationARM handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkShaderInstrumentationARM.html
type ShaderInstrumentationARM uint64

// IsValid returns true if the ShaderInstrumentationARM handle is not NULL.
func (h ShaderInstrumentationARM) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h ShaderInstrumentationARM) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h ShaderInstrumentationARM) String() string {
	return fmt.Sprintf("ShaderInstrumentationARM(0x%X)", uint64(h))
}

// ShaderModule is a Vulkan VkShaderModule handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkShaderModule.html
type ShaderModule uint64

// IsValid returns true if the ShaderModule handle is not NULL.
func (h ShaderModule) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h ShaderModule) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h ShaderModule) String() string {
	return fmt.Sprintf("ShaderModule(0x%X)", uint64(h))
}

// SurfaceKHR is a Vulkan VkSurfaceKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceKHR.html
type SurfaceKHR uint64

// IsValid returns true if the SurfaceKHR handle is not NULL.
func (h SurfaceKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h SurfaceKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h SurfaceKHR) String() string {
	return fmt.Sprintf("SurfaceKHR(0x%X)", uint64(h))
}

// SwapchainKHR is a Vulkan VkSwapchainKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSwapchainKHR.html
type SwapchainKHR uint64

// IsValid returns true if the SwapchainKHR handle is not NULL.
func (h SwapchainKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h SwapchainKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h SwapchainKHR) String() string {
	return fmt.Sprintf("SwapchainKHR(0x%X)", uint64(h))
}

// TensorARM is a Vulkan VkTensorARM handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkTensorARM.html
type TensorARM uint64

// IsValid returns true if the TensorARM handle is not NULL.
func (h TensorARM) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h TensorARM) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h TensorARM) String() string {
	return fmt.Sprintf("TensorARM(0x%X)", uint64(h))
}

// TensorViewARM is a Vulkan VkTensorViewARM handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkTensorViewARM.html
type TensorViewARM uint64

// IsValid returns true if the TensorViewARM handle is not NULL.
func (h TensorViewARM) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h TensorViewARM) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h TensorViewARM) String() string {
	return fmt.Sprintf("TensorViewARM(0x%X)", uint64(h))
}

// ValidationCacheEXT is a Vulkan VkValidationCacheEXT handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkValidationCacheEXT.html
type ValidationCacheEXT uint64

// IsValid returns true if the ValidationCacheEXT handle is not NULL.
func (h ValidationCacheEXT) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h ValidationCacheEXT) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h ValidationCacheEXT) String() string {
	return fmt.Sprintf("ValidationCacheEXT(0x%X)", uint64(h))
}

// VideoSessionKHR is a Vulkan VkVideoSessionKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkVideoSessionKHR.html
type VideoSessionKHR uint64

// IsValid returns true if the VideoSessionKHR handle is not NULL.
func (h VideoSessionKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h VideoSessionKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h VideoSessionKHR) String() string {
	return fmt.Sprintf("VideoSessionKHR(0x%X)", uint64(h))
}

// VideoSessionParametersKHR is a Vulkan VkVideoSessionParametersKHR handle.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkVideoSessionParametersKHR.html
type VideoSessionParametersKHR uint64

// IsValid returns true if the VideoSessionParametersKHR handle is not NULL.
func (h VideoSessionParametersKHR) IsValid() bool {
	return h != 0
}

// Handle returns the underlying uint64 value.
func (h VideoSessionParametersKHR) Handle() uint64 {
	return uint64(h)
}

// String formats the handle as a hex string.
func (h VideoSessionParametersKHR) String() string {
	return fmt.Sprintf("VideoSessionParametersKHR(0x%X)", uint64(h))
}

// --- Handle and Type Aliases ---

// DescriptorUpdateTemplateKHR is an alias of DescriptorUpdateTemplate.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorUpdateTemplateKHR.html
type DescriptorUpdateTemplateKHR = DescriptorUpdateTemplate

// PrivateDataSlotEXT is an alias of PrivateDataSlot.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPrivateDataSlotEXT.html
type PrivateDataSlotEXT = PrivateDataSlot

// SamplerYcbcrConversionKHR is an alias of SamplerYcbcrConversion.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSamplerYcbcrConversionKHR.html
type SamplerYcbcrConversionKHR = SamplerYcbcrConversion

// --- Function Pointer (Callback) Types ---

// PFN_vkAllocationFunction is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkAllocationFunction.html
type PFN_vkAllocationFunction func(userData unsafe.Pointer, size uintptr, alignment uintptr, allocationScope SystemAllocationScope) unsafe.Pointer

// PFN_vkDebugReportCallbackEXT is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkDebugReportCallbackEXT.html
type PFN_vkDebugReportCallbackEXT func(flags DebugReportFlagsEXT, objectType DebugReportObjectTypeEXT, object uint64, location uintptr, messageCode int32, layerPrefix *byte, message *byte, userData unsafe.Pointer) Bool32

// PFN_vkDebugUtilsMessengerCallbackEXT is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkDebugUtilsMessengerCallbackEXT.html
type PFN_vkDebugUtilsMessengerCallbackEXT func(messageSeverity DebugUtilsMessageSeverityFlagBitsEXT, messageTypes DebugUtilsMessageTypeFlagsEXT, callbackData *RawDebugUtilsMessengerCallbackDataEXT, userData unsafe.Pointer) Bool32

// PFN_vkDeviceMemoryReportCallbackEXT is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkDeviceMemoryReportCallbackEXT.html
type PFN_vkDeviceMemoryReportCallbackEXT func(callbackData *RawDeviceMemoryReportCallbackDataEXT, userData unsafe.Pointer)

// PFN_vkFaultCallbackFunction is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkFaultCallbackFunction.html
type PFN_vkFaultCallbackFunction func(unrecordedFaults Bool32, faultCount uint32, faults *RawFaultData)

// PFN_vkFreeFunction is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkFreeFunction.html
type PFN_vkFreeFunction func(userData unsafe.Pointer, memory unsafe.Pointer)

// PFN_vkGetInstanceProcAddrLUNARG is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkGetInstanceProcAddrLUNARG.html
type PFN_vkGetInstanceProcAddrLUNARG func(instance Instance, name *byte) PFN_vkVoidFunction

// PFN_vkInternalAllocationNotification is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkInternalAllocationNotification.html
type PFN_vkInternalAllocationNotification func(userData unsafe.Pointer, size uintptr, allocationType InternalAllocationType, allocationScope SystemAllocationScope)

// PFN_vkInternalFreeNotification is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkInternalFreeNotification.html
type PFN_vkInternalFreeNotification func(userData unsafe.Pointer, size uintptr, allocationType InternalAllocationType, allocationScope SystemAllocationScope)

// PFN_vkReallocationFunction is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkReallocationFunction.html
type PFN_vkReallocationFunction func(userData unsafe.Pointer, original unsafe.Pointer, size uintptr, alignment uintptr, allocationScope SystemAllocationScope) unsafe.Pointer

// PFN_vkVoidFunction is a Vulkan function pointer / callback type.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/PFN_vkVoidFunction.html
type PFN_vkVoidFunction func()
