// Code generated by vk-gen. DO NOT EDIT.

package khr_device_fault

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetDeviceFaultDebugInfoKHR uintptr
	pfnGetDeviceFaultReportsKHR   uintptr
)

// Init resolves and initializes all VK_KHR_device_fault extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetDeviceFaultDebugInfoKHR = vulkan.GetDeviceProcAddr(device, "vkGetDeviceFaultDebugInfoKHR")
	pfnGetDeviceFaultReportsKHR = vulkan.GetDeviceProcAddr(device, "vkGetDeviceFaultReportsKHR")
}

// GetDeviceFaultDebugInfoKHR - Retrieve vendor-specific crash dump data for the specified logical device (vkGetDeviceFaultDebugInfoKHR).
// Parameters:
//   - device: is the logical device from which to query the crash dump.
//   - debugInfo: is a pointer to a VkDeviceFaultDebugInfoKHR structure which will be populated with the vendor binary data crash dump binary, as described below.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_NOT_ENOUGH_SPACE_KHR, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetDeviceFaultDebugInfoKHR.html
func GetDeviceFaultDebugInfoKHR(device vulkan.Device) (debugInfo vulkan.DeviceFaultDebugInfoKHR, result vulkan.Result) {
	r1, _, _ := vulkan.CallSyscall(pfnGetDeviceFaultDebugInfoKHR, uintptr(device), uintptr(unsafe.Pointer(&debugInfo)))
	return debugInfo, vulkan.Result(r1)
}

// GetDeviceFaultReportsKHR - Reports fault information for the specified device (vkGetDeviceFaultReportsKHR).
// Parameters:
//   - device: is the logical device from which to query the diagnostic fault information.
//   - timeout: is the timeout period in units of nanoseconds. timeout is adjusted to the closest value allowed by the implementation-dependent timeout accuracy, which may be substantially longer than one nanosecond, and may be longer than the requested period.
//   - faultInfo: is NULL or a pointer to an array of VkDeviceFaultInfoKHR structures in which fault information is returned.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE, VK_TIMEOUT
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetDeviceFaultReportsKHR.html
func GetDeviceFaultReportsKHR(device vulkan.Device, timeout uint64) (faultInfo []vulkan.DeviceFaultInfoKHR, result vulkan.Result) {
	var count uint32
	r1, _, _ := vulkan.CallSyscall(pfnGetDeviceFaultReportsKHR, uintptr(device), uintptr(timeout), uintptr(unsafe.Pointer(&count)), 0)
	if vulkan.Result(r1) != vulkan.SUCCESS || count == 0 {
		return nil, vulkan.Result(r1)
	}

	faultInfo = make([]vulkan.DeviceFaultInfoKHR, count)
	call2ArgsPtr := uintptr(unsafe.Pointer(&faultInfo[0]))
	r1, _, _ = vulkan.CallSyscall(pfnGetDeviceFaultReportsKHR, uintptr(device), uintptr(timeout), uintptr(unsafe.Pointer(&count)), call2ArgsPtr)
	return faultInfo, vulkan.Result(r1)
}
