// Code generated by vk-gen. DO NOT EDIT.

// Package khr_vertex_attribute_divisor provides bindings for the VK_KHR_vertex_attribute_divisor extension.
// Author: KHR
// Contact: Shahbaz Youssefi @syoussefi
// Promoted to: VK_VERSION_1_4
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2023-09-20
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Shahbaz Youssefi, Google
//   - Contributors to VKEXTvertexattributedivisor
//
// Description:
//
// This extension is based on the VKEXTvertexattributedivisor
// extension.
// The only difference is the new property supportsNonZeroFirstInstance,
// which indicates support for non-zero values in firstInstance.
// This allows the extension to be supported on implementations that have
// traditionally only supported OpenGL ES.
//
// Promotion to Vulkan 1.4:
//
// Functionality in this extension is included in core Vulkan 1.4 with the KHR
// suffix omitted.
// The original type, enum, and command names are still available as aliases of
// the core functionality.
//
// Version History:
//
//   - Revision 1, 2023-09-20 (Shahbaz Youssefi)
//   - First Version, based on VKEXTvertexattributedivisor
package khr_vertex_attribute_divisor
