// Code generated by vk-gen. DO NOT EDIT.

// Package ext_separate_stencil_usage provides bindings for the VK_EXT_separate_stencil_usage extension.
// Author: EXT
// Contact: Daniel Rakos @drakos-amd
// Promoted to: VK_VERSION_1_2
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2018-11-08
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Daniel Rakos, AMD
//   - Jordan Logan, AMD
//
// Description:
//
// This extension allows specifying separate usage flags for the stencil aspect
// of images with a depth-stencil format at image creation time.
//
// Promotion to Vulkan 1.2:
//
// All functionality in this extension is included in core Vulkan 1.2, with the
// EXT suffix omitted.
// The original type, enum, and command names are still available as aliases of
// the core functionality.
//
// Version History:
//
//   - Revision 1, 2018-11-08 (Daniel Rakos)
//   - Internal revisions.
package ext_separate_stencil_usage
