// Code generated by vk-gen. DO NOT EDIT.

// Package khr_pipeline_library provides bindings for the VK_KHR_pipeline_library extension.
// Author: KHR
// Contact: Christoph Kubisch @pixeljetstream
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2020-01-08
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - See contributors to VKKHRraytracingpipeline
//
// Description:
//
// A pipeline library is a special pipeline that cannot be bound, instead it
// defines a set of shaders and shader groups which can be linked into other
// pipelines.
// This extension defines the infrastructure for pipeline libraries, but does
// not specify the creation or usage of pipeline libraries.
// This is left to additional dependent extensions.
//
// Version History:
//
//   - Revision 1, 2020-01-08 (Christoph Kubisch)
//   - Initial draft.
package khr_pipeline_library
