// Code generated by vk-gen. DO NOT EDIT.

// Package ext_frame_boundary provides bindings for the VK_EXT_frame_boundary extension.
// Author: EXT
// Contact: James Fitzpatrick @jamesfitzpatrick
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2023-06-14
//
// Contributors:
//   - James Fitzpatrick, Imagination Technologies
//   - Hugues Evrard, Google
//   - Melih Yasin Yalcin, Google
//   - Andrew Garrard, Imagination Technologies
//   - Jan-Harald Fredriksen, Arm
//   - Vassili Nikolaev, NVIDIA
//   - Ting Wei, Huawei
//
// Description:
//
// VKEXTframe_boundary is a device extension that helps tools (such
// as debuggers) to group queue submissions per frames in non-trivial
// scenarios, typically when vkQueuePresentKHR is not a relevant frame
// boundary delimiter.
//
// Version History:
//
//   - Revision 0, 2022-01-14 (Hugues Evard)
//
//   - Initial proposal
//
//   - Revision 1, 2023-06-14 (James Fitzpatrick)
//
//   - Initial draft
package ext_frame_boundary
