// Code generated by vk-gen. DO NOT EDIT.

// Package ggp_stream_descriptor_surface provides bindings for the VK_GGP_stream_descriptor_surface extension.
// Author: GGP
// Contact: Jean-Francois Roy @jfroy
// Platform: ggp
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2019-01-28
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Jean-Francois Roy, Google
//   - Brad Grantham, Google
//   - Connor Smith, Google
//   - Cort Stratton, Google
//   - Hai Nguyen, Google
//   - Ian Elliott, Google
//   - Jesse Hall, Google
//   - Jim Ray, Google
//   - Katherine Wu, Google
//   - Kaye Mason, Google
//   - Kuangye Guo, Google
//   - Mark Segal, Google
//   - Nicholas Vining, Google
//   - Paul Lalonde, Google
//   - Richard O'Grady, Google
//
// Description:
//
// The VKGGPstreamdescriptorsurface extension is an instance extension.
// It provides a mechanism to create a VkSurfaceKHR object (defined by
// the VKKHRsurface extension) that refers to a Google Games
// Platform GgpStreamDescriptor.
//
// Version History:
//
//   - Revision 1, 2018-11-26 (Jean-Francois Roy)
//   - Initial revision.
package ggp_stream_descriptor_surface
