// Code generated by vk-gen. DO NOT EDIT.

package ext_conditional_rendering

import (
	"unsafe"

	"go.cld.moe/vk_google/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdBeginConditionalRenderingEXT uintptr
	pfnCmdEndConditionalRenderingEXT   uintptr
)

// Init resolves and initializes all VK_EXT_conditional_rendering extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdBeginConditionalRenderingEXT = vulkan.GetDeviceProcAddr(device, "vkCmdBeginConditionalRenderingEXT")
	pfnCmdEndConditionalRenderingEXT = vulkan.GetDeviceProcAddr(device, "vkCmdEndConditionalRenderingEXT")
}

// CmdBeginConditionalRenderingEXT - Define the beginning of a conditional rendering block (vkCmdBeginConditionalRenderingEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which this command will be recorded.
//   - conditionalRenderingBegin: is a pointer to a VkConditionalRenderingBeginInfoEXT structure specifying parameters of conditional rendering.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginConditionalRenderingEXT.html
func CmdBeginConditionalRenderingEXT(commandBuffer vulkan.CommandBuffer, conditionalRenderingBegin *vulkan.ConditionalRenderingBeginInfoEXT) {
	c_conditionalRenderingBegin := conditionalRenderingBegin.Raw()
	vulkan.CallSyscall(pfnCmdBeginConditionalRenderingEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_conditionalRenderingBegin)))
}

// CmdEndConditionalRenderingEXT - Define the end of a conditional rendering block (vkCmdEndConditionalRenderingEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which this command will be recorded.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdEndConditionalRenderingEXT.html
func CmdEndConditionalRenderingEXT(commandBuffer vulkan.CommandBuffer) {
	vulkan.CallSyscall(pfnCmdEndConditionalRenderingEXT, uintptr(commandBuffer))
}
