// Code generated by vk-gen. DO NOT EDIT.

// Package khr_shader_quad_control provides bindings for the VK_KHR_shader_quad_control extension.
// Author: KHR
// Contact: Tobias Hector @tobski
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2023-11-01
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Tobias Hector, AMD
//   - Bill Licea-Kane, Qualcomm
//   - Graeme Leese, Broadcom
//   - Jan-Harald Fredriksen, Arm
//   - Nicolai Hähnle, AMD
//   - Jeff Bolz, NVidia
//   - Alan Baker, Google
//   - Hans-Kristian Arntzen, Valve
//
// Description:
//
// This extension adds new quad any/all operations, requires that derivatives
// are well-defined in quad-uniform control flow, and adds the ability to
// require helper invocations participate in group operations.
//
// New SPIR-V Capabilities:
//
//   - QuadControlKHR
//
// Version History:
//
//   - Revision 1, 2023-11-01 (Tobias Hector)
//   - Initial draft
package khr_shader_quad_control
