// Code generated by vk-gen. DO NOT EDIT.

// Package khr_video_encode_feedback2 provides bindings for the VK_KHR_video_encode_feedback2 extension.
// Author: KHR
// Contact: Ahmed Abdelkhalek @aabdelkh
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2026-02-04
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Sreerenj Balachandran, Amazon
//   - Ahmed Abdelkhalek, AMD
//   - Benjamin Cheng, AMD
//   - Aidan Fabius, Core Avionics & Industrial Inc.
//   - Ping Liu, Intel
//   - Srinath Kumarapuram, NVIDIA
//   - Tony Zlatinski, NVIDIA
//   - Daniel Rakos, RasterGrid
//
// Description:
//
// This extension builds upon the VKQUERYTYPEVIDEOENCODEFEEDBACKKHR
// queries introduced by the VKKHRvideoencodequeue extension and
// extends the set of supported video encode feedback values with additional
// statistics about the encoded picture, including per picture partition
// feedback values.
//
// Version History:
//
//   - Revision 1, 2026-02-04 (Daniel Rakos)
//   - Internal revisions
package khr_video_encode_feedback2
