// Code generated by vk-gen. DO NOT EDIT.

package ext_primitive_restart_index

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Commands holds resolved procedure addresses for an instance and/or device.
type Commands struct {
	pfnCmdSetPrimitiveRestartIndexEXT uintptr
}

// Default procedure addresses resolved by Init
var (
	pfnCmdSetPrimitiveRestartIndexEXT uintptr
)

// Init resolves and initializes all VK_EXT_primitive_restart_index extension procedure addresses, setting default globals and returning a Commands instance for multi-device support.
func Init(instance vulkan.Instance, device vulkan.Device) *Commands {
	cmds := &Commands{
		pfnCmdSetPrimitiveRestartIndexEXT: vulkan.GetDeviceProcAddr(device, "vkCmdSetPrimitiveRestartIndexEXT"),
	}
	pfnCmdSetPrimitiveRestartIndexEXT = cmds.pfnCmdSetPrimitiveRestartIndexEXT
	return cmds
}

// CmdSetPrimitiveRestartIndexEXT - Set primitive assembly restart index dynamically for a command buffer (vkCmdSetPrimitiveRestartIndexEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - primitiveRestartIndex: controls which special vertex index value is treated as restarting the assembly of primitives. This overrides the default restart index value as defined as part of the description of the VkPipelineInputAssemblyStateCreateInfo::pname:primitiveRestartEnable state. Default values are applied when binding an index buffer.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetPrimitiveRestartIndexEXT.html
func (c *Commands) CmdSetPrimitiveRestartIndexEXT(commandBuffer vulkan.CommandBuffer, primitiveRestartIndex uint32) {
	vulkan.CallSyscall(c.pfnCmdSetPrimitiveRestartIndexEXT, uintptr(commandBuffer), uintptr(primitiveRestartIndex))
}

func CmdSetPrimitiveRestartIndexEXT(commandBuffer vulkan.CommandBuffer, primitiveRestartIndex uint32) {
	vulkan.CallSyscall(pfnCmdSetPrimitiveRestartIndexEXT, uintptr(commandBuffer), uintptr(primitiveRestartIndex))
}
