// Code generated by vk-gen. DO NOT EDIT.

package ext_debug_utils

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Commands holds resolved procedure addresses for an instance and/or device.
type Commands struct {
	pfnCmdBeginDebugUtilsLabelEXT    uintptr
	pfnCmdEndDebugUtilsLabelEXT      uintptr
	pfnCmdInsertDebugUtilsLabelEXT   uintptr
	pfnCreateDebugUtilsMessengerEXT  uintptr
	pfnDestroyDebugUtilsMessengerEXT uintptr
	pfnQueueBeginDebugUtilsLabelEXT  uintptr
	pfnQueueEndDebugUtilsLabelEXT    uintptr
	pfnQueueInsertDebugUtilsLabelEXT uintptr
	pfnSetDebugUtilsObjectNameEXT    uintptr
	pfnSetDebugUtilsObjectTagEXT     uintptr
	pfnSubmitDebugUtilsMessageEXT    uintptr
}

// Default procedure addresses resolved by Init
var (
	pfnCmdBeginDebugUtilsLabelEXT    uintptr
	pfnCmdEndDebugUtilsLabelEXT      uintptr
	pfnCmdInsertDebugUtilsLabelEXT   uintptr
	pfnCreateDebugUtilsMessengerEXT  uintptr
	pfnDestroyDebugUtilsMessengerEXT uintptr
	pfnQueueBeginDebugUtilsLabelEXT  uintptr
	pfnQueueEndDebugUtilsLabelEXT    uintptr
	pfnQueueInsertDebugUtilsLabelEXT uintptr
	pfnSetDebugUtilsObjectNameEXT    uintptr
	pfnSetDebugUtilsObjectTagEXT     uintptr
	pfnSubmitDebugUtilsMessageEXT    uintptr
)

// Init resolves and initializes all VK_EXT_debug_utils extension procedure addresses, setting default globals and returning a Commands instance for multi-device support.
func Init(instance vulkan.Instance, device vulkan.Device) *Commands {
	cmds := &Commands{
		pfnCmdBeginDebugUtilsLabelEXT:    vulkan.GetDeviceProcAddr(device, "vkCmdBeginDebugUtilsLabelEXT"),
		pfnCmdEndDebugUtilsLabelEXT:      vulkan.GetDeviceProcAddr(device, "vkCmdEndDebugUtilsLabelEXT"),
		pfnCmdInsertDebugUtilsLabelEXT:   vulkan.GetDeviceProcAddr(device, "vkCmdInsertDebugUtilsLabelEXT"),
		pfnCreateDebugUtilsMessengerEXT:  vulkan.GetInstanceProcAddr(instance, "vkCreateDebugUtilsMessengerEXT"),
		pfnDestroyDebugUtilsMessengerEXT: vulkan.GetInstanceProcAddr(instance, "vkDestroyDebugUtilsMessengerEXT"),
		pfnQueueBeginDebugUtilsLabelEXT:  vulkan.GetDeviceProcAddr(device, "vkQueueBeginDebugUtilsLabelEXT"),
		pfnQueueEndDebugUtilsLabelEXT:    vulkan.GetDeviceProcAddr(device, "vkQueueEndDebugUtilsLabelEXT"),
		pfnQueueInsertDebugUtilsLabelEXT: vulkan.GetDeviceProcAddr(device, "vkQueueInsertDebugUtilsLabelEXT"),
		pfnSetDebugUtilsObjectNameEXT:    vulkan.GetDeviceProcAddr(device, "vkSetDebugUtilsObjectNameEXT"),
		pfnSetDebugUtilsObjectTagEXT:     vulkan.GetDeviceProcAddr(device, "vkSetDebugUtilsObjectTagEXT"),
		pfnSubmitDebugUtilsMessageEXT:    vulkan.GetInstanceProcAddr(instance, "vkSubmitDebugUtilsMessageEXT"),
	}
	pfnCmdBeginDebugUtilsLabelEXT = cmds.pfnCmdBeginDebugUtilsLabelEXT
	pfnCmdEndDebugUtilsLabelEXT = cmds.pfnCmdEndDebugUtilsLabelEXT
	pfnCmdInsertDebugUtilsLabelEXT = cmds.pfnCmdInsertDebugUtilsLabelEXT
	pfnCreateDebugUtilsMessengerEXT = cmds.pfnCreateDebugUtilsMessengerEXT
	pfnDestroyDebugUtilsMessengerEXT = cmds.pfnDestroyDebugUtilsMessengerEXT
	pfnQueueBeginDebugUtilsLabelEXT = cmds.pfnQueueBeginDebugUtilsLabelEXT
	pfnQueueEndDebugUtilsLabelEXT = cmds.pfnQueueEndDebugUtilsLabelEXT
	pfnQueueInsertDebugUtilsLabelEXT = cmds.pfnQueueInsertDebugUtilsLabelEXT
	pfnSetDebugUtilsObjectNameEXT = cmds.pfnSetDebugUtilsObjectNameEXT
	pfnSetDebugUtilsObjectTagEXT = cmds.pfnSetDebugUtilsObjectTagEXT
	pfnSubmitDebugUtilsMessageEXT = cmds.pfnSubmitDebugUtilsMessageEXT
	return cmds
}

// CmdBeginDebugUtilsLabelEXT - Open a command buffer debug label region (vkCmdBeginDebugUtilsLabelEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - labelInfo: is a pointer to a VkDebugUtilsLabelEXT structure specifying parameters of the label region to open.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBeginDebugUtilsLabelEXT.html
func (c *Commands) CmdBeginDebugUtilsLabelEXT(commandBuffer vulkan.CommandBuffer, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(c.pfnCmdBeginDebugUtilsLabelEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_labelInfo)))
}

func CmdBeginDebugUtilsLabelEXT(commandBuffer vulkan.CommandBuffer, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(pfnCmdBeginDebugUtilsLabelEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_labelInfo)))
}

// CmdEndDebugUtilsLabelEXT - Close a command buffer label region (vkCmdEndDebugUtilsLabelEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdEndDebugUtilsLabelEXT.html
func (c *Commands) CmdEndDebugUtilsLabelEXT(commandBuffer vulkan.CommandBuffer) {
	vulkan.CallSyscall(c.pfnCmdEndDebugUtilsLabelEXT, uintptr(commandBuffer))
}

func CmdEndDebugUtilsLabelEXT(commandBuffer vulkan.CommandBuffer) {
	vulkan.CallSyscall(pfnCmdEndDebugUtilsLabelEXT, uintptr(commandBuffer))
}

// CmdInsertDebugUtilsLabelEXT - Insert a label into a command buffer (vkCmdInsertDebugUtilsLabelEXT).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - labelInfo: is a pointer to a VkDebugUtilsLabelEXT structure specifying parameters of the label to insert.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdInsertDebugUtilsLabelEXT.html
func (c *Commands) CmdInsertDebugUtilsLabelEXT(commandBuffer vulkan.CommandBuffer, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(c.pfnCmdInsertDebugUtilsLabelEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_labelInfo)))
}

func CmdInsertDebugUtilsLabelEXT(commandBuffer vulkan.CommandBuffer, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(pfnCmdInsertDebugUtilsLabelEXT, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_labelInfo)))
}

// CreateDebugUtilsMessengerEXT - Create a debug messenger object (vkCreateDebugUtilsMessengerEXT).
// Parameters:
//   - instance: is the instance the messenger will be used with.
//   - createInfo: is a pointer to a VkDebugUtilsMessengerCreateInfoEXT structure containing the callback pointer, as well as defining conditions under which this messenger will trigger the callback.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//   - messenger: is a pointer to a VkDebugUtilsMessengerEXT handle in which the created object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateDebugUtilsMessengerEXT.html
func (c *Commands) CreateDebugUtilsMessengerEXT(instance vulkan.Instance, createInfo *vulkan.DebugUtilsMessengerCreateInfoEXT, allocator *vulkan.AllocationCallbacks) (messenger vulkan.DebugUtilsMessengerEXT, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnCreateDebugUtilsMessengerEXT, uintptr(instance), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&messenger)))
	return messenger, vulkan.Result(r1)
}

func CreateDebugUtilsMessengerEXT(instance vulkan.Instance, createInfo *vulkan.DebugUtilsMessengerCreateInfoEXT, allocator *vulkan.AllocationCallbacks) (messenger vulkan.DebugUtilsMessengerEXT, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateDebugUtilsMessengerEXT, uintptr(instance), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&messenger)))
	return messenger, vulkan.Result(r1)
}

// DestroyDebugUtilsMessengerEXT - Destroy a debug messenger object (vkDestroyDebugUtilsMessengerEXT).
// Parameters:
//   - instance: is the instance where the callback was created.
//   - messenger: is the VkDebugUtilsMessengerEXT object to destroy. messenger is an externally synchronized object and must not be used on more than one thread at a time. This means that vkDestroyDebugUtilsMessengerEXT must not be called when a callback is active.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkDestroyDebugUtilsMessengerEXT.html
func (c *Commands) DestroyDebugUtilsMessengerEXT(instance vulkan.Instance, messenger vulkan.DebugUtilsMessengerEXT, allocator *vulkan.AllocationCallbacks) {
	c_allocator := allocator.Raw()
	vulkan.CallSyscall(c.pfnDestroyDebugUtilsMessengerEXT, uintptr(instance), uintptr(messenger), uintptr(unsafe.Pointer(c_allocator)))
}

func DestroyDebugUtilsMessengerEXT(instance vulkan.Instance, messenger vulkan.DebugUtilsMessengerEXT, allocator *vulkan.AllocationCallbacks) {
	c_allocator := allocator.Raw()
	vulkan.CallSyscall(pfnDestroyDebugUtilsMessengerEXT, uintptr(instance), uintptr(messenger), uintptr(unsafe.Pointer(c_allocator)))
}

// QueueBeginDebugUtilsLabelEXT - Open a queue debug label region (vkQueueBeginDebugUtilsLabelEXT).
// Parameters:
//   - queue: is the queue in which to start a debug label region.
//   - labelInfo: is a pointer to a VkDebugUtilsLabelEXT structure specifying parameters of the label region to open.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkQueueBeginDebugUtilsLabelEXT.html
func (c *Commands) QueueBeginDebugUtilsLabelEXT(queue vulkan.Queue, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(c.pfnQueueBeginDebugUtilsLabelEXT, uintptr(queue), uintptr(unsafe.Pointer(c_labelInfo)))
}

func QueueBeginDebugUtilsLabelEXT(queue vulkan.Queue, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(pfnQueueBeginDebugUtilsLabelEXT, uintptr(queue), uintptr(unsafe.Pointer(c_labelInfo)))
}

// QueueEndDebugUtilsLabelEXT - Close a queue debug label region (vkQueueEndDebugUtilsLabelEXT).
// Parameters:
//   - queue: is the queue in which a debug label region should be closed.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkQueueEndDebugUtilsLabelEXT.html
func (c *Commands) QueueEndDebugUtilsLabelEXT(queue vulkan.Queue) {
	vulkan.CallSyscall(c.pfnQueueEndDebugUtilsLabelEXT, uintptr(queue))
}

func QueueEndDebugUtilsLabelEXT(queue vulkan.Queue) {
	vulkan.CallSyscall(pfnQueueEndDebugUtilsLabelEXT, uintptr(queue))
}

// QueueInsertDebugUtilsLabelEXT - Insert a label into a queue (vkQueueInsertDebugUtilsLabelEXT).
// Parameters:
//   - queue: is the queue into which a debug label will be inserted.
//   - labelInfo: is a pointer to a VkDebugUtilsLabelEXT structure specifying parameters of the label to insert.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkQueueInsertDebugUtilsLabelEXT.html
func (c *Commands) QueueInsertDebugUtilsLabelEXT(queue vulkan.Queue, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(c.pfnQueueInsertDebugUtilsLabelEXT, uintptr(queue), uintptr(unsafe.Pointer(c_labelInfo)))
}

func QueueInsertDebugUtilsLabelEXT(queue vulkan.Queue, labelInfo *vulkan.DebugUtilsLabelEXT) {
	c_labelInfo := labelInfo.Raw()
	vulkan.CallSyscall(pfnQueueInsertDebugUtilsLabelEXT, uintptr(queue), uintptr(unsafe.Pointer(c_labelInfo)))
}

// SetDebugUtilsObjectNameEXT - Give an application-defined name to an object (vkSetDebugUtilsObjectNameEXT).
// Parameters:
//   - device: is the device that is associated with the named object passed in via objectHandle.
//   - nameInfo: is a pointer to a VkDebugUtilsObjectNameInfoEXT structure specifying parameters of the name to set on the object.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkSetDebugUtilsObjectNameEXT.html
func (c *Commands) SetDebugUtilsObjectNameEXT(device vulkan.Device, nameInfo *vulkan.DebugUtilsObjectNameInfoEXT) (result vulkan.Result) {
	c_nameInfo := nameInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnSetDebugUtilsObjectNameEXT, uintptr(device), uintptr(unsafe.Pointer(c_nameInfo)))
	return vulkan.Result(r1)
}

func SetDebugUtilsObjectNameEXT(device vulkan.Device, nameInfo *vulkan.DebugUtilsObjectNameInfoEXT) (result vulkan.Result) {
	c_nameInfo := nameInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnSetDebugUtilsObjectNameEXT, uintptr(device), uintptr(unsafe.Pointer(c_nameInfo)))
	return vulkan.Result(r1)
}

// SetDebugUtilsObjectTagEXT - Attach arbitrary data to an object (vkSetDebugUtilsObjectTagEXT).
// Parameters:
//   - device: is the device that created the object.
//   - tagInfo: is a pointer to a VkDebugUtilsObjectTagInfoEXT structure specifying parameters of the tag to attach to the object.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkSetDebugUtilsObjectTagEXT.html
func (c *Commands) SetDebugUtilsObjectTagEXT(device vulkan.Device, tagInfo *vulkan.DebugUtilsObjectTagInfoEXT) (result vulkan.Result) {
	c_tagInfo := tagInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(c.pfnSetDebugUtilsObjectTagEXT, uintptr(device), uintptr(unsafe.Pointer(c_tagInfo)))
	return vulkan.Result(r1)
}

func SetDebugUtilsObjectTagEXT(device vulkan.Device, tagInfo *vulkan.DebugUtilsObjectTagInfoEXT) (result vulkan.Result) {
	c_tagInfo := tagInfo.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnSetDebugUtilsObjectTagEXT, uintptr(device), uintptr(unsafe.Pointer(c_tagInfo)))
	return vulkan.Result(r1)
}

// SubmitDebugUtilsMessageEXT - Inject a message into a debug stream (vkSubmitDebugUtilsMessageEXT).
// Parameters:
//   - instance: is the debug stream's VkInstance.
//   - messageSeverity: is a VkDebugUtilsMessageSeverityFlagBitsEXT value specifying the severity of this event/message.
//   - messageTypes: is a bitmask of VkDebugUtilsMessageTypeFlagBitsEXT specifying which type of event(s) to identify with this message.
//   - callbackData: contains all the callback related data in the VkDebugUtilsMessengerCallbackDataEXT structure.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkSubmitDebugUtilsMessageEXT.html
func (c *Commands) SubmitDebugUtilsMessageEXT(instance vulkan.Instance, messageSeverity vulkan.DebugUtilsMessageSeverityFlagBitsEXT, messageTypes vulkan.DebugUtilsMessageTypeFlagsEXT, callbackData *vulkan.DebugUtilsMessengerCallbackDataEXT) {
	c_callbackData := callbackData.Raw()
	vulkan.CallSyscall(c.pfnSubmitDebugUtilsMessageEXT, uintptr(instance), uintptr(messageSeverity), uintptr(messageTypes), uintptr(unsafe.Pointer(c_callbackData)))
}

func SubmitDebugUtilsMessageEXT(instance vulkan.Instance, messageSeverity vulkan.DebugUtilsMessageSeverityFlagBitsEXT, messageTypes vulkan.DebugUtilsMessageTypeFlagsEXT, callbackData *vulkan.DebugUtilsMessengerCallbackDataEXT) {
	c_callbackData := callbackData.Raw()
	vulkan.CallSyscall(pfnSubmitDebugUtilsMessageEXT, uintptr(instance), uintptr(messageSeverity), uintptr(messageTypes), uintptr(unsafe.Pointer(c_callbackData)))
}
