// Code generated by vk-gen. DO NOT EDIT.

package khr_calibrated_timestamps

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetCalibratedTimestampsKHR                   uintptr
	pfnGetPhysicalDeviceCalibrateableTimeDomainsKHR uintptr
)

// Init resolves and initializes all VK_KHR_calibrated_timestamps extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetCalibratedTimestampsKHR = vulkan.GetDeviceProcAddr(device, "vkGetCalibratedTimestampsKHR")
	pfnGetPhysicalDeviceCalibrateableTimeDomainsKHR = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceCalibrateableTimeDomainsKHR")
}

// GetCalibratedTimestampsKHR - Query calibrated timestamps (vkGetCalibratedTimestampsKHR).
// Parameters:
//   - device: is the logical device used to perform the query.
//   - timestampCount: is the number of timestamps to query.
//   - timestampInfos: is a pointer to an array of timestampCount VkCalibratedTimestampInfoKHR structures, describing the time domains the calibrated timestamps should be captured from.
//   - timestamps: is a pointer to an array of timestampCount 64-bit unsigned integer values in which the requested calibrated timestamp values are returned.
//   - maxDeviation: is a pointer to a 64-bit unsigned integer value in which the strictly positive maximum deviation, in nanoseconds, of the calibrated timestamp values is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetCalibratedTimestampsKHR.html
func GetCalibratedTimestampsKHR(device vulkan.Device, timestampInfos []vulkan.CalibratedTimestampInfoKHR, timestamps *uint64) (maxDeviation uint64, result vulkan.Result) {
	c_timestampInfos := make([]vulkan.RawCalibratedTimestampInfoKHR, len(timestampInfos))
	for i := range timestampInfos {
		if raw := timestampInfos[i].Raw(); raw != nil {
			c_timestampInfos[i] = *raw
		}
	}
	r1, _, _ := vulkan.CallSyscall(pfnGetCalibratedTimestampsKHR, uintptr(device), uintptr(len(timestampInfos)), uintptr(unsafe.Pointer(vulkan.SliceData(c_timestampInfos))), uintptr(unsafe.Pointer(timestamps)), uintptr(unsafe.Pointer(&maxDeviation)))
	return maxDeviation, vulkan.Result(r1)
}

// GetPhysicalDeviceCalibrateableTimeDomainsKHR - Query calibrateable time domains (vkGetPhysicalDeviceCalibrateableTimeDomainsKHR).
// Parameters:
//   - physicalDevice: is the physical device from which to query the set of calibrateable time domains.
//   - timeDomainCount: is a pointer to an integer related to the number of calibrateable time domains available or queried, as described below.
//   - timeDomains: is either NULL or a pointer to an array of VkTimeDomainKHR values, indicating the supported calibrateable time domains.
//
// Success codes: VK_SUCCESS, VK_INCOMPLETE
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceCalibrateableTimeDomainsKHR.html
func GetPhysicalDeviceCalibrateableTimeDomainsKHR(physicalDevice vulkan.PhysicalDevice) (timeDomains []vulkan.TimeDomainKHR, result vulkan.Result) {
	var count uint32
	r1, _, _ := vulkan.CallSyscall(pfnGetPhysicalDeviceCalibrateableTimeDomainsKHR, uintptr(physicalDevice), uintptr(unsafe.Pointer(&count)), 0)
	if vulkan.Result(r1) != vulkan.SUCCESS || count == 0 {
		return nil, vulkan.Result(r1)
	}

	timeDomains = make([]vulkan.TimeDomainKHR, count)
	call2ArgsPtr := uintptr(unsafe.Pointer(&timeDomains[0]))
	r1, _, _ = vulkan.CallSyscall(pfnGetPhysicalDeviceCalibrateableTimeDomainsKHR, uintptr(physicalDevice), uintptr(unsafe.Pointer(&count)), call2ArgsPtr)
	return timeDomains, vulkan.Result(r1)
}
