// Code generated by vk-gen. DO NOT EDIT.

// Package qcom_queue_perf_hint provides bindings for the VK_QCOM_queue_perf_hint extension.
// Author: QCOM
// Contact: Matthew Netsch @mnetsch
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2026-02-26
//
// IP Status:
//
//	No known IP claims.
//
// Interactions and External Dependencies:
//   - Interacts with VKKHRinternallysynchronizedqueues
//
// Contributors:
//   - Matthew Netsch, Qualcomm Technologies, Inc
//
// Description:
//
// This extension exposes power constraints to the application, allowing it to
// provide hints for influencing the device's clock frequency.
//
// These hints are VkQueue state and are persistent across the life of
// the queue until the app updates or removes the constraint.
// The kernel combines the constraints across the active queues from all
// processes to determine the actual clock frequency levels.
//
// Issues:
//
// None.
//
// Version History:
//
//   - Revision 1, 2026-02-26 (Matthew Netsch)
package qcom_queue_perf_hint
