// Code generated by vk-gen. DO NOT EDIT.

// Package nv_compute_shader_derivatives provides bindings for the VK_NV_compute_shader_derivatives extension.
// Author: NV
// Contact: Pat Brown @nvpbrown
// Promoted to: VK_KHR_compute_shader_derivatives
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2018-07-19
//
// IP Status:
//
//	No known IP claims.
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLSLregistry}/nv/GLSLNVcomputeshaderderivatives.txt[GLNVcomputeshaderderivatives]
//
// Contributors:
//   - Pat Brown, NVIDIA
//
// Description:
//
// This extension adds Vulkan support for the
// {spirv}/NV/SPVNVcomputeshaderderivatives.html[SPVNVcomputeshaderderivatives]
// SPIR-V extension.
//
// The SPIR-V extension provides two new execution modes, both of which allow
// compute shaders to use built-ins that evaluate compute derivatives
// explicitly or implicitly.
// Derivatives will be computed via differencing over a 2x2 group of shader
// invocations.
// The DerivativeGroupQuadsNV execution mode assembles shader invocations
// into 2x2 groups, where each group has x and y coordinates of the local
// invocation ID of the form (2m{0,1}, 2n{0,1}).
// The DerivativeGroupLinearNV execution mode assembles shader invocations
// into 2x2 groups, where each group has local invocation index values of the
// form 4m+{0,1,2,3}.
//
// New SPIR-V Capability:
//
//   - <<spirvenv-capabilities-table-ComputeDerivativeGroupQuadsKHR,
//     ComputeDerivativeGroupQuadsNV>>
//   - <<spirvenv-capabilities-table-ComputeDerivativeGroupLinearKHR,
//     ComputeDerivativeGroupLinearNV>>
//
// Issues:
//
// (1) Should we specify that the groups of four shader invocations used for
// derivatives in a compute shader are the same groups of four invocations that
// form a "quad" in shader subgroups?
//
// RESOLVED:
//
// Examples:
//
// None.
//
// Version History:
//
//   - Revision 1, 2018-07-19 (Pat Brown)
//   - Initial draft
package nv_compute_shader_derivatives
