// Code generated by vk-gen. DO NOT EDIT.

package nv_compute_occupancy_priority

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdSetComputeOccupancyPriorityNV uintptr
)

// Init resolves and initializes all VK_NV_compute_occupancy_priority extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdSetComputeOccupancyPriorityNV = vulkan.GetDeviceProcAddr(device, "vkCmdSetComputeOccupancyPriorityNV")
}

// CmdSetComputeOccupancyPriorityNV - Set the compute occupancy priority for subsequent compute dispatches (vkCmdSetComputeOccupancyPriorityNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - parameters: is a pointer to a VkComputeOccupancyPriorityParametersNV structure specifying the occupancy priority parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetComputeOccupancyPriorityNV.html
func CmdSetComputeOccupancyPriorityNV(commandBuffer vulkan.CommandBuffer, parameters *vulkan.ComputeOccupancyPriorityParametersNV) {
	c_parameters := parameters.Raw()
	vulkan.CallSyscall(pfnCmdSetComputeOccupancyPriorityNV, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_parameters)))
}
