// Code generated by vk-gen. DO NOT EDIT.

package arm_tensors

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnBindTensorMemoryARM                          uintptr
	pfnCmdCopyTensorARM                             uintptr
	pfnCreateTensorARM                              uintptr
	pfnCreateTensorViewARM                          uintptr
	pfnDestroyTensorARM                             uintptr
	pfnDestroyTensorViewARM                         uintptr
	pfnGetDeviceTensorMemoryRequirementsARM         uintptr
	pfnGetPhysicalDeviceExternalTensorPropertiesARM uintptr
	pfnGetTensorMemoryRequirementsARM               uintptr
	pfnGetTensorOpaqueCaptureDescriptorDataARM      uintptr
	pfnGetTensorViewOpaqueCaptureDescriptorDataARM  uintptr
)

// Init resolves and initializes all VK_ARM_tensors extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnBindTensorMemoryARM = vulkan.GetDeviceProcAddr(device, "vkBindTensorMemoryARM")
	pfnCmdCopyTensorARM = vulkan.GetDeviceProcAddr(device, "vkCmdCopyTensorARM")
	pfnCreateTensorARM = vulkan.GetDeviceProcAddr(device, "vkCreateTensorARM")
	pfnCreateTensorViewARM = vulkan.GetDeviceProcAddr(device, "vkCreateTensorViewARM")
	pfnDestroyTensorARM = vulkan.GetDeviceProcAddr(device, "vkDestroyTensorARM")
	pfnDestroyTensorViewARM = vulkan.GetDeviceProcAddr(device, "vkDestroyTensorViewARM")
	pfnGetDeviceTensorMemoryRequirementsARM = vulkan.GetDeviceProcAddr(device, "vkGetDeviceTensorMemoryRequirementsARM")
	pfnGetPhysicalDeviceExternalTensorPropertiesARM = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalTensorPropertiesARM")
	pfnGetTensorMemoryRequirementsARM = vulkan.GetDeviceProcAddr(device, "vkGetTensorMemoryRequirementsARM")
	pfnGetTensorOpaqueCaptureDescriptorDataARM = vulkan.GetDeviceProcAddr(device, "vkGetTensorOpaqueCaptureDescriptorDataARM")
	pfnGetTensorViewOpaqueCaptureDescriptorDataARM = vulkan.GetDeviceProcAddr(device, "vkGetTensorViewOpaqueCaptureDescriptorDataARM")
}

// BindTensorMemoryARM - Bind device memory to tensor objects (vkBindTensorMemoryARM).
// Parameters:
//   - device: is the logical device that owns the buffers and memory.
//   - bindInfoCount: is the number of elements in pBindInfos.
//   - bindInfos: is a pointer to an array of structures of type VkBindTensorMemoryInfoARM, describing tensors and memory to bind.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkBindTensorMemoryARM.html
func BindTensorMemoryARM(device vulkan.Device, bindInfos []vulkan.BindTensorMemoryInfoARM) (result vulkan.Result) {
	c_bindInfos := make([]vulkan.RawBindTensorMemoryInfoARM, len(bindInfos))
	for i := range bindInfos {
		if raw := bindInfos[i].Raw(); raw != nil {
			c_bindInfos[i] = *raw
		}
	}
	r1, _, _ := vulkan.CallSyscall(pfnBindTensorMemoryARM, uintptr(device), uintptr(len(bindInfos)), uintptr(unsafe.Pointer(vulkan.SliceData(c_bindInfos))))
	return vulkan.Result(r1)
}

// CmdCopyTensorARM - Copy data between tensors (vkCmdCopyTensorARM).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - copyTensorInfo: is a pointer to VkCopyTensorInfoARM structure describing the copy parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdCopyTensorARM.html
func CmdCopyTensorARM(commandBuffer vulkan.CommandBuffer, copyTensorInfo *vulkan.CopyTensorInfoARM) {
	c_copyTensorInfo := copyTensorInfo.Raw()
	vulkan.CallSyscall(pfnCmdCopyTensorARM, uintptr(commandBuffer), uintptr(unsafe.Pointer(c_copyTensorInfo)))
}

// CreateTensorARM - Create a new tensor object (vkCreateTensorARM).
// Parameters:
//   - device: is the logical device that creates the tensor.
//   - createInfo: is a pointer to a VkTensorCreateInfoARM structure containing parameters to be used to create the tensor.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//   - tensor: is a pointer to a VkTensorARM handle in which the resulting tensor object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateTensorARM.html
func CreateTensorARM(device vulkan.Device, createInfo *vulkan.TensorCreateInfoARM, allocator *vulkan.AllocationCallbacks) (tensor vulkan.TensorARM, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateTensorARM, uintptr(device), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&tensor)))
	return tensor, vulkan.Result(r1)
}

// CreateTensorViewARM - Create an tensor view from an existing tensor (vkCreateTensorViewARM).
// Parameters:
//   - device: is the logical device that creates the tensor view.
//   - createInfo: is a pointer to an instance of the VkTensorViewCreateInfoARM structure containing parameters to be used to create the tensor view.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//   - view: is a pointer to a VkTensorViewARM handle in which the resulting tensor view object is returned.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateTensorViewARM.html
func CreateTensorViewARM(device vulkan.Device, createInfo *vulkan.TensorViewCreateInfoARM, allocator *vulkan.AllocationCallbacks) (view vulkan.TensorViewARM, result vulkan.Result) {
	c_createInfo := createInfo.Raw()
	c_allocator := allocator.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnCreateTensorViewARM, uintptr(device), uintptr(unsafe.Pointer(c_createInfo)), uintptr(unsafe.Pointer(c_allocator)), uintptr(unsafe.Pointer(&view)))
	return view, vulkan.Result(r1)
}

// DestroyTensorARM - Destroy a tensor object (vkDestroyTensorARM).
// Parameters:
//   - device: is the logical device that destroys the tensor.
//   - tensor: is the tensor to destroy.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkDestroyTensorARM.html
func DestroyTensorARM(device vulkan.Device, tensor vulkan.TensorARM, allocator *vulkan.AllocationCallbacks) {
	c_allocator := allocator.Raw()
	vulkan.CallSyscall(pfnDestroyTensorARM, uintptr(device), uintptr(tensor), uintptr(unsafe.Pointer(c_allocator)))
}

// DestroyTensorViewARM - Destroy a tensor view object (vkDestroyTensorViewARM).
// Parameters:
//   - device: is the logical device that destroys the tensor view.
//   - tensorView: is the tensor view to destroy.
//   - allocator: controls host memory allocation as described in the Memory Allocation chapter.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkDestroyTensorViewARM.html
func DestroyTensorViewARM(device vulkan.Device, tensorView vulkan.TensorViewARM, allocator *vulkan.AllocationCallbacks) {
	c_allocator := allocator.Raw()
	vulkan.CallSyscall(pfnDestroyTensorViewARM, uintptr(device), uintptr(tensorView), uintptr(unsafe.Pointer(c_allocator)))
}

// GetDeviceTensorMemoryRequirementsARM - Returns the memory requirements for specified tensor creation infos (vkGetDeviceTensorMemoryRequirementsARM).
// Parameters:
//   - device: is the logical device intended to own the tensor.
//   - info: is a pointer to a VkDeviceTensorMemoryRequirementsARM structure containing parameters required for the memory requirements query.
//   - memoryRequirements: is a pointer to a VkMemoryRequirements2 structure in which the memory requirements of the tensor object are returned.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetDeviceTensorMemoryRequirementsARM.html
func GetDeviceTensorMemoryRequirementsARM(device vulkan.Device, info *vulkan.DeviceTensorMemoryRequirementsARM) (memoryRequirements vulkan.MemoryRequirements2) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnGetDeviceTensorMemoryRequirementsARM, uintptr(device), uintptr(unsafe.Pointer(c_info)), uintptr(unsafe.Pointer(&memoryRequirements)))
	return memoryRequirements
}

// GetPhysicalDeviceExternalTensorPropertiesARM - Function for querying external tensor handle capabilities. (vkGetPhysicalDeviceExternalTensorPropertiesARM).
// Parameters:
//   - physicalDevice: is the physical device from which to query the tensor capabilities.
//   - externalTensorInfo: is a pointer to a VkPhysicalDeviceExternalTensorInfoARM structure describing the parameters that would be consumed by vkCreateTensorARM.
//   - externalTensorProperties: is a pointer to a VkExternalTensorPropertiesARM structure in which the capabilities are returned.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceExternalTensorPropertiesARM.html
func GetPhysicalDeviceExternalTensorPropertiesARM(physicalDevice vulkan.PhysicalDevice, externalTensorInfo *vulkan.PhysicalDeviceExternalTensorInfoARM) (externalTensorProperties vulkan.ExternalTensorPropertiesARM) {
	c_externalTensorInfo := externalTensorInfo.Raw()
	vulkan.CallSyscall(pfnGetPhysicalDeviceExternalTensorPropertiesARM, uintptr(physicalDevice), uintptr(unsafe.Pointer(c_externalTensorInfo)), uintptr(unsafe.Pointer(&externalTensorProperties)))
	return externalTensorProperties
}

// GetTensorMemoryRequirementsARM - Returns the memory requirements for specified Vulkan object (vkGetTensorMemoryRequirementsARM).
// Parameters:
//   - device: is the logical device that owns the tensor.
//   - info: is a pointer to a VkTensorMemoryRequirementsInfoARM structure containing parameters required for the memory requirements query.
//   - memoryRequirements: is a pointer to a VkMemoryRequirements2 structure in which the memory requirements of the tensor object are returned.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetTensorMemoryRequirementsARM.html
func GetTensorMemoryRequirementsARM(device vulkan.Device, info *vulkan.TensorMemoryRequirementsInfoARM) (memoryRequirements vulkan.MemoryRequirements2) {
	c_info := info.Raw()
	vulkan.CallSyscall(pfnGetTensorMemoryRequirementsARM, uintptr(device), uintptr(unsafe.Pointer(c_info)), uintptr(unsafe.Pointer(&memoryRequirements)))
	return memoryRequirements
}

// GetTensorOpaqueCaptureDescriptorDataARM - Get tensor opaque capture descriptor data (vkGetTensorOpaqueCaptureDescriptorDataARM).
// Parameters:
//   - device: is the logical device that gets the data.
//   - info: is a pointer to a VkTensorCaptureDescriptorDataInfoARM structure specifying the tensor.
//   - data: is a pointer to a user-allocated buffer where the data will be written.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetTensorOpaqueCaptureDescriptorDataARM.html
func GetTensorOpaqueCaptureDescriptorDataARM(device vulkan.Device, info *vulkan.TensorCaptureDescriptorDataInfoARM) (data unsafe.Pointer, result vulkan.Result) {
	c_info := info.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetTensorOpaqueCaptureDescriptorDataARM, uintptr(device), uintptr(unsafe.Pointer(c_info)), uintptr(unsafe.Pointer(&data)))
	return data, vulkan.Result(r1)
}

// GetTensorViewOpaqueCaptureDescriptorDataARM - Get tensor view opaque capture descriptor data (vkGetTensorViewOpaqueCaptureDescriptorDataARM).
// Parameters:
//   - device: is the logical device that gets the data.
//   - info: is a pointer to a VkTensorViewCaptureDescriptorDataInfoARM structure specifying the tensor view.
//   - data: is a pointer to a user-allocated buffer where the data will be written.
//
// Success codes: VK_SUCCESS
// Error codes: VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_UNKNOWN, VK_ERROR_VALIDATION_FAILED
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetTensorViewOpaqueCaptureDescriptorDataARM.html
func GetTensorViewOpaqueCaptureDescriptorDataARM(device vulkan.Device, info *vulkan.TensorViewCaptureDescriptorDataInfoARM) (data unsafe.Pointer, result vulkan.Result) {
	c_info := info.Raw()
	r1, _, _ := vulkan.CallSyscall(pfnGetTensorViewOpaqueCaptureDescriptorDataARM, uintptr(device), uintptr(unsafe.Pointer(c_info)), uintptr(unsafe.Pointer(&data)))
	return data, vulkan.Result(r1)
}
