// Code generated by vk-gen. DO NOT EDIT.

package huawei_cluster_culling_shader

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdDrawClusterHUAWEI         uintptr
	pfnCmdDrawClusterIndirectHUAWEI uintptr
)

// Init resolves and initializes all VK_HUAWEI_cluster_culling_shader extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdDrawClusterHUAWEI = vulkan.GetDeviceProcAddr(device, "vkCmdDrawClusterHUAWEI")
	pfnCmdDrawClusterIndirectHUAWEI = vulkan.GetDeviceProcAddr(device, "vkCmdDrawClusterIndirectHUAWEI")
}

// CmdDrawClusterHUAWEI - Draw cluster culling work items (vkCmdDrawClusterHUAWEI).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - groupCountX: is the number of local workgroups to dispatch in the X dimension.
//   - groupCountY: is the number of local workgroups to dispatch in the Y dimension.
//   - groupCountZ: is the number of local workgroups to dispatch in the Z dimension.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawClusterHUAWEI.html
func CmdDrawClusterHUAWEI(commandBuffer vulkan.CommandBuffer, groupCountX uint32, groupCountY uint32, groupCountZ uint32) {
	vulkan.CallSyscall(pfnCmdDrawClusterHUAWEI, uintptr(commandBuffer), uintptr(groupCountX), uintptr(groupCountY), uintptr(groupCountZ))
}

// CmdDrawClusterIndirectHUAWEI - Issue an indirect cluster culling draw into a command buffer (vkCmdDrawClusterIndirectHUAWEI).
// Parameters:
//   - commandBuffer: is the command buffer into which the command is recorded.
//   - buffer: is the buffer containing draw parameters.
//   - offset: is the byte offset into buffer where parameters begin.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawClusterIndirectHUAWEI.html
func CmdDrawClusterIndirectHUAWEI(commandBuffer vulkan.CommandBuffer, buffer vulkan.Buffer, offset vulkan.DeviceSize) {
	vulkan.CallSyscall(pfnCmdDrawClusterIndirectHUAWEI, uintptr(commandBuffer), uintptr(buffer), uintptr(offset))
}
