// Code generated by vk-gen. DO NOT EDIT.

package amd_anti_lag

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnAntiLagUpdateAMD uintptr
)

// Init resolves and initializes all VK_AMD_anti_lag extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnAntiLagUpdateAMD = vulkan.GetDeviceProcAddr(device, "vkAntiLagUpdateAMD")
}

// AntiLagUpdateAMD - Provide information to reduce latency (vkAntiLagUpdateAMD).
// Parameters:
//   - device: is the logical device
//   - data: is a pointer to a VkAntiLagDataAMD structure containing latency reduction parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkAntiLagUpdateAMD.html
func AntiLagUpdateAMD(device vulkan.Device, data *vulkan.AntiLagDataAMD) {
	c_data := data.Raw()
	vulkan.CallSyscall(pfnAntiLagUpdateAMD, uintptr(device), uintptr(unsafe.Pointer(c_data)))
}
