// Code generated by vk-gen. DO NOT EDIT.

// Package nn_vi_surface provides bindings for the VK_NN_vi_surface extension.
// Author: NN
// Contact: Mathias Heyer gitlab:@mheyer
// Platform: vi
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2016-12-02
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Mathias Heyer, NVIDIA
//   - Michael Chock, NVIDIA
//   - Yasuhiro Yoshioka, Nintendo
//   - Daniel Koch, NVIDIA
//
// Description:
//
// The VKNNvi_surface extension is an instance extension.
// It provides a mechanism to create a VkSurfaceKHR object (defined by
// the VKKHRsurface extension) associated with an
// nn::code:vi::code:Layer.
//
// Issues:
//
// 1) Does VI need a way to query for compatibility between a particular
// physical device (and queue family?) and a specific VI display?
//
// RESOLVED:
// It is currently always assumed that the device and display will always be
// compatible.
//
// 2) VkViSurfaceCreateInfoNN::pname:window is intended to store an
// nn::code:vi::code:NativeWindowHandle, but its declared type is a bare
// void* to store the window handle.
// Why the discrepancy?
//
// RESOLVED:
// The definition for the VI native window handle type is defined inside the
// nn::code:vi C++ namespace.
// This prevents its use in C source files.
// nn::code:vi::code:NativeWindowHandle is always defined to be
// void, so this extension uses void to match.
//
// Version History:
//
//   - Revision 1, 2016-12-2 (Michael Chock)
//   - Initial draft.
package nn_vi_surface
