// Code generated by vk-gen. DO NOT EDIT.

// Package khr_internally_synchronized_queues provides bindings for the VK_KHR_internally_synchronized_queues extension.
// Author: KHR
// Contact: Shahbaz Youssefi @syoussefi
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2025-02-04
//
// Contributors:
//   - Shahbaz Youssefi, Google
//   - Daniel Rakos, RasterGrid
//   - Jeff Bolz, Nvidia
//   - Hans-Kristian Arntzen, Valve
//
// Description:
//
// VKKHRinternallysynchronizedqueues allows queues to opt into being
// internally synchronized via the
// VKDEVICEQUEUECREATEINTERNALLYSYNCHRONIZEDBIT_KHR flag.
//
// Issues:
//
// None.
//
// Version History:
//
//   - Revision 0, 2025-01-07 (Daniel Rakos)
//
//   - Initial proposal
//
//   - Revision 1, 2025-02-04 (Shahbaz Youssefi)
//
//   - Initial revision
package khr_internally_synchronized_queues
