// Code generated by vk-gen. DO NOT EDIT.

// Package mvk_ios_surface provides bindings for the VK_MVK_ios_surface extension.
// Author: MVK
// Contact: Bill Hollings @billhollings
// Deprecated by: VK_EXT_metal_surface
// Platform: ios
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2020-07-31
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Bill Hollings, The Brenwill Workshop Ltd.
//
// Description:
//
// The VKMVKios_surface extension is an instance extension.
// It provides a mechanism to create a VkSurfaceKHR object (defined by
// the VKKHRsurface extension) based on a UIView, the native
// surface type of iOS, which is underpinned by a basetype:CAMetalLayer, to
// support rendering to the surface using Apple's Metal framework.
//
// Deprecation by `VK_EXT_metal_surface`:
//
// The VKMVKios_surface extension is considered deprecated and has been
// superseded by the VKEXTmetal_surface extension.
//
// Version History:
//
//   - Revision 1, 2017-02-15 (Bill Hollings)
//
//   - Initial draft.
//
//   - Revision 2, 2017-02-24 (Bill Hollings)
//
//   - Minor syntax fix to emphasize firm requirement for UIView to be
//     backed by a CAMetalLayer.
//
//   - Revision 3, 2020-07-31 (Bill Hollings)
//
//   - Update documentation on requirements for UIView.
//
//   - Mark as deprecated by VKEXTmetal_surface.
package mvk_ios_surface
