// Code generated by vk-gen. DO NOT EDIT.

package nv_clip_space_w_scaling

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnCmdSetViewportWScalingNV uintptr
)

// Init resolves and initializes all VK_NV_clip_space_w_scaling extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnCmdSetViewportWScalingNV = vulkan.GetDeviceProcAddr(device, "vkCmdSetViewportWScalingNV")
}

// CmdSetViewportWScalingNV - Set the viewport W scaling dynamically for a command buffer (vkCmdSetViewportWScalingNV).
// Parameters:
//   - commandBuffer: is the command buffer into which the command will be recorded.
//   - firstViewport: is the index of the first viewport whose parameters are updated by the command.
//   - viewportCount: is the number of viewports whose parameters are updated by the command.
//   - viewportWScalings: is a pointer to an array of VkViewportWScalingNV structures specifying viewport parameters.
//
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdSetViewportWScalingNV.html
func CmdSetViewportWScalingNV(commandBuffer vulkan.CommandBuffer, firstViewport uint32, viewportWScalings []vulkan.ViewportWScalingNV) {
	c_viewportWScalings := make([]vulkan.RawViewportWScalingNV, len(viewportWScalings))
	for i := range viewportWScalings {
		if raw := viewportWScalings[i].Raw(); raw != nil {
			c_viewportWScalings[i] = *raw
		}
	}
	vulkan.CallSyscall(pfnCmdSetViewportWScalingNV, uintptr(commandBuffer), uintptr(firstViewport), uintptr(len(viewportWScalings)), uintptr(unsafe.Pointer(vulkan.SliceData(c_viewportWScalings))))
}
