// Code generated by vk-gen. DO NOT EDIT.

// Package ext_directfb_surface provides bindings for the VK_EXT_directfb_surface extension.
// Author: EXT
// Contact: Nicolas Caramelli @caramelli
// Platform: directfb
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2020-06-16
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Nicolas Caramelli
//
// Description:
//
// The VKEXTdirectfb_surface extension is an instance extension.
// It provides a mechanism to create a VkSurfaceKHR object (defined by
// the VKKHRsurface extension) that refers to a DirectFB
// IDirectFBSurface, as well as a query to determine support for rendering
// via DirectFB.
//
// Version History:
//
//   - Revision 1, 2020-06-16 (Nicolas Caramelli)
//   - Initial version
package ext_directfb_surface
