// Code generated by vk-gen. DO NOT EDIT.

// Package ext_metal_surface provides bindings for the VK_EXT_metal_surface extension.
// Author: EXT
// Contact: Dzmitry Malyshau @kvark
// Platform: metal
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2018-10-01
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Dzmitry Malyshau, Mozilla Corp.
//
// Description:
//
// The VKEXTmetal_surface extension is an instance extension.
// It provides a mechanism to create a VkSurfaceKHR object (defined by
// the VKKHRsurface extension) from basetype:CAMetalLayer, which is
// the native rendering surface of Apple's Metal framework.
//
// Version History:
//
//   - Revision 1, 2018-10-01 (Dzmitry Malyshau)
//   - Initial version
package ext_metal_surface
