// Code generated by vk-gen. DO NOT EDIT.

// Package nvx_multiview_per_view_attributes provides bindings for the VK_NVX_multiview_per_view_attributes extension.
// Author: NVX
// Contact: Jeff Bolz @jeffbolznv
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2017-01-13
//
// IP Status:
//
//	No known IP claims.
//
// Interactions and External Dependencies:
//   - This extension provides API support for
//     {GLSLregistry}/nvx/GLNVXmultiviewperviewattributes.txt[GLNVXmultiviewperviewattributes]
//   - This extension interacts with VKNVviewport_array2.
//
// Contributors:
//   - Jeff Bolz, NVIDIA
//   - Daniel Koch, NVIDIA
//
// Description:
//
// This extension adds a new way to write shaders to be used with multiview
// subpasses, where the attributes for all views are written out by a single
// invocation of the
// <<pipelines-graphics-subsets-pre-rasterization,pre-rasterization shader
// stages>>.
// Related SPIR-V and GLSL extensions SPVNVXmultiviewperview_attributes
// and GLNVXmultiviewperview_attributes introduce per-view position and
// viewport mask attributes arrays, and this extension defines how those
// per-view attribute arrays are interpreted by Vulkan.
// Pipelines using per-view attributes may: only execute the
// <<pipelines-graphics-subsets-pre-rasterization,pre-rasterization shader
// stages>> once for all views rather than once per-view, which reduces
// redundant shading work.
//
// A subpass creation flag controls whether the subpass uses this extension.
// A subpass must: either exclusively use this extension or not use it at all.
//
// Some Vulkan implementations only support the position attribute varying
// between views in the X component.
// A subpass can declare via a second creation flag whether all pipelines
// compiled for this subpass will obey this restriction.
//
// Shaders that use the new per-view outputs (e.g. gl_PositionPerViewNV)
// must: also write the non-per-view output (gl_Position), and the values
// written must: be such that `gl_Position =
// glPositionPerViewNV[glViewIndex]` for all views in the subpass.
// Implementations are free to either use the per-view outputs or the
// non-per-view outputs, whichever would be more efficient.
//
// If the VKNVviewport_array2 extension is not also supported and
// enabled, the per-view viewport mask must: not be used.
//
// New Built-In Variables:
//
//   - PositionPerViewNV
//   - ViewportMaskPerViewNV
//
// New SPIR-V Capabilities:
//
//   - <<spirvenv-capabilities-table-PerViewAttributesNV,
//     PerViewAttributesNV>>
//
// Examples:
//
// #version 450 core
//
// #extension GLKHXmultiview : enable
// #extension GLNVXmultiviewperview_attributes : enable
//
// layout(location = 0) in vec4 position;
// layout(set = 0, binding = 0) uniform Block { mat4 mvpPerView[2]; } buf;
//
// void main()
//
//	{
//	    gl_PositionPerViewNV[0] = buf.mvpPerView[0] * position;
//	    gl_PositionPerViewNV[1] = buf.mvpPerView[1] * position;
//	    glPosition = buf.mvpPerView[glViewIndex] * position;
//	}
//
// Version History:
//
//   - Revision 1, 2017-01-13 (Jeff Bolz)
//   - Internal revisions
package nvx_multiview_per_view_attributes
