// Code generated by vk-gen. DO NOT EDIT.

package khr_external_fence_capabilities

import (
	"unsafe"

	"github.com/KCoen/vk/vulkan"
)

var _ = unsafe.Pointer(nil)

// Procedure addresses resolved by Init
var (
	pfnGetPhysicalDeviceExternalFencePropertiesKHR uintptr
)

// Init resolves and initializes all VK_KHR_external_fence_capabilities extension procedure addresses.
func Init(instance vulkan.Instance, device vulkan.Device) {
	pfnGetPhysicalDeviceExternalFencePropertiesKHR = vulkan.GetInstanceProcAddr(instance, "vkGetPhysicalDeviceExternalFencePropertiesKHR")
}

// GetPhysicalDeviceExternalFencePropertiesKHR executes vkGetPhysicalDeviceExternalFencePropertiesKHR.
// Documented at: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceExternalFencePropertiesKHR.html
func GetPhysicalDeviceExternalFencePropertiesKHR() {
	vulkan.CallSyscall(pfnGetPhysicalDeviceExternalFencePropertiesKHR)
}
