// Code generated by vk-gen. DO NOT EDIT.

// Package khr_shader_integer_dot_product provides bindings for the VK_KHR_shader_integer_dot_product extension.
// Author: KHR
// Contact: Kevin Petit @kpet
// Promoted to: VK_VERSION_1_3
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2021-06-16
//
// Interactions and External Dependencies:
//   - This extension interacts with VKKHRshaderfloat16int8.
//
// IP Status:
//
//	No known IP claims.
//
// Contributors:
//   - Kévin Petit, Arm Ltd.
//   - Jeff Bolz, NVidia
//   - Spencer Fricke, Samsung
//   - Jesse Hall, Google
//   - John Kessenich, Google
//   - Graeme Leese, Broadcom
//   - Einar Hov, Arm Ltd.
//   - Stuart Brady, Arm Ltd.
//   - Pablo Cascon, Arm Ltd.
//   - Tobias Hector, AMD
//   - Jeff Leger, Qualcomm
//   - Ruihao Zhang, Qualcomm
//   - Pierre Boudier, NVidia
//   - Jon Leech, The Khronos Group
//   - Tom Olson, Arm Ltd.
//
// Description:
//
// This extension adds support for the integer dot product SPIR-V instructions
// defined in SPVKHRintegerdotproduct.
// These instructions are particularly useful for neural network inference and
// training but find uses in other general-purpose compute applications as
// well.
//
// Promotion to Vulkan 1.3:
//
// Vulkan APIs in this extension are included in core Vulkan 1.3, with the KHR
// suffix omitted.
// External interactions defined by this extension, such as SPIR-V token names,
// retain their original names.
// The original Vulkan API names are still available as aliases of the core
// functionality.
//
// New SPIR-V Capabilities:
//
//   - <<spirvenv-capabilities-table-DotProductInputAll,
//     DotProductInputAllKHR>>
//   - <<spirvenv-capabilities-table-DotProductInput4x8Bit,
//     DotProductInput4x8BitKHR>>
//   - <<spirvenv-capabilities-table-DotProductInput4x8BitPacked,
//     DotProductInput4x8BitPackedKHR>>
//   - DotProductKHR
//
// Version History:
//
//   - Revision 1, 2021-06-16 (Kévin Petit)
//   - Initial revision
package khr_shader_integer_dot_product
