// Code generated by vk-gen. DO NOT EDIT.

// Package nv_display_stereo provides bindings for the VK_NV_display_stereo extension.
// Author: NV
// Contact: Russell Chou @russellcnv
//
// Other Extension Metadata:
//
// Last Modified Date:
//
//	2024-11-20
//
// Contributors:
//   - Russell Chou, NVIDIA
//   - Jeff Juliano, NVIDIA
//   - James Jones, NVIDIA
//
// Description:
//
// This extension allows the application to choose which type of 3D stereo
// hardware it wants to use so the driver can configure it properly.
// This configuration is useful for swapchains created from display surfaces
// because some environments do not have an intermediate windowing system
// available for easy configuration.
// This extension will override any stereo type configuration in the windowing
// system.
//
// For HDMI 3D, only some display modes support stereo rendering, and a new
// structure is needed to expose that information to the application.
//
// Version History:
//
//   - Revision 1, 2024-11-20 (Russell Chou)
//   - Initial release
package nv_display_stereo
